-- +goose Up
-- The schema a node starts from. What each table holds is in SPEC.md sec. 11.2, which
-- internal/cli/doclint_test.go holds to the tables made here. The comments below say why an
-- index or a trigger exists.

CREATE TABLE owners (
    id text NOT NULL,
    display_name text NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT owners_pkey PRIMARY KEY (id)
);

CREATE TABLE credentials (
    id text NOT NULL,
    owner_id text NOT NULL,
    kind text NOT NULL,
    tag text DEFAULT ''::text NOT NULL,
    data bytea NOT NULL,
    created_at bigint NOT NULL,
    last_used_at bigint,
    CONSTRAINT credentials_kind_check CHECK ((kind = ANY (ARRAY['passkey'::text, 'oauth'::text, 'password'::text]))),
    CONSTRAINT credentials_pkey PRIMARY KEY (id),
    CONSTRAINT credentials_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);
CREATE INDEX credentials_owner ON credentials (owner_id);

CREATE TABLE sessions (
    id text NOT NULL,
    owner_id text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT sessions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE tokens (
    id text NOT NULL,
    owner_id text NOT NULL,
    label text NOT NULL,
    hash bytea NOT NULL,
    account_id text,
    created_at bigint NOT NULL,
    revoked_at bigint,
    CONSTRAINT tokens_pkey PRIMARY KEY (id),
    CONSTRAINT tokens_hash_key UNIQUE (hash),
    CONSTRAINT tokens_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE accounts (
    id text NOT NULL,
    slug text NOT NULL,
    display_name text NOT NULL,
    algo text NOT NULL,
    fingerprint text,
    key_sealed bytea,
    seal text DEFAULT 'required'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at bigint NOT NULL,
    root_fingerprint text,
    root_cert bytea,
    accept_new_hosts text DEFAULT 'auto'::text NOT NULL,
    CONSTRAINT accounts_algo_check CHECK ((algo = ANY (ARRAY['p256'::text, 'ed25519'::text]))),
    CONSTRAINT accounts_seal_check CHECK ((seal = ANY (ARRAY['none'::text, 'optional'::text, 'required'::text]))),
    CONSTRAINT accounts_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text]))),
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_fingerprint_key UNIQUE (fingerprint),
    CONSTRAINT accounts_slug_key UNIQUE (slug)
);

CREATE TABLE memberships (
    owner_id text NOT NULL,
    account_id text NOT NULL,
    role text DEFAULT 'admin'::text NOT NULL,
    CONSTRAINT memberships_role_check CHECK ((role = 'admin'::text)),
    CONSTRAINT memberships_pkey PRIMARY KEY (owner_id, account_id),
    CONSTRAINT memberships_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT memberships_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);

CREATE TABLE audit_events (
    seq bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ts bigint NOT NULL,
    account_id text,
    actor_kind text NOT NULL,
    actor_id text NOT NULL,
    action text NOT NULL,
    resource text NOT NULL,
    outcome text NOT NULL,
    request_id text DEFAULT ''::text NOT NULL,
    details text DEFAULT '{}'::text NOT NULL,
    prev_hash text NOT NULL,
    hash text NOT NULL,
    CONSTRAINT audit_events_actor_kind_check CHECK ((actor_kind = ANY (ARRAY['owner'::text, 'token'::text, 'contact'::text, 'guest'::text, 'cli'::text, 'system'::text]))),
    CONSTRAINT audit_events_pkey PRIMARY KEY (seq)
);
-- One actor's trail (ListAuditEventsByActor, ListAuditEventsPageByActor), in chain order.
CREATE INDEX audit_events_actor ON audit_events (actor_id, seq);
-- The hourly sweep asks which identities left long enough ago (ListDueLeaves): the few
-- account_leave rows among all the others, in chain order.
CREATE INDEX audit_events_leaves ON audit_events (seq) WHERE (action = 'account_leave'::text);
-- A row is deleted only once it is archived: a row the head anchor covers (audit_anchor), or a
-- row whose seq and hash are listed in audit_archive_rows. Every other DELETE is refused, so the
-- engine, not a convention in application code, stops rows being removed without a re-anchor.
-- +goose StatementBegin
CREATE FUNCTION audit_events_prune_guard() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM audit_anchor WHERE id = 1 AND archived_through_seq >= OLD.seq
    ) AND NOT EXISTS (
        SELECT 1 FROM audit_archive_rows WHERE seq = OLD.seq AND hash = OLD.hash
    ) THEN
        RAISE EXCEPTION 'audit_events: only rows already archived and anchored may be pruned';
    END IF;
    RETURN OLD;
END;
$$;
-- +goose StatementEnd
CREATE TRIGGER audit_events_delete_only_archived BEFORE DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_events_prune_guard();
-- The audit trail is append-only: a row is never updated.
-- +goose StatementBegin
CREATE FUNCTION audit_events_immutable() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only';
END;
$$;
-- +goose StatementEnd
CREATE TRIGGER audit_events_no_update BEFORE UPDATE ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();

CREATE TABLE contacts (
    id text NOT NULL,
    account_id text NOT NULL,
    fingerprint text NOT NULL,
    spki bytea,
    status text NOT NULL,
    preset text DEFAULT 'basic'::text NOT NULL,
    permissions text DEFAULT '["message.text"]'::text NOT NULL,
    trust_flag text DEFAULT 'messages_only'::text NOT NULL,
    display_name text DEFAULT ''::text NOT NULL,
    card text DEFAULT ''::text NOT NULL,
    created_at bigint NOT NULL,
    pinned_at bigint,
    their_permissions text DEFAULT '[]'::text NOT NULL,
    petname text DEFAULT ''::text NOT NULL,
    invite_id text DEFAULT ''::text NOT NULL,
    endpoint text DEFAULT ''::text NOT NULL,
    leaf bytea,
    chain_sent_kid text DEFAULT ''::text NOT NULL,
    root_cert bytea,
    ever_active bigint DEFAULT 0 NOT NULL,
    handshake_due bigint DEFAULT 0 NOT NULL,
    requested_at bigint,
    leaf_fingerprint text,
    CONSTRAINT contacts_status_check CHECK ((status = ANY (ARRAY['active'::text, 'pending_in'::text, 'pending_out'::text, 'blocked'::text]))),
    CONSTRAINT contacts_trust_flag_check CHECK ((trust_flag = ANY (ARRAY['messages_only'::text, 'may_instruct'::text]))),
    CONSTRAINT contacts_pkey PRIMARY KEY (id),
    CONSTRAINT contacts_account_id_fingerprint_key UNIQUE (account_id, fingerprint),
    CONSTRAINT contacts_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX contacts_account_created ON contacts (account_id, created_at, id);
CREATE INDEX contacts_account_endpoint ON contacts (account_id, endpoint);
CREATE INDEX contacts_account_leaf_fingerprint ON contacts (account_id, leaf_fingerprint);
-- The owner's wait counts one account's contact requests awaiting approval on every wake
-- (CountContactsByStatus).
CREATE INDEX contacts_account_status ON contacts (account_id, status);
CREATE INDEX contacts_pending_requested ON contacts (account_id, requested_at) WHERE (status = ANY (ARRAY['pending_in'::text, 'pending_out'::text]));

CREATE TABLE invites (
    id text NOT NULL,
    account_id text NOT NULL,
    token_hash bytea NOT NULL,
    expires_at bigint NOT NULL,
    max_uses bigint DEFAULT 1 NOT NULL,
    uses bigint DEFAULT 0 NOT NULL,
    auto_accept bigint DEFAULT 0 NOT NULL,
    preset text DEFAULT 'basic'::text NOT NULL,
    permissions text DEFAULT '["message.text"]'::text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    revoked_at bigint,
    created_at bigint NOT NULL,
    CONSTRAINT invites_pkey PRIMARY KEY (id),
    CONSTRAINT invites_token_hash_key UNIQUE (token_hash),
    CONSTRAINT invites_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX invites_account_created ON invites (account_id, created_at, id);

CREATE TABLE threads (
    id text NOT NULL,
    account_id text NOT NULL,
    contact_fpr text NOT NULL,
    topic text DEFAULT ''::text NOT NULL,
    created_at bigint NOT NULL,
    last_at bigint NOT NULL,
    last_read_seq bigint DEFAULT 0 NOT NULL,
    CONSTRAINT threads_pkey PRIMARY KEY (account_id, id),
    CONSTRAINT threads_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX threads_account_last ON threads (account_id, last_at DESC, id);
CREATE INDEX threads_contact ON threads (account_id, contact_fpr);

CREATE TABLE blobs (
    account_id text NOT NULL,
    hash text NOT NULL,
    size bigint NOT NULL,
    mime text DEFAULT 'application/octet-stream'::text NOT NULL,
    filename text DEFAULT ''::text NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT blobs_pkey PRIMARY KEY (account_id, hash),
    CONSTRAINT blobs_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX blobs_account_created ON blobs (account_id, created_at);
-- CountBlobRefs counts a hash ACROSS accounts (the media store is content-addressed), and the
-- primary key leads with the account.
CREATE INDEX blobs_hash ON blobs (hash);

CREATE TABLE integrations (
    id text NOT NULL,
    account_id text NOT NULL,
    slug text NOT NULL,
    transport text NOT NULL,
    endpoint text DEFAULT ''::text NOT NULL,
    command text DEFAULT ''::text NOT NULL,
    auth_kind text DEFAULT 'none'::text NOT NULL,
    status text DEFAULT 'disabled'::text NOT NULL,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    secret bytea,
    CONSTRAINT integrations_pkey PRIMARY KEY (id),
    CONSTRAINT integrations_account_id_slug_key UNIQUE (account_id, slug),
    CONSTRAINT integrations_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE catalogs (
    id text NOT NULL,
    integration_id text NOT NULL,
    version bigint NOT NULL,
    tools text NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT catalogs_pkey PRIMARY KEY (id),
    CONSTRAINT catalogs_integration_id_version_key UNIQUE (integration_id, version),
    CONSTRAINT catalogs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES integrations(id) ON DELETE CASCADE
);

CREATE TABLE exposures (
    id text NOT NULL,
    integration_id text NOT NULL,
    version bigint NOT NULL,
    catalog_version bigint NOT NULL,
    entries text NOT NULL,
    created_at bigint NOT NULL,
    CONSTRAINT exposures_pkey PRIMARY KEY (id),
    CONSTRAINT exposures_integration_id_version_key UNIQUE (integration_id, version),
    CONSTRAINT exposures_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES integrations(id) ON DELETE CASCADE
);

CREATE TABLE idempotency (
    account_id text NOT NULL,
    contact_fpr text NOT NULL,
    msg_id text NOT NULL,
    ack text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint,
    CONSTRAINT idempotency_pkey PRIMARY KEY (account_id, contact_fpr, msg_id)
);
-- The hourly sweep removes spent rows and finds them here: dated ones by their expiry
-- (DeleteExpiredIdempotency), undated ones by their age (DeleteUndatedIdempotencyBefore).
CREATE INDEX idempotency_expiry ON idempotency (expires_at, created_at);

CREATE TABLE pending_requests (
    id text NOT NULL,
    account_id text NOT NULL,
    contact_fpr text NOT NULL,
    capability text NOT NULL,
    args text NOT NULL,
    trust_flag text DEFAULT 'messages_only'::text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    result text DEFAULT ''::text NOT NULL,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    answered_at bigint,
    CONSTRAINT pending_requests_pkey PRIMARY KEY (id),
    CONSTRAINT pending_requests_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX pending_account_status ON pending_requests (account_id, status);

CREATE TABLE move_fanout (
    account_id text NOT NULL,
    contact_fpr text NOT NULL,
    leaf_kid text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    attempts bigint DEFAULT 0 NOT NULL,
    last_error text DEFAULT ''::text NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT move_fanout_pkey PRIMARY KEY (account_id, contact_fpr),
    CONSTRAINT move_fanout_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE settings (
    key text NOT NULL,
    value text NOT NULL,
    secret boolean DEFAULT false NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT settings_pkey PRIMARY KEY (key)
);

CREATE TABLE audit_anchor (
    id integer NOT NULL,
    archived_through_seq bigint NOT NULL,
    terminal_hash text NOT NULL,
    archive_path text NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT audit_anchor_id_check CHECK ((id = 1)),
    CONSTRAINT audit_anchor_pkey PRIMARY KEY (id)
);

CREATE TABLE leaves (
    account_id text NOT NULL,
    kid text NOT NULL,
    leaf bytea,
    key_sealed bytea,
    not_before bigint DEFAULT 0 NOT NULL,
    not_after bigint DEFAULT 0 NOT NULL,
    state text NOT NULL,
    endpoint text NOT NULL,
    created_at bigint NOT NULL,
    request_state_hash bytea,
    wallet_origin text DEFAULT ''::text NOT NULL,
    moved bigint DEFAULT 0 NOT NULL,
    answered_state_hash bytea,
    CONSTRAINT leaves_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'current'::text, 'superseded'::text, 'former'::text]))),
    CONSTRAINT leaves_pkey PRIMARY KEY (account_id, kid),
    CONSTRAINT leaves_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
-- One pending signing request per identity (HDTP sec. 9.1): a new request replaces the last, and
-- a second pending row is impossible.
CREATE UNIQUE INDEX leaves_one_pending ON leaves (account_id) WHERE (state = 'pending'::text);

CREATE TABLE tombstones (
    account_id text NOT NULL,
    root text NOT NULL,
    leaf bytea NOT NULL,
    at bigint NOT NULL,
    CONSTRAINT tombstones_pkey PRIMARY KEY (account_id, root),
    CONSTRAINT tombstones_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE former_endpoints (
    account_id text NOT NULL,
    root text NOT NULL,
    endpoint text NOT NULL,
    at bigint NOT NULL,
    CONSTRAINT former_endpoints_pkey PRIMARY KEY (account_id, root, endpoint, at),
    CONSTRAINT former_endpoints_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE pending_addresses (
    account_id text NOT NULL,
    root text NOT NULL,
    endpoint text NOT NULL,
    leaf bytea NOT NULL,
    why text NOT NULL,
    at bigint NOT NULL,
    root_cert bytea,
    CONSTRAINT pending_addresses_pkey PRIMARY KEY (account_id, root),
    CONSTRAINT pending_addresses_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE messages (
    seq bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    id text NOT NULL,
    account_id text NOT NULL,
    contact_fpr text NOT NULL,
    msg_id text NOT NULL,
    thread_id text NOT NULL,
    direction text NOT NULL,
    sender text NOT NULL,
    body text NOT NULL,
    reply_to text DEFAULT ''::text NOT NULL,
    status text NOT NULL,
    created_at bigint NOT NULL,
    kind text DEFAULT 'text'::text NOT NULL,
    expires_at bigint DEFAULT 0 NOT NULL,
    attempts bigint DEFAULT 0 NOT NULL,
    next_attempt_at bigint DEFAULT 0 NOT NULL,
    CONSTRAINT messages_direction_check CHECK ((direction = ANY (ARRAY['in'::text, 'out'::text]))),
    CONSTRAINT messages_kind_check CHECK ((kind = ANY (ARRAY['text'::text, 'media'::text]))),
    CONSTRAINT messages_sender_check CHECK ((sender = ANY (ARRAY['agent'::text, 'human'::text]))),
    CONSTRAINT messages_status_check CHECK ((status = ANY (ARRAY['delivered'::text, 'queued_for_human'::text, 'pending'::text, 'failed'::text]))),
    CONSTRAINT messages_pkey PRIMARY KEY (seq),
    CONSTRAINT messages_account_id_contact_fpr_direction_msg_id_key UNIQUE (account_id, contact_fpr, direction, msg_id),
    CONSTRAINT messages_id_key UNIQUE (id),
    CONSTRAINT messages_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
-- Retention (DeleteMessagesBefore) asks for an account's messages older than a cutoff.
CREATE INDEX messages_account_created ON messages (account_id, created_at);
-- Retention learns which media is still referenced from the media messages (ListMediaBodies).
CREATE INDEX messages_media ON messages (account_id, seq) WHERE (kind = 'media'::text);
-- The retry sweep (ListPendingOutbound) runs every tick and wants the few outbound rows still
-- pending, oldest first. A partial index holds exactly those, and a row leaves it the moment it
-- is delivered or fails.
CREATE INDEX messages_pending_out ON messages (seq) WHERE ((direction = 'out'::text) AND (status = 'pending'::text));
CREATE INDEX messages_thread ON messages (account_id, thread_id, seq);

CREATE TABLE vacated_addresses (
    endpoint text NOT NULL,
    slug text NOT NULL,
    until_at bigint NOT NULL,
    at bigint NOT NULL,
    CONSTRAINT vacated_addresses_pkey PRIMARY KEY (endpoint)
);
CREATE INDEX vacated_addresses_slug ON vacated_addresses (slug, until_at);

CREATE TABLE audit_archive_rows (
    seq bigint NOT NULL,
    hash text NOT NULL,
    CONSTRAINT audit_archive_rows_pkey PRIMARY KEY (seq)
);

CREATE TABLE changes (
    id bigserial NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    thread_id text DEFAULT ''::text NOT NULL,
    contact_fpr text DEFAULT ''::text NOT NULL,
    ref text DEFAULT ''::text NOT NULL,
    at bigint NOT NULL,
    CONSTRAINT changes_pkey PRIMARY KEY (id)
);
-- wait_for_updates reads one account's changes after its cursor.
CREATE INDEX changes_account ON changes (account_id, id);
CREATE INDEX changes_at ON changes (at);

CREATE TABLE owner_presence (
    id integer NOT NULL,
    seen_at bigint NOT NULL,
    CONSTRAINT owner_presence_id_check CHECK ((id = 1)),
    CONSTRAINT owner_presence_pkey PRIMARY KEY (id)
);

CREATE TABLE leases (
    name text NOT NULL,
    holder text NOT NULL,
    taken_at bigint NOT NULL,
    expires_at bigint NOT NULL,
    CONSTRAINT leases_pkey PRIMARY KEY (name)
);

-- +goose Down
DROP TABLE leases;
DROP TABLE owner_presence;
DROP TABLE changes;
DROP TABLE audit_archive_rows;
DROP TABLE vacated_addresses;
DROP TABLE messages;
DROP TABLE pending_addresses;
DROP TABLE former_endpoints;
DROP TABLE tombstones;
DROP TABLE leaves;
DROP TABLE audit_anchor;
DROP TABLE settings;
DROP TABLE move_fanout;
DROP TABLE pending_requests;
DROP TABLE idempotency;
DROP TABLE exposures;
DROP TABLE catalogs;
DROP TABLE integrations;
DROP TABLE blobs;
DROP TABLE threads;
DROP TABLE invites;
DROP TABLE contacts;
DROP TABLE audit_events;
DROP TABLE memberships;
DROP TABLE accounts;
DROP TABLE tokens;
DROP TABLE sessions;
DROP TABLE credentials;
DROP TABLE owners;
DROP FUNCTION audit_events_immutable();
DROP FUNCTION audit_events_prune_guard();
