-- +goose Up
-- The audit writer supplies seq explicitly (it participates in the chain hash,
-- SPEC §11.4); GENERATED ALWAYS would refuse that.
ALTER TABLE audit_events ALTER COLUMN seq SET GENERATED BY DEFAULT;

-- +goose Down
ALTER TABLE audit_events ALTER COLUMN seq SET GENERATED ALWAYS;
