// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changes.sql

package pgdb

import (
	"context"
)

const accountChangesAfter = `-- name: AccountChangesAfter :many
SELECT id, account_id, kind, thread_id, contact_fpr, ref, at FROM changes WHERE account_id = $1 AND id > $2 ORDER BY id LIMIT $3
`

type AccountChangesAfterParams struct {
	AccountID string
	ID        int64
	Limit     int32
}

func (q *Queries) AccountChangesAfter(ctx context.Context, arg AccountChangesAfterParams) ([]Change, error) {
	rows, err := q.db.Query(ctx, accountChangesAfter, arg.AccountID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.ThreadID,
			&i.ContactFpr,
			&i.Ref,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesAfter = `-- name: ChangesAfter :many
SELECT id, account_id, kind, thread_id, contact_fpr, ref, at FROM changes WHERE id > $1 ORDER BY id LIMIT $2
`

type ChangesAfterParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ChangesAfter(ctx context.Context, arg ChangesAfterParams) ([]Change, error) {
	rows, err := q.db.Query(ctx, changesAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.ThreadID,
			&i.ContactFpr,
			&i.Ref,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChangesBefore = `-- name: DeleteChangesBefore :execrows
DELETE FROM changes WHERE at < $1
`

func (q *Queries) DeleteChangesBefore(ctx context.Context, at int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChangesBefore, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChangesByAccount = `-- name: DeleteChangesByAccount :execrows
DELETE FROM changes WHERE account_id = $1
`

// An identity leaving (HDTP sec. 9): its changes go with it.
func (q *Queries) DeleteChangesByAccount(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChangesByAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChangesByThread = `-- name: DeleteChangesByThread :execrows
DELETE FROM changes WHERE account_id = $1 AND thread_id = $2
`

type DeleteChangesByThreadParams struct {
	AccountID string
	ThreadID  string
}

// A deleted conversation's wake-ups go with it.
func (q *Queries) DeleteChangesByThread(ctx context.Context, arg DeleteChangesByThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChangesByThread, arg.AccountID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (account_id, kind, thread_id, contact_fpr, ref, at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertChangeParams struct {
	AccountID  string
	Kind       string
	ThreadID   string
	ContactFpr string
	Ref        string
	At         int64
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChange,
		arg.AccountID,
		arg.Kind,
		arg.ThreadID,
		arg.ContactFpr,
		arg.Ref,
		arg.At,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastChangeID = `-- name: LastChangeID :one
SELECT COALESCE(MAX(id), 0)::BIGINT AS id FROM changes
`

func (q *Queries) LastChangeID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, lastChangeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listenChanges = `-- name: ListenChanges :exec
LISTEN hdtp_changes
`

func (q *Queries) ListenChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, listenChanges)
	return err
}

const lockChanges = `-- name: LockChanges :exec
SELECT pg_advisory_xact_lock(7152101200000012)
`

// Taken before every insert, in its transaction: ids commit in the order they are assigned, so a
// reader past id N never misses a row a slower transaction commits later below it. A key outside
// int4, beside LockAuditChain's.
func (q *Queries) LockChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockChanges)
	return err
}

const notifyChanges = `-- name: NotifyChanges :exec
SELECT pg_notify('hdtp_changes', '')
`

// Sent in the inserting transaction, so it is delivered at commit: a wake for the processes
// that LISTEN (ListenChanges). Polling finds the row whether or not the wake arrives.
func (q *Queries) NotifyChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyChanges)
	return err
}

const oldestChangeID = `-- name: OldestChangeID :one
SELECT COALESCE(MIN(id), 0)::BIGINT AS id FROM changes
`

func (q *Queries) OldestChangeID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, oldestChangeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
