// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package pgdb

import (
	"context"
	"database/sql"
)

const clearContactHandshake = `-- name: ClearContactHandshake :execrows
UPDATE contacts SET handshake_due = 0 WHERE account_id = $1 AND fingerprint = $2
`

type ClearContactHandshakeParams struct {
	AccountID   string
	Fingerprint string
}

// The campaign has told this contact: it is owed nothing more (sec. 9.2).
func (q *Queries) ClearContactHandshake(ctx context.Context, arg ClearContactHandshakeParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearContactHandshake, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countHeldContacts = `-- name: CountHeldContacts :one
SELECT COUNT(*) FROM contacts WHERE account_id = $1 AND status IN ('active', 'pending_out')
`

// The contacts an account holds against its contact cap: active rows and the requests it sent
// (pending_out). pending_in is written by strangers and blocked is a refusal, so neither counts.
func (q *Queries) CountHeldContacts(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHeldContacts, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE account_id = $1 AND fingerprint = $2
`

type DeleteContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContactInStatus = `-- name: DeleteContactInStatus :execrows
DELETE FROM contacts WHERE account_id = $1 AND fingerprint = $2 AND status = $3
`

type DeleteContactInStatusParams struct {
	AccountID   string
	Fingerprint string
	Status      string
}

// Unblock's forget: only while the row is still the blocked row the decision read.
func (q *Queries) DeleteContactInStatus(ctx context.Context, arg DeleteContactInStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContactInStatus, arg.AccountID, arg.Fingerprint, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredPendingContacts = `-- name: DeleteExpiredPendingContacts :many
DELETE FROM contacts
WHERE account_id = $1 AND status IN ('pending_in', 'pending_out') AND requested_at < $2
RETURNING fingerprint, status
`

type DeleteExpiredPendingContactsParams struct {
	AccountID   string
	RequestedAt sql.NullInt64
}

type DeleteExpiredPendingContactsRow struct {
	Fingerprint string
	Status      string
}

// An unanswered request, ours or theirs, expires (SPEC sec. 9.1): the relationship returns to
// none. The status is in the statement, so a request approved between a read and this delete
// is not the one removed. The window runs from requested_at, when the request was made (migration
// 0043), not from when the contact was first known.
func (q *Queries) DeleteExpiredPendingContacts(ctx context.Context, arg DeleteExpiredPendingContactsParams) ([]DeleteExpiredPendingContactsRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredPendingContacts, arg.AccountID, arg.RequestedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteExpiredPendingContactsRow
	for rows.Next() {
		var i DeleteExpiredPendingContactsRow
		if err := rows.Scan(&i.Fingerprint, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContact = `-- name: GetContact :one
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, endpoint, leaf, chain_sent_kid, root_cert, ever_active, handshake_due, requested_at, leaf_fingerprint FROM contacts WHERE account_id = $1 AND fingerprint = $2
`

type GetContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.AccountID, arg.Fingerprint)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Fingerprint,
		&i.Spki,
		&i.Status,
		&i.Preset,
		&i.Permissions,
		&i.TrustFlag,
		&i.DisplayName,
		&i.Card,
		&i.CreatedAt,
		&i.PinnedAt,
		&i.TheirPermissions,
		&i.Petname,
		&i.InviteID,
		&i.Endpoint,
		&i.Leaf,
		&i.ChainSentKid,
		&i.RootCert,
		&i.EverActive,
		&i.HandshakeDue,
		&i.RequestedAt,
		&i.LeafFingerprint,
	)
	return i, err
}

const importContact = `-- name: ImportContact :exec
INSERT INTO contacts (id, account_id, fingerprint, spki, status, preset, permissions, their_permissions, trust_flag, display_name, petname, card, created_at, pinned_at, endpoint, leaf, leaf_fingerprint, root_cert, ever_active, handshake_due, requested_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
`

type ImportContactParams struct {
	ID               string
	AccountID        string
	Fingerprint      string
	Spki             []byte
	Status           string
	Preset           string
	Permissions      string
	TheirPermissions string
	TrustFlag        string
	DisplayName      string
	Petname          string
	Card             string
	CreatedAt        int64
	PinnedAt         sql.NullInt64
	Endpoint         string
	Leaf             []byte
	LeafFingerprint  sql.NullString
	RootCert         []byte
	EverActive       int64
	HandshakeDue     int64
	RequestedAt      sql.NullInt64
}

// A contact arriving in an export (SPEC sec. 3.10): every column an export carries, in one
// statement, and none it does not. invite_id stays empty because invites do not travel, and
// chain_sent_kid stays empty because it records which of THIS host's leaves the contact has
// seen - and this host has not been issued one yet. handshake_due is the time of the import: the
// contact is owed this host's handshake from the first leaf requested after it (sec. 9.2,
// migration 0043). requested_at is created_at for a row the file carries as pending_out.
func (q *Queries) ImportContact(ctx context.Context, arg ImportContactParams) error {
	_, err := q.db.Exec(ctx, importContact,
		arg.ID,
		arg.AccountID,
		arg.Fingerprint,
		arg.Spki,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.TheirPermissions,
		arg.TrustFlag,
		arg.DisplayName,
		arg.Petname,
		arg.Card,
		arg.CreatedAt,
		arg.PinnedAt,
		arg.Endpoint,
		arg.Leaf,
		arg.LeafFingerprint,
		arg.RootCert,
		arg.EverActive,
		arg.HandshakeDue,
		arg.RequestedAt,
	)
	return err
}

const importContactPin = `-- name: ImportContactPin :execrows
UPDATE contacts SET endpoint = $1, leaf = $2, leaf_fingerprint = $3, spki = $4, root_cert = COALESCE($5, root_cert), handshake_due = $6
WHERE account_id = $7 AND fingerprint = $8 AND (leaf IS NULL OR octet_length(leaf) = 0)
`

type ImportContactPinParams struct {
	Endpoint        string
	Leaf            []byte
	LeafFingerprint sql.NullString
	Spki            []byte
	RootCert        []byte
	HandshakeDue    int64
	AccountID       string
	Fingerprint     string
}

// An import merging into an identity this host already holds (SPEC sec. 3.10, PACT sec. 9.2):
// a contact held with no leaf takes the pin a file carries - the endpoint, and the leaf that
// validated there - and is owed this host's handshake, from the time of the import. A contact held WITH a leaf is never
// written: a pin this host validated itself is not replaced by one from a file (sec. 14.5).
func (q *Queries) ImportContactPin(ctx context.Context, arg ImportContactPinParams) (int64, error) {
	result, err := q.db.Exec(ctx, importContactPin,
		arg.Endpoint,
		arg.Leaf,
		arg.LeafFingerprint,
		arg.Spki,
		arg.RootCert,
		arg.HandshakeDue,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertContact = `-- name: InsertContact :exec
INSERT INTO contacts (id, account_id, fingerprint, spki, status, preset, permissions, display_name, card, created_at, pinned_at, invite_id, endpoint, leaf, leaf_fingerprint, chain_sent_kid, root_cert, ever_active, requested_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
`

type InsertContactParams struct {
	ID              string
	AccountID       string
	Fingerprint     string
	Spki            []byte
	Status          string
	Preset          string
	Permissions     string
	DisplayName     string
	Card            string
	CreatedAt       int64
	PinnedAt        sql.NullInt64
	InviteID        string
	Endpoint        string
	Leaf            []byte
	LeafFingerprint sql.NullString
	ChainSentKid    string
	RootCert        []byte
	EverActive      int64
	RequestedAt     sql.NullInt64
}

// requested_at is the row's created_at when it is inserted as a request (pending_in, pending_out)
// and NULL otherwise (migration 0043).
func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.Exec(ctx, insertContact,
		arg.ID,
		arg.AccountID,
		arg.Fingerprint,
		arg.Spki,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.DisplayName,
		arg.Card,
		arg.CreatedAt,
		arg.PinnedAt,
		arg.InviteID,
		arg.Endpoint,
		arg.Leaf,
		arg.LeafFingerprint,
		arg.ChainSentKid,
		arg.RootCert,
		arg.EverActive,
		arg.RequestedAt,
	)
	return err
}

const listContactLeafKeysUnfilled = `-- name: ListContactLeafKeysUnfilled :many
SELECT id, spki FROM contacts WHERE leaf IS NOT NULL AND octet_length(leaf) > 0 AND leaf_fingerprint IS NULL
`

type ListContactLeafKeysUnfilledRow struct {
	ID   string
	Spki []byte
}

// The fill after migration 0046 (Store.Migrate, fillLeafFingerprints): every row that holds a leaf
// and no fingerprint of it, with the key beside the leaf. After the first fill, none.
func (q *Queries) ListContactLeafKeysUnfilled(ctx context.Context) ([]ListContactLeafKeysUnfilledRow, error) {
	rows, err := q.db.Query(ctx, listContactLeafKeysUnfilled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactLeafKeysUnfilledRow
	for rows.Next() {
		var i ListContactLeafKeysUnfilledRow
		if err := rows.Scan(&i.ID, &i.Spki); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, endpoint, leaf, chain_sent_kid, root_cert, ever_active, handshake_due, requested_at, leaf_fingerprint FROM contacts WHERE account_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListContacts(ctx context.Context, accountID string) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Fingerprint,
			&i.Spki,
			&i.Status,
			&i.Preset,
			&i.Permissions,
			&i.TrustFlag,
			&i.DisplayName,
			&i.Card,
			&i.CreatedAt,
			&i.PinnedAt,
			&i.TheirPermissions,
			&i.Petname,
			&i.InviteID,
			&i.Endpoint,
			&i.Leaf,
			&i.ChainSentKid,
			&i.RootCert,
			&i.EverActive,
			&i.HandshakeDue,
			&i.RequestedAt,
			&i.LeafFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContactRequested = `-- name: MarkContactRequested :execrows
UPDATE contacts SET status = 'pending_out', requested_at = $1
WHERE account_id = $2 AND fingerprint = $3 AND status = $4
`

type MarkContactRequestedParams struct {
	RequestedAt sql.NullInt64
	AccountID   string
	Fingerprint string
	Status      string
}

// The handshake after an import falls back to request_contact (PACT sec. 9.2): the contact becomes
// an approach of ours BEFORE the request is sent, so a peer that answers at once finds the
// pending_out its contact_accepted answers. Guarded by the status the campaign read. The request
// clock starts now; ever_active is left as it was.
func (q *Queries) MarkContactRequested(ctx context.Context, arg MarkContactRequestedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markContactRequested,
		arg.RequestedAt,
		arg.AccountID,
		arg.Fingerprint,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveContactStatus = `-- name: MoveContactStatus :execrows
UPDATE contacts SET status = $1,
    ever_active = CASE WHEN $1 = 'active' THEN 1 ELSE ever_active END
WHERE account_id = $2 AND fingerprint = $3 AND status = $4
`

type MoveContactStatusParams struct {
	Status      string
	AccountID   string
	Fingerprint string
	Status_2    string
}

// The owner's decisions (approve, reject, block, unblock): the move happens only from the status
// the decision was taken on, so a row that changed between the read and this write (a redeem over
// a pending request, the expiry sweep) is not overwritten. Zero rows means it changed.
func (q *Queries) MoveContactStatus(ctx context.Context, arg MoveContactStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveContactStatus,
		arg.Status,
		arg.AccountID,
		arg.Fingerprint,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pinCandidates = `-- name: PinCandidates :many
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, endpoint, leaf, chain_sent_kid, root_cert, ever_active, handshake_due, requested_at, leaf_fingerprint FROM contacts WHERE id IN (
    SELECT c.id FROM contacts c WHERE c.account_id = $1 AND c.fingerprint = $2 AND $2 <> ''
    UNION
    SELECT c.id FROM contacts c WHERE c.account_id = $1 AND c.endpoint = $3 AND $3 <> ''
    UNION
    SELECT c.id FROM contacts c WHERE c.account_id = $1 AND c.leaf_fingerprint = $4 AND $4 <> ''
)
ORDER BY created_at, id
`

type PinCandidatesParams struct {
	AccountID       string
	Fingerprint     string
	Endpoint        string
	LeafFingerprint sql.NullString
}

// The contacts a sealed call's proof could concern (PACT sec. 13.3; public/decide.go): the row of
// the root a chain proves, the rows at the address its leaf names (the address claim of sec. 5.2),
// and the row whose pinned leaf a small form names. Three index probes, then the rows they found by
// id, in ListContacts' order,
// so decide meets them as it met them among every contact. An empty argument matches nothing.
func (q *Queries) PinCandidates(ctx context.Context, arg PinCandidatesParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, pinCandidates,
		arg.AccountID,
		arg.Fingerprint,
		arg.Endpoint,
		arg.LeafFingerprint,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Fingerprint,
			&i.Spki,
			&i.Status,
			&i.Preset,
			&i.Permissions,
			&i.TrustFlag,
			&i.DisplayName,
			&i.Card,
			&i.CreatedAt,
			&i.PinnedAt,
			&i.TheirPermissions,
			&i.Petname,
			&i.InviteID,
			&i.Endpoint,
			&i.Leaf,
			&i.ChainSentKid,
			&i.RootCert,
			&i.EverActive,
			&i.HandshakeDue,
			&i.RequestedAt,
			&i.LeafFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemOverPendingContact = `-- name: RedeemOverPendingContact :execrows
UPDATE contacts SET status = $1,
    ever_active = CASE WHEN $1 = 'active' THEN 1 ELSE ever_active END,
    preset = $2, permissions = $3, invite_id = $4,
    display_name = $5, card = $6, spki = $7,
    endpoint = $8, leaf = $9, root_cert = COALESCE($10, root_cert), leaf_fingerprint = $13
WHERE account_id = $11 AND fingerprint = $12 AND status = 'pending_in'
`

type RedeemOverPendingContactParams struct {
	Status          string
	Preset          string
	Permissions     string
	InviteID        string
	DisplayName     string
	Card            string
	Spki            []byte
	Endpoint        string
	Leaf            []byte
	RootCert        []byte
	AccountID       string
	Fingerprint     string
	LeafFingerprint sql.NullString
}

// A request still awaiting the owner (pending_in) redeems one of the owner's invites: the row
// takes the invite's status and grant and the pin this call proved (a sealed call proves no root
// certificate, and then the one held is kept). Guarded by the status it expects, so a row the
// owner decided on meanwhile is not overwritten.
func (q *Queries) RedeemOverPendingContact(ctx context.Context, arg RedeemOverPendingContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, redeemOverPendingContact,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.InviteID,
		arg.DisplayName,
		arg.Card,
		arg.Spki,
		arg.Endpoint,
		arg.Leaf,
		arg.RootCert,
		arg.AccountID,
		arg.Fingerprint,
		arg.LeafFingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContactAccepted = `-- name: SetContactAccepted :execrows
UPDATE contacts SET status = 'active', ever_active = 1, card = $1, their_permissions = $2, pinned_at = $3
WHERE account_id = $4 AND fingerprint = $5
`

type SetContactAcceptedParams struct {
	Card             string
	TheirPermissions string
	PinnedAt         sql.NullInt64
	AccountID        string
	Fingerprint      string
}

func (q *Queries) SetContactAccepted(ctx context.Context, arg SetContactAcceptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContactAccepted,
		arg.Card,
		arg.TheirPermissions,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContactLeafFingerprint = `-- name: SetContactLeafFingerprint :exec
UPDATE contacts SET leaf_fingerprint = $1 WHERE id = $2
`

type SetContactLeafFingerprintParams struct {
	LeafFingerprint sql.NullString
	ID              string
}

// The fill after migration 0046: one row's leaf fingerprint.
func (q *Queries) SetContactLeafFingerprint(ctx context.Context, arg SetContactLeafFingerprintParams) error {
	_, err := q.db.Exec(ctx, setContactLeafFingerprint, arg.LeafFingerprint, arg.ID)
	return err
}

const takeBackContactRequest = `-- name: TakeBackContactRequest :execrows
UPDATE contacts SET status = $1, requested_at = $2
WHERE account_id = $3 AND fingerprint = $4 AND status = 'pending_out' AND requested_at = $5
`

type TakeBackContactRequestParams struct {
	Status        string
	RequestedAt   sql.NullInt64
	AccountID     string
	Fingerprint   string
	RequestedAt_2 sql.NullInt64
}

// A request that did not reach the peer, or that the peer refused, is taken back: the row returns
// to the status and the request clock it had. Only while it is still the approach that was marked.
func (q *Queries) TakeBackContactRequest(ctx context.Context, arg TakeBackContactRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeBackContactRequest,
		arg.Status,
		arg.RequestedAt,
		arg.AccountID,
		arg.Fingerprint,
		arg.RequestedAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactCard = `-- name: UpdateContactCard :execrows
UPDATE contacts SET card = $1, display_name = $2 WHERE account_id = $3 AND fingerprint = $4
`

type UpdateContactCardParams struct {
	Card        string
	DisplayName string
	AccountID   string
	Fingerprint string
}

// The periodic contact sync's write: a re-fetched card whose signature
// verified under the PINNED key. The key itself never moves here - rotation
// is update_contact's job - so only the card text and the display name change.
func (q *Queries) UpdateContactCard(ctx context.Context, arg UpdateContactCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactCard,
		arg.Card,
		arg.DisplayName,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactPermissions = `-- name: UpdateContactPermissions :execrows
UPDATE contacts SET permissions = $1, preset = $2 WHERE account_id = $3 AND fingerprint = $4
`

type UpdateContactPermissionsParams struct {
	Permissions string
	Preset      string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactPermissions(ctx context.Context, arg UpdateContactPermissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactPermissions,
		arg.Permissions,
		arg.Preset,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactPetname = `-- name: UpdateContactPetname :execrows
UPDATE contacts SET petname = $1 WHERE account_id = $2 AND fingerprint = $3
`

type UpdateContactPetnameParams struct {
	Petname     string
	AccountID   string
	Fingerprint string
}

// The owner's own name for a contact. Local by construction: no peer surface
// reaches it, which is the point - display_name is the contact's own claim.
func (q *Queries) UpdateContactPetname(ctx context.Context, arg UpdateContactPetnameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactPetname, arg.Petname, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactStatus = `-- name: UpdateContactStatus :execrows
UPDATE contacts SET status = $1,
    ever_active = CASE WHEN $1 = 'active' THEN 1 ELSE ever_active END
WHERE account_id = $2 AND fingerprint = $3
`

type UpdateContactStatusParams struct {
	Status      string
	AccountID   string
	Fingerprint string
}

// Moving a row to active records that it was ever active (migration 0039); nothing clears it.
func (q *Queries) UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactStatus, arg.Status, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactTrust = `-- name: UpdateContactTrust :execrows
UPDATE contacts SET trust_flag = $1 WHERE account_id = $2 AND fingerprint = $3
`

type UpdateContactTrustParams struct {
	TrustFlag   string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactTrust(ctx context.Context, arg UpdateContactTrustParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactTrust, arg.TrustFlag, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
