// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE account_id = $1 AND fingerprint = $2
`

type DeleteContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContact = `-- name: GetContact :one
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id FROM contacts WHERE account_id = $1 AND fingerprint = $2
`

type GetContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.AccountID, arg.Fingerprint)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Fingerprint,
		&i.Spki,
		&i.Status,
		&i.Preset,
		&i.Permissions,
		&i.TrustFlag,
		&i.DisplayName,
		&i.Card,
		&i.CreatedAt,
		&i.PinnedAt,
		&i.TheirPermissions,
		&i.Petname,
		&i.InviteID,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :exec
INSERT INTO contacts (id, account_id, fingerprint, spki, status, preset, permissions, display_name, card, created_at, pinned_at, invite_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertContactParams struct {
	ID          string
	AccountID   string
	Fingerprint string
	Spki        []byte
	Status      string
	Preset      string
	Permissions string
	DisplayName string
	Card        string
	CreatedAt   int64
	PinnedAt    pgtype.Int8
	InviteID    string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.Exec(ctx, insertContact,
		arg.ID,
		arg.AccountID,
		arg.Fingerprint,
		arg.Spki,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.DisplayName,
		arg.Card,
		arg.CreatedAt,
		arg.PinnedAt,
		arg.InviteID,
	)
	return err
}

const listContacts = `-- name: ListContacts :many
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id FROM contacts WHERE account_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListContacts(ctx context.Context, accountID string) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Fingerprint,
			&i.Spki,
			&i.Status,
			&i.Preset,
			&i.Permissions,
			&i.TrustFlag,
			&i.DisplayName,
			&i.Card,
			&i.CreatedAt,
			&i.PinnedAt,
			&i.TheirPermissions,
			&i.Petname,
			&i.InviteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactPermissions = `-- name: UpdateContactPermissions :execrows
UPDATE contacts SET permissions = $1, preset = $2 WHERE account_id = $3 AND fingerprint = $4
`

type UpdateContactPermissionsParams struct {
	Permissions string
	Preset      string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactPermissions(ctx context.Context, arg UpdateContactPermissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactPermissions,
		arg.Permissions,
		arg.Preset,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactStatus = `-- name: UpdateContactStatus :execrows
UPDATE contacts SET status = $1 WHERE account_id = $2 AND fingerprint = $3
`

type UpdateContactStatusParams struct {
	Status      string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactStatus, arg.Status, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactTrust = `-- name: UpdateContactTrust :execrows
UPDATE contacts SET trust_flag = $1 WHERE account_id = $2 AND fingerprint = $3
`

type UpdateContactTrustParams struct {
	TrustFlag   string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactTrust(ctx context.Context, arg UpdateContactTrustParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactTrust, arg.TrustFlag, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContactAccepted = `-- name: SetContactAccepted :execrows
UPDATE contacts SET status = 'active', card = $1, their_permissions = $2, pinned_at = $3
WHERE account_id = $4 AND fingerprint = $5
`

type SetContactAcceptedParams struct {
	Card             string
	TheirPermissions string
	PinnedAt         int64
	AccountID        string
	Fingerprint      string
}

func (q *Queries) SetContactAccepted(ctx context.Context, arg SetContactAcceptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContactAccepted,
		arg.Card, arg.TheirPermissions, arg.PinnedAt, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactCard = `-- name: UpdateContactCard :execrows
UPDATE contacts SET card = $1, display_name = $2 WHERE account_id = $3 AND fingerprint = $4
`

type UpdateContactCardParams struct {
	Card        string
	DisplayName string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactCard(ctx context.Context, arg UpdateContactCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactCard, arg.Card, arg.DisplayName, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateContactPetname = `-- name: UpdateContactPetname :execrows
UPDATE contacts SET petname = $1 WHERE account_id = $2 AND fingerprint = $3
`

type UpdateContactPetnameParams struct {
	Petname     string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactPetname(ctx context.Context, arg UpdateContactPetnameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContactPetname, arg.Petname, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
