// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAccountPrevKey = `-- name: ClearAccountPrevKey :execrows
UPDATE accounts SET prev_fingerprint = NULL, prev_key_sealed = NULL, grace_until = 0 WHERE id = $1
`

func (q *Queries) ClearAccountPrevKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, clearAccountPrevKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCredentialsByKind = `-- name: CountCredentialsByKind :one
SELECT COUNT(*) FROM credentials WHERE kind = $1
`

func (q *Queries) CountCredentialsByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentialsByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type DeleteCredentialParams struct {
	ID   string
	Kind string
}

const deleteCredentialIfNotLast = `-- name: DeleteCredentialIfNotLast :execrows
WITH held AS (
  SELECT id FROM credentials WHERE kind = $2 ORDER BY id FOR UPDATE
)
DELETE FROM credentials WHERE id = $1 AND kind = $2
  AND (SELECT COUNT(*) FROM held) > 1
`

// DeleteCredentialIfNotLast removes a credential only while another of the same
// kind survives.
//
// One statement is NOT sufficient on Postgres. A bare `(SELECT COUNT(*) …)` is an
// uncorrelated sub-plan evaluated once against the statement's snapshot, so under
// READ COMMITTED two concurrent removals of the last two passkeys each see "there
// are two", each delete a different row, and the node is left with NONE — locking
// the owner out of the portal and re-opening the setup wizard to whoever reaches
// it first. The `FOR UPDATE` CTE takes row locks on that kind first, so the second
// statement blocks, re-reads, and finds one.
func (q *Queries) DeleteCredentialIfNotLast(ctx context.Context, arg DeleteCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredentialIfNotLast, arg.ID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships WHERE owner_id = $1 AND account_id = $2
`

type DeleteMembershipParams struct {
	OwnerID   string
	AccountID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.OwnerID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOwner = `-- name: DeleteOwner :execrows
DELETE FROM owners WHERE id = $1
`

func (q *Queries) DeleteOwner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, slug, display_name, algo, fingerprint, key_sealed, seal, status, created_at, prev_fingerprint, prev_key_sealed, grace_until, protocol, root_fingerprint, root_cert, accept_new_hosts, accept_1x FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Algo,
		&i.Fingerprint,
		&i.KeySealed,
		&i.Seal,
		&i.Status,
		&i.CreatedAt,
		&i.PrevFingerprint,
		&i.PrevKeySealed,
		&i.GraceUntil,
		&i.Protocol,
		&i.RootFingerprint,
		&i.RootCert,
		&i.AcceptNewHosts,
		&i.Accept1x,
	)
	return i, err
}

const getAccountBySlug = `-- name: GetAccountBySlug :one
SELECT id, slug, display_name, algo, fingerprint, key_sealed, seal, status, created_at, prev_fingerprint, prev_key_sealed, grace_until, protocol, root_fingerprint, root_cert, accept_new_hosts, accept_1x FROM accounts WHERE slug = $1
`

func (q *Queries) GetAccountBySlug(ctx context.Context, slug string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountBySlug, slug)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Algo,
		&i.Fingerprint,
		&i.KeySealed,
		&i.Seal,
		&i.Status,
		&i.CreatedAt,
		&i.PrevFingerprint,
		&i.PrevKeySealed,
		&i.GraceUntil,
		&i.Protocol,
		&i.RootFingerprint,
		&i.RootCert,
		&i.AcceptNewHosts,
		&i.Accept1x,
	)
	return i, err
}

const getAccountPrevKey = `-- name: GetAccountPrevKey :one
SELECT prev_fingerprint, prev_key_sealed, grace_until FROM accounts WHERE id = $1
`

type GetAccountPrevKeyRow struct {
	PrevFingerprint pgtype.Text
	PrevKeySealed   []byte
	GraceUntil      int64
}

func (q *Queries) GetAccountPrevKey(ctx context.Context, id string) (GetAccountPrevKeyRow, error) {
	row := q.db.QueryRow(ctx, getAccountPrevKey, id)
	var i GetAccountPrevKeyRow
	err := row.Scan(&i.PrevFingerprint, &i.PrevKeySealed, &i.GraceUntil)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT id, display_name, created_at FROM owners WHERE id = $1
`

func (q *Queries) GetOwner(ctx context.Context, id string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwner, id)
	var i Owner
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, owner_id, created_at, expires_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, owner_id, label, hash, account_id, created_at, revoked_at FROM tokens WHERE hash = $1
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash []byte) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Label,
		&i.Hash,
		&i.AccountID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, slug, display_name, algo, created_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertAccountParams struct {
	ID          string
	Slug        string
	DisplayName string
	Algo        string
	CreatedAt   int64
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Algo,
		arg.CreatedAt,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (seq, ts, account_id, actor_kind, actor_id, action, resource, outcome, request_id, details, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertAuditEventParams struct {
	Seq       int64
	Ts        int64
	AccountID pgtype.Text
	ActorKind string
	ActorID   string
	Action    string
	Resource  string
	Outcome   string
	RequestID string
	Details   string
	PrevHash  string
	Hash      string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.Seq,
		arg.Ts,
		arg.AccountID,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.Outcome,
		arg.RequestID,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (id, owner_id, kind, tag, data, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCredentialParams struct {
	ID        string
	OwnerID   string
	Kind      string
	Tag       string
	Data      []byte
	CreatedAt int64
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.OwnerID,
		arg.Kind,
		arg.Tag,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO memberships (owner_id, account_id, role) VALUES ($1, $2, $3)
`

type InsertMembershipParams struct {
	OwnerID   string
	AccountID string
	Role      string
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership, arg.OwnerID, arg.AccountID, arg.Role)
	return err
}

const insertOwner = `-- name: InsertOwner :exec
INSERT INTO owners (id, display_name, created_at) VALUES ($1, $2, $3)
`

type InsertOwnerParams struct {
	ID          string
	DisplayName string
	CreatedAt   int64
}

func (q *Queries) InsertOwner(ctx context.Context, arg InsertOwnerParams) error {
	_, err := q.db.Exec(ctx, insertOwner, arg.ID, arg.DisplayName, arg.CreatedAt)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, owner_id, created_at, expires_at) VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	ID        string
	OwnerID   string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.OwnerID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO tokens (id, owner_id, label, hash, account_id, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTokenParams struct {
	ID        string
	OwnerID   string
	Label     string
	Hash      []byte
	AccountID pgtype.Text
	CreatedAt int64
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.Exec(ctx, insertToken,
		arg.ID,
		arg.OwnerID,
		arg.Label,
		arg.Hash,
		arg.AccountID,
		arg.CreatedAt,
	)
	return err
}

const lastAuditEvent = `-- name: LastAuditEvent :one
SELECT seq, ts, account_id, actor_kind, actor_id, action, resource, outcome, request_id, details, prev_hash, hash FROM audit_events ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LastAuditEvent(ctx context.Context) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, lastAuditEvent)
	var i AuditEvent
	err := row.Scan(
		&i.Seq,
		&i.Ts,
		&i.AccountID,
		&i.ActorKind,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.Outcome,
		&i.RequestID,
		&i.Details,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, slug, display_name, algo, fingerprint, key_sealed, seal, status, created_at, prev_fingerprint, prev_key_sealed, grace_until, protocol, root_fingerprint, root_cert, accept_new_hosts, accept_1x FROM accounts ORDER BY created_at, id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Algo,
			&i.Fingerprint,
			&i.KeySealed,
			&i.Seal,
			&i.Status,
			&i.CreatedAt,
			&i.PrevFingerprint,
			&i.PrevKeySealed,
			&i.GraceUntil,
			&i.Protocol,
			&i.RootFingerprint,
			&i.RootCert,
			&i.AcceptNewHosts,
			&i.Accept1x,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT seq, ts, account_id, actor_kind, actor_id, action, resource, outcome, request_id, details, prev_hash, hash FROM audit_events ORDER BY seq
`

func (q *Queries) ListAuditEvents(ctx context.Context) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.AccountID,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RequestID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT seq, ts, account_id, actor_kind, actor_id, "action", resource, outcome, request_id, details, prev_hash, hash FROM audit_events
WHERE ($1 = '' OR actor_id = $1)
  AND ($2 = '' OR account_id = $2 OR account_id IS NULL OR account_id = '')
ORDER BY seq DESC LIMIT $3
`

type ListAuditEventsPageParams struct {
	ActorID   string
	AccountID string
	Limit     int64
}

func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsPage, arg.ActorID, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq, &i.Ts, &i.AccountID, &i.ActorKind, &i.ActorID, &i.Action,
			&i.Resource, &i.Outcome, &i.RequestID, &i.Details, &i.PrevHash, &i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByActor = `-- name: ListAuditEventsByActor :many
SELECT seq, ts, account_id, actor_kind, actor_id, action, resource, outcome, request_id, details, prev_hash, hash FROM audit_events WHERE actor_id = $1 ORDER BY seq
`

func (q *Queries) ListAuditEventsByActor(ctx context.Context, actorID string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.AccountID,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RequestID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByKind = `-- name: ListCredentialsByKind :many
SELECT id, owner_id, kind, tag, data, created_at, last_used_at FROM credentials WHERE kind = $1 ORDER BY created_at, id
`

func (q *Queries) ListCredentialsByKind(ctx context.Context, kind string) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Tag,
			&i.Data,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByOwner = `-- name: ListMembershipsByOwner :many
SELECT owner_id, account_id, role FROM memberships WHERE owner_id = $1 ORDER BY account_id
`

func (q *Queries) ListMembershipsByOwner(ctx context.Context, ownerID string) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(&i.OwnerID, &i.AccountID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwners = `-- name: ListOwners :many
SELECT id, display_name, created_at FROM owners ORDER BY created_at, id
`

func (q *Queries) ListOwners(ctx context.Context) ([]Owner, error) {
	rows, err := q.db.Query(ctx, listOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Owner
	for rows.Next() {
		var i Owner
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRotationFanout = `-- name: ListRotationFanout :many
SELECT account_id, contact_fpr, new_fpr, status, attempts, last_error, updated_at, kind FROM rotation_fanout WHERE account_id = $1 ORDER BY contact_fpr
`

func (q *Queries) ListRotationFanout(ctx context.Context, accountID string) ([]RotationFanout, error) {
	rows, err := q.db.Query(ctx, listRotationFanout, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RotationFanout
	for rows.Next() {
		var i RotationFanout
		if err := rows.Scan(
			&i.AccountID,
			&i.ContactFpr,
			&i.NewFpr,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.UpdatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, owner_id, label, hash, account_id, created_at, revoked_at FROM tokens ORDER BY created_at, id
`

func (q *Queries) ListTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Label,
			&i.Hash,
			&i.AccountID,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE tokens SET revoked_at = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt pgtype.Int8
	ID        string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAccountKey = `-- name: RotateAccountKey :execrows
UPDATE accounts SET prev_fingerprint = fingerprint, prev_key_sealed = key_sealed,
  fingerprint = $1, key_sealed = $2, grace_until = $3
WHERE id = $4 AND fingerprint IS NOT NULL
`

type RotateAccountKeyParams struct {
	Fingerprint pgtype.Text
	KeySealed   []byte
	GraceUntil  int64
	ID          string
}

func (q *Queries) RotateAccountKey(ctx context.Context, arg RotateAccountKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateAccountKey,
		arg.Fingerprint,
		arg.KeySealed,
		arg.GraceUntil,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountKey = `-- name: SetAccountKey :execrows
UPDATE accounts SET fingerprint = $1, key_sealed = $2 WHERE id = $3 AND fingerprint IS NULL
`

type SetAccountKeyParams struct {
	Fingerprint pgtype.Text
	KeySealed   []byte
	ID          string
}

func (q *Queries) SetAccountKey(ctx context.Context, arg SetAccountKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountKey, arg.Fingerprint, arg.KeySealed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountSeal = `-- name: UpdateAccountSeal :execrows
UPDATE accounts SET seal = $1 WHERE id = $2
`

type UpdateAccountSealParams struct {
	Seal string
	ID   string
}

func (q *Queries) UpdateAccountSeal(ctx context.Context, arg UpdateAccountSealParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountSeal, arg.Seal, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRotationFanout = `-- name: UpsertRotationFanout :exec
INSERT INTO rotation_fanout (account_id, contact_fpr, new_fpr, status, attempts, last_error, updated_at, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (account_id, contact_fpr) DO UPDATE SET
  new_fpr = EXCLUDED.new_fpr, status = EXCLUDED.status, attempts = EXCLUDED.attempts,
  last_error = EXCLUDED.last_error, updated_at = EXCLUDED.updated_at, kind = EXCLUDED.kind
`

type UpsertRotationFanoutParams struct {
	AccountID  string
	ContactFpr string
	NewFpr     string
	Status     string
	Attempts   int64
	LastError  string
	UpdatedAt  int64
	Kind       string
}

func (q *Queries) UpsertRotationFanout(ctx context.Context, arg UpsertRotationFanoutParams) error {
	_, err := q.db.Exec(ctx, upsertRotationFanout,
		arg.AccountID,
		arg.ContactFpr,
		arg.NewFpr,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.UpdatedAt,
		arg.Kind,
	)
	return err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, secret, updated_at FROM settings ORDER BY key
`

type Setting struct {
	Key       string
	Value     string
	Secret    bool
	UpdatedAt int64
}

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.Secret, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value, secret, updated_at) VALUES ($1, $2, $3, $4)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, secret = excluded.secret, updated_at = excluded.updated_at
`

type PutSettingParams struct {
	Key       string
	Value     string
	Secret    bool
	UpdatedAt int64
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value, arg.Secret, arg.UpdatedAt)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getAuditAnchor = `-- name: GetAuditAnchor :one
SELECT id, archived_through_seq, terminal_hash, archive_path, updated_at FROM audit_anchor WHERE id = 1
`

type AuditAnchor struct {
	ID                 int64
	ArchivedThroughSeq int64
	TerminalHash       string
	ArchivePath        string
	UpdatedAt          int64
}

func (q *Queries) GetAuditAnchor(ctx context.Context) (AuditAnchor, error) {
	row := q.db.QueryRow(ctx, getAuditAnchor)
	var i AuditAnchor
	err := row.Scan(&i.ID, &i.ArchivedThroughSeq, &i.TerminalHash, &i.ArchivePath, &i.UpdatedAt)
	return i, err
}

const setAuditAnchor = `-- name: SetAuditAnchor :exec
INSERT INTO audit_anchor (id, archived_through_seq, terminal_hash, archive_path, updated_at)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT(id) DO UPDATE SET archived_through_seq = excluded.archived_through_seq,
    terminal_hash = excluded.terminal_hash, archive_path = excluded.archive_path,
    updated_at = excluded.updated_at
`

type SetAuditAnchorParams struct {
	ArchivedThroughSeq int64
	TerminalHash       string
	ArchivePath        string
	UpdatedAt          int64
}

func (q *Queries) SetAuditAnchor(ctx context.Context, arg SetAuditAnchorParams) error {
	_, err := q.db.Exec(ctx, setAuditAnchor, arg.ArchivedThroughSeq, arg.TerminalHash, arg.ArchivePath, arg.UpdatedAt)
	return err
}

const deleteAuditEventsThrough = `-- name: DeleteAuditEventsThrough :execrows
DELETE FROM audit_events WHERE seq <= $1
`

func (q *Queries) DeleteAuditEventsThrough(ctx context.Context, seq int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditEventsThrough, seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
