// Package pgdb is the SQL the Postgres store runs, as Go over pgx/v5: one method on Queries for
// each statement in queries/postgres/*.sql, with the parameter and row types sqlc derived from the
// schema in migrations/postgres. Where sqlc.yaml's overrides apply, a row has the same Go shape as
// its sqlitedb twin, so internal/core/store converts it to a sqlitedb type and maps it once for both
// engines.
//
// Every .go file in this directory except this one is generated by sqlc (make sqlc, pinned to the version
// the Makefile names) and is not edited by hand; make sqlc-check fails when the committed files differ
// from what the sources produce. This file is the only hand-written .go file, and it holds only this
// comment. The package is imported by internal/core/store alone (README.md in this directory says
// more).
package pgdb
