// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_state.sql

package pgdb

import (
	"context"
	"database/sql"
)

const clearAccountKey = `-- name: ClearAccountKey :execrows
UPDATE accounts SET key_sealed = NULL WHERE id = $1
`

// The account's copy of its CURRENT leaf's key, destroyed when that leaf expires. The leaf ledger
// row is retired by RetireLeafKey; this is the other place the same key is held. The fingerprint
// stays: it is how every pin, route and audit row names this account, and it names a key the
// account no longer has - which is exactly what "awaiting a leaf" means.
func (q *Queries) ClearAccountKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, clearAccountKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearChainSentKids = `-- name: ClearChainSentKids :execrows
UPDATE contacts SET chain_sent_kid = '' WHERE account_id = $1
`

// After a leaf install every contact must see the new chain once (HDTP sec. 13.2).
func (q *Queries) ClearChainSentKids(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, clearChainSentKids, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeLeafRequest = `-- name: ConsumeLeafRequest :execrows
UPDATE leaves SET answered_state_hash = request_state_hash, request_state_hash = NULL
WHERE account_id = $1 AND kid = $2 AND state = 'pending' AND request_state_hash = $3
`

type ConsumeLeafRequestParams struct {
	AccountID        string
	Kid              string
	RequestStateHash []byte
}

// An answer is accepted once: the check and the consumption are one statement, so two answers
// carrying the same state cannot both see it. The consumed hash moves to answered_state_hash
// (migration 0051; SET reads the row as it was), so an answer that arrives again can be told apart.
func (q *Queries) ConsumeLeafRequest(ctx context.Context, arg ConsumeLeafRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeLeafRequest, arg.AccountID, arg.Kid, arg.RequestStateHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveVacatedEndpoint = `-- name: CountLiveVacatedEndpoint :one
SELECT COUNT(*) FROM vacated_addresses WHERE endpoint = $1 AND until_at > $2
`

type CountLiveVacatedEndpointParams struct {
	Endpoint string
	UntilAt  int64
}

func (q *Queries) CountLiveVacatedEndpoint(ctx context.Context, arg CountLiveVacatedEndpointParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveVacatedEndpoint, arg.Endpoint, arg.UntilAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveVacatedSlug = `-- name: CountLiveVacatedSlug :one
SELECT COUNT(*) FROM vacated_addresses WHERE slug = $1 AND until_at > $2
`

type CountLiveVacatedSlugParams struct {
	Slug    string
	UntilAt int64
}

func (q *Queries) CountLiveVacatedSlug(ctx context.Context, arg CountLiveVacatedSlugParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveVacatedSlug, arg.Slug, arg.UntilAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredVacatedAddresses = `-- name: DeleteExpiredVacatedAddresses :execrows
DELETE FROM vacated_addresses WHERE until_at <= $1
`

func (q *Queries) DeleteExpiredVacatedAddresses(ctx context.Context, untilAt int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredVacatedAddresses, untilAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLeavesByState = `-- name: DeleteLeavesByState :execrows
DELETE FROM leaves WHERE account_id = $1 AND state = $2
`

type DeleteLeavesByStateParams struct {
	AccountID string
	State     string
}

func (q *Queries) DeleteLeavesByState(ctx context.Context, arg DeleteLeavesByStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLeavesByState, arg.AccountID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingAddress = `-- name: DeletePendingAddress :execrows
DELETE FROM pending_addresses WHERE account_id = $1 AND root = $2
`

type DeletePendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeletePendingAddress(ctx context.Context, arg DeletePendingAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingAddress, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTombstone = `-- name: DeleteTombstone :execrows
DELETE FROM tombstones WHERE account_id = $1 AND root = $2
`

type DeleteTombstoneParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeleteTombstone(ctx context.Context, arg DeleteTombstoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTombstone, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingAddress = `-- name: GetPendingAddress :one
SELECT account_id, root, endpoint, leaf, why, at, root_cert FROM pending_addresses WHERE account_id = $1 AND root = $2
`

type GetPendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) GetPendingAddress(ctx context.Context, arg GetPendingAddressParams) (PendingAddress, error) {
	row := q.db.QueryRow(ctx, getPendingAddress, arg.AccountID, arg.Root)
	var i PendingAddress
	err := row.Scan(
		&i.AccountID,
		&i.Root,
		&i.Endpoint,
		&i.Leaf,
		&i.Why,
		&i.At,
		&i.RootCert,
	)
	return i, err
}

const insertFormerEndpoint = `-- name: InsertFormerEndpoint :exec
INSERT INTO former_endpoints (account_id, root, endpoint, at) VALUES ($1, $2, $3, $4)
`

type InsertFormerEndpointParams struct {
	AccountID string
	Root      string
	Endpoint  string
	At        int64
}

func (q *Queries) InsertFormerEndpoint(ctx context.Context, arg InsertFormerEndpointParams) error {
	_, err := q.db.Exec(ctx, insertFormerEndpoint,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.At,
	)
	return err
}

const insertLeaf = `-- name: InsertLeaf :exec
INSERT INTO leaves (account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertLeafParams struct {
	AccountID string
	Kid       string
	Leaf      []byte
	KeySealed []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	CreatedAt int64
}

func (q *Queries) InsertLeaf(ctx context.Context, arg InsertLeafParams) error {
	_, err := q.db.Exec(ctx, insertLeaf,
		arg.AccountID,
		arg.Kid,
		arg.Leaf,
		arg.KeySealed,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.CreatedAt,
	)
	return err
}

const listFormerEndpoints = `-- name: ListFormerEndpoints :many
SELECT account_id, root, endpoint, at FROM former_endpoints WHERE account_id = $1 ORDER BY at, root, endpoint
`

func (q *Queries) ListFormerEndpoints(ctx context.Context, accountID string) ([]FormerEndpoint, error) {
	rows, err := q.db.Query(ctx, listFormerEndpoints, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormerEndpoint
	for rows.Next() {
		var i FormerEndpoint
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKidsExcept = `-- name: ListKidsExcept :many
SELECT account_id, kid FROM leaves WHERE account_id != $1 ORDER BY account_id, kid
`

type ListKidsExceptRow struct {
	AccountID string
	Kid       string
}

// Every leaf kid on this node that does NOT belong to one account. RecipientState asks
// this once per inbound envelope, to tell a kid held for a SIBLING identity from
// one this endpoint never held (HDTP sec. 13.3, sec. 14.4). It used to be one
// query per other account, so the cost of every message grew with the number of
// identities the node hosts.
func (q *Queries) ListKidsExcept(ctx context.Context, accountID string) ([]ListKidsExceptRow, error) {
	rows, err := q.db.Query(ctx, listKidsExcept, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKidsExceptRow
	for rows.Next() {
		var i ListKidsExceptRow
		if err := rows.Scan(&i.AccountID, &i.Kid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaves = `-- name: ListLeaves :many
SELECT account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at, request_state_hash, wallet_origin, moved, answered_state_hash FROM leaves WHERE account_id = $1 ORDER BY created_at, kid
`

func (q *Queries) ListLeaves(ctx context.Context, accountID string) ([]Leaf, error) {
	rows, err := q.db.Query(ctx, listLeaves, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaf
	for rows.Next() {
		var i Leaf
		if err := rows.Scan(
			&i.AccountID,
			&i.Kid,
			&i.Leaf,
			&i.KeySealed,
			&i.NotBefore,
			&i.NotAfter,
			&i.State,
			&i.Endpoint,
			&i.CreatedAt,
			&i.RequestStateHash,
			&i.WalletOrigin,
			&i.Moved,
			&i.AnsweredStateHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAddresses = `-- name: ListPendingAddresses :many
SELECT account_id, root, endpoint, leaf, why, at, root_cert FROM pending_addresses WHERE account_id = $1 ORDER BY at, root
`

func (q *Queries) ListPendingAddresses(ctx context.Context, accountID string) ([]PendingAddress, error) {
	rows, err := q.db.Query(ctx, listPendingAddresses, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAddress
	for rows.Next() {
		var i PendingAddress
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.Leaf,
			&i.Why,
			&i.At,
			&i.RootCert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstones = `-- name: ListTombstones :many
SELECT account_id, root, leaf, at FROM tombstones WHERE account_id = $1 ORDER BY at, root
`

func (q *Queries) ListTombstones(ctx context.Context, accountID string) ([]Tombstone, error) {
	rows, err := q.db.Query(ctx, listTombstones, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tombstone
	for rows.Next() {
		var i Tombstone
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Leaf,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacatedAddresses = `-- name: ListVacatedAddresses :many
SELECT endpoint, slug, until_at, at FROM vacated_addresses ORDER BY endpoint
`

func (q *Queries) ListVacatedAddresses(ctx context.Context) ([]VacatedAddress, error) {
	rows, err := q.db.Query(ctx, listVacatedAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacatedAddress
	for rows.Next() {
		var i VacatedAddress
		if err := rows.Scan(
			&i.Endpoint,
			&i.Slug,
			&i.UntilAt,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repinContactAddress = `-- name: RepinContactAddress :execrows
UPDATE contacts SET endpoint = $1, leaf = $2, leaf_fingerprint = $3, spki = $4, pinned_at = $5 WHERE account_id = $6 AND fingerprint = $7
`

type RepinContactAddressParams struct {
	Endpoint        string
	Leaf            []byte
	LeafFingerprint sql.NullString
	Spki            []byte
	PinnedAt        sql.NullInt64
	AccountID       string
	Fingerprint     string
}

// The 2.0 pin moves: a renewal at the pinned endpoint or an accepted new
// address replaces the leaf, its key and the endpoint; the root (the
// fingerprint column) never moves (HDTP sec. 14.3, sec. 5.3).
func (q *Queries) RepinContactAddress(ctx context.Context, arg RepinContactAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, repinContactAddress,
		arg.Endpoint,
		arg.Leaf,
		arg.LeafFingerprint,
		arg.Spki,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireLeafKey = `-- name: RetireLeafKey :execrows
UPDATE leaves SET key_sealed = NULL, state = 'former' WHERE account_id = $1 AND kid = $2
`

type RetireLeafKeyParams struct {
	AccountID string
	Kid       string
}

// A superseded leaf past its not_after: the key is destroyed, the kid kept so
// an envelope still sealed to it is answered certificate_renewed (HDTP sec. 14.4).
func (q *Queries) RetireLeafKey(ctx context.Context, arg RetireLeafKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireLeafKey, arg.AccountID, arg.Kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountHostPolicy = `-- name: SetAccountHostPolicy :execrows
UPDATE accounts SET accept_new_hosts = $1 WHERE id = $2
`

type SetAccountHostPolicyParams struct {
	AcceptNewHosts string
	ID             string
}

func (q *Queries) SetAccountHostPolicy(ctx context.Context, arg SetAccountHostPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountHostPolicy, arg.AcceptNewHosts, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountLeafKey = `-- name: SetAccountLeafKey :execrows
UPDATE accounts SET fingerprint = $1, key_sealed = $2, algo = $3 WHERE id = $4
`

type SetAccountLeafKeyParams struct {
	Fingerprint sql.NullString
	KeySealed   []byte
	Algo        string
	ID          string
}

// Re-points the account at its CURRENT leaf key. SetAccountKey binds once and
// never moves; a leaf install moves it, keeping every fingerprint-keyed path
// (routing, audit, pins) on the key that signs and seals today.
func (q *Queries) SetAccountLeafKey(ctx context.Context, arg SetAccountLeafKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountLeafKey,
		arg.Fingerprint,
		arg.KeySealed,
		arg.Algo,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountRoot = `-- name: SetAccountRoot :execrows

UPDATE accounts SET root_fingerprint = $1, root_cert = $2 WHERE id = $3
`

type SetAccountRootParams struct {
	RootFingerprint sql.NullString
	RootCert        []byte
	ID              string
}

// HDTP 1.0 state (SPEC sec. 2, sec. 14; migration 0027): the account's root and leaf
// ledger, 2.0 pins, the removal tombstone, former endpoints, and the
// addresses awaiting the owner under `accept_new_hosts = ask`.
// The first leaf installed names the account's root; the root never changes after (HDTP sec. 2).
func (q *Queries) SetAccountRoot(ctx context.Context, arg SetAccountRootParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountRoot, arg.RootFingerprint, arg.RootCert, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContactChainSentKid = `-- name: SetContactChainSentKid :execrows
UPDATE contacts SET chain_sent_kid = $1 WHERE account_id = $2 AND fingerprint = $3
`

type SetContactChainSentKidParams struct {
	ChainSentKid string
	AccountID    string
	Fingerprint  string
}

func (q *Queries) SetContactChainSentKid(ctx context.Context, arg SetContactChainSentKidParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContactChainSentKid, arg.ChainSentKid, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContactRootCert = `-- name: SetContactRootCert :execrows
UPDATE contacts SET root_cert = $1 WHERE account_id = $2 AND fingerprint = $3 AND (root_cert IS NULL OR length(root_cert) = 0)
`

type SetContactRootCertParams struct {
	RootCert    []byte
	AccountID   string
	Fingerprint string
}

// Fills in a pin's root certificate the first time a chain carries one: a pin made
// before this column existed, or one restored from an archive that could not carry it.
// Never overwrites, because the root a pin names cannot change (HDTP sec. 14.3) and the
// cert already stored is the one that was checked when the pin was made.
func (q *Queries) SetContactRootCert(ctx context.Context, arg SetContactRootCertParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContactRootCert, arg.RootCert, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLeafMoved = `-- name: SetLeafMoved :execrows
UPDATE leaves SET moved = $1 WHERE account_id = $2 AND kid = $3
`

type SetLeafMovedParams struct {
	Moved     int64
	AccountID string
	Kid       string
}

// Whether installing this leaf moved the identity, as the install decided it (migration 0043): what
// a resumed campaign reads to know whom it walks.
func (q *Queries) SetLeafMoved(ctx context.Context, arg SetLeafMovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLeafMoved, arg.Moved, arg.AccountID, arg.Kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLeafRequest = `-- name: SetLeafRequest :execrows
UPDATE leaves SET request_state_hash = $1, wallet_origin = $2 WHERE account_id = $3 AND kid = $4 AND state = 'pending'
`

type SetLeafRequestParams struct {
	RequestStateHash []byte
	WalletOrigin     string
	AccountID        string
	Kid              string
}

// The state a web wallet's answer must carry, as its SHA-256, and the wallet the request went to
// (migration 0041). Only a pending request carries one.
func (q *Queries) SetLeafRequest(ctx context.Context, arg SetLeafRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLeafRequest,
		arg.RequestStateHash,
		arg.WalletOrigin,
		arg.AccountID,
		arg.Kid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLeaf = `-- name: UpdateLeaf :execrows
UPDATE leaves SET leaf = $1, not_before = $2, not_after = $3, state = $4, endpoint = $5 WHERE account_id = $6 AND kid = $7
`

type UpdateLeafParams struct {
	Leaf      []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	AccountID string
	Kid       string
}

func (q *Queries) UpdateLeaf(ctx context.Context, arg UpdateLeafParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLeaf,
		arg.Leaf,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.AccountID,
		arg.Kid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPendingAddress = `-- name: UpsertPendingAddress :exec
INSERT INTO pending_addresses (account_id, root, endpoint, leaf, why, at, root_cert) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (account_id, root) DO UPDATE SET endpoint = excluded.endpoint, leaf = excluded.leaf, why = excluded.why, at = excluded.at,
  -- A later note for the same root must not erase a certificate already kept: the
  -- envelope path has none to offer, and the root of a pending address cannot change.
  root_cert = COALESCE(excluded.root_cert, pending_addresses.root_cert)
`

type UpsertPendingAddressParams struct {
	AccountID string
	Root      string
	Endpoint  string
	Leaf      []byte
	Why       string
	At        int64
	RootCert  []byte
}

func (q *Queries) UpsertPendingAddress(ctx context.Context, arg UpsertPendingAddressParams) error {
	_, err := q.db.Exec(ctx, upsertPendingAddress,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.Leaf,
		arg.Why,
		arg.At,
		arg.RootCert,
	)
	return err
}

const upsertTombstone = `-- name: UpsertTombstone :exec
INSERT INTO tombstones (account_id, root, leaf, at) VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, root) DO UPDATE SET leaf = excluded.leaf, at = excluded.at
`

type UpsertTombstoneParams struct {
	AccountID string
	Root      string
	Leaf      []byte
	At        int64
}

func (q *Queries) UpsertTombstone(ctx context.Context, arg UpsertTombstoneParams) error {
	_, err := q.db.Exec(ctx, upsertTombstone,
		arg.AccountID,
		arg.Root,
		arg.Leaf,
		arg.At,
	)
	return err
}

const upsertVacatedAddress = `-- name: UpsertVacatedAddress :exec
INSERT INTO vacated_addresses (endpoint, slug, until_at, at) VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE SET slug = excluded.slug, until_at = GREATEST(vacated_addresses.until_at, excluded.until_at), at = excluded.at
`

type UpsertVacatedAddressParams struct {
	Endpoint string
	Slug     string
	UntilAt  int64
	At       int64
}

// An address an identity has left (migration 0040, HDTP sec. 9). The row keeps the latest
// not_after it has been given: a second vacating of the same endpoint never shortens it.
func (q *Queries) UpsertVacatedAddress(ctx context.Context, arg UpsertVacatedAddressParams) error {
	_, err := q.db.Exec(ctx, upsertVacatedAddress,
		arg.Endpoint,
		arg.Slug,
		arg.UntilAt,
		arg.At,
	)
	return err
}
