// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package pgdb

import (
	"context"
	"database/sql"
)

const answerPendingRequest = `-- name: AnswerPendingRequest :execrows
UPDATE pending_requests SET status = 'answered', result = $1, answered_at = $2
WHERE account_id = $3 AND id = $4 AND status = 'open' AND expires_at > $5
`

type AnswerPendingRequestParams struct {
	Result     string
	AnsweredAt sql.NullInt64
	AccountID  string
	ID         string
	ExpiresAt  int64
}

func (q *Queries) AnswerPendingRequest(ctx context.Context, arg AnswerPendingRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerPendingRequest,
		arg.Result,
		arg.AnsweredAt,
		arg.AccountID,
		arg.ID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :execrows
DELETE FROM idempotency WHERE expires_at <= $1
`

// A record past its window protects nothing (HDTP sec. 13.3): nothing later than the window passes
// the freshness check, so a replay of that envelope is refused before this table is asked.
func (q *Queries) DeleteExpiredIdempotency(ctx context.Context, expiresAt sql.NullInt64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotency, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyByAccount = `-- name: DeleteIdempotencyByAccount :execrows
DELETE FROM idempotency WHERE account_id = $1
`

// The records of an identity that has left this host (HDTP sec. 9): the table has no foreign key.
func (q *Queries) DeleteIdempotencyByAccount(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdempotencyByAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIntegration = `-- name: DeleteIntegration :execrows
DELETE FROM integrations WHERE id = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUndatedIdempotencyBefore = `-- name: DeleteUndatedIdempotencyBefore :execrows
DELETE FROM idempotency WHERE expires_at IS NULL AND created_at <= $1
`

// A record written without a window (a `book_slot` replay guard) is kept thirty days (SPEC 11).
func (q *Queries) DeleteUndatedIdempotencyBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUndatedIdempotencyBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountIntegration = `-- name: GetAccountIntegration :one
SELECT id, account_id, slug, transport, endpoint, command, auth_kind, status, created_at, updated_at, secret FROM integrations WHERE account_id = $1 AND id = $2
`

type GetAccountIntegrationParams struct {
	AccountID string
	ID        string
}

func (q *Queries) GetAccountIntegration(ctx context.Context, arg GetAccountIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getAccountIntegration, arg.AccountID, arg.ID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Transport,
		&i.Endpoint,
		&i.Command,
		&i.AuthKind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Secret,
	)
	return i, err
}

const getAccountPendingRequest = `-- name: GetAccountPendingRequest :one
SELECT id, account_id, contact_fpr, capability, args, trust_flag, status, result, created_at, expires_at, answered_at FROM pending_requests WHERE account_id = $1 AND id = $2
`

type GetAccountPendingRequestParams struct {
	AccountID string
	ID        string
}

func (q *Queries) GetAccountPendingRequest(ctx context.Context, arg GetAccountPendingRequestParams) (PendingRequest, error) {
	row := q.db.QueryRow(ctx, getAccountPendingRequest, arg.AccountID, arg.ID)
	var i PendingRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.Capability,
		&i.Args,
		&i.TrustFlag,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getCatalog = `-- name: GetCatalog :one
SELECT id, integration_id, version, tools, created_at FROM catalogs WHERE integration_id = $1 AND version = $2
`

type GetCatalogParams struct {
	IntegrationID string
	Version       int64
}

func (q *Queries) GetCatalog(ctx context.Context, arg GetCatalogParams) (Catalog, error) {
	row := q.db.QueryRow(ctx, getCatalog, arg.IntegrationID, arg.Version)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Version,
		&i.Tools,
		&i.CreatedAt,
	)
	return i, err
}

const getExposure = `-- name: GetExposure :one
SELECT id, integration_id, version, catalog_version, entries, created_at FROM exposures WHERE integration_id = $1 AND version = $2
`

type GetExposureParams struct {
	IntegrationID string
	Version       int64
}

func (q *Queries) GetExposure(ctx context.Context, arg GetExposureParams) (Exposure, error) {
	row := q.db.QueryRow(ctx, getExposure, arg.IntegrationID, arg.Version)
	var i Exposure
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Version,
		&i.CatalogVersion,
		&i.Entries,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT ack FROM idempotency WHERE account_id = $1 AND contact_fpr = $2 AND msg_id = $3
`

type GetIdempotencyParams struct {
	AccountID  string
	ContactFpr string
	MsgID      string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (string, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.AccountID, arg.ContactFpr, arg.MsgID)
	var ack string
	err := row.Scan(&ack)
	return ack, err
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, account_id, slug, transport, endpoint, command, auth_kind, status, created_at, updated_at, secret FROM integrations WHERE account_id = $1 AND slug = $2
`

type GetIntegrationParams struct {
	AccountID string
	Slug      string
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.AccountID, arg.Slug)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Transport,
		&i.Endpoint,
		&i.Command,
		&i.AuthKind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Secret,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, account_id, slug, transport, endpoint, command, auth_kind, status, created_at, updated_at, secret FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id string) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Transport,
		&i.Endpoint,
		&i.Command,
		&i.AuthKind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Secret,
	)
	return i, err
}

const getIntegrationSecret = `-- name: GetIntegrationSecret :one
SELECT secret FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationSecret(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getIntegrationSecret, id)
	var secret []byte
	err := row.Scan(&secret)
	return secret, err
}

const getPendingRequest = `-- name: GetPendingRequest :one
SELECT id, account_id, contact_fpr, capability, args, trust_flag, status, result, created_at, expires_at, answered_at FROM pending_requests WHERE id = $1
`

func (q *Queries) GetPendingRequest(ctx context.Context, id string) (PendingRequest, error) {
	row := q.db.QueryRow(ctx, getPendingRequest, id)
	var i PendingRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.Capability,
		&i.Args,
		&i.TrustFlag,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AnsweredAt,
	)
	return i, err
}

const insertCatalog = `-- name: InsertCatalog :exec
INSERT INTO catalogs (id, integration_id, version, tools, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCatalogParams struct {
	ID            string
	IntegrationID string
	Version       int64
	Tools         string
	CreatedAt     int64
}

func (q *Queries) InsertCatalog(ctx context.Context, arg InsertCatalogParams) error {
	_, err := q.db.Exec(ctx, insertCatalog,
		arg.ID,
		arg.IntegrationID,
		arg.Version,
		arg.Tools,
		arg.CreatedAt,
	)
	return err
}

const insertExposure = `-- name: InsertExposure :exec
INSERT INTO exposures (id, integration_id, version, catalog_version, entries, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertExposureParams struct {
	ID             string
	IntegrationID  string
	Version        int64
	CatalogVersion int64
	Entries        string
	CreatedAt      int64
}

func (q *Queries) InsertExposure(ctx context.Context, arg InsertExposureParams) error {
	_, err := q.db.Exec(ctx, insertExposure,
		arg.ID,
		arg.IntegrationID,
		arg.Version,
		arg.CatalogVersion,
		arg.Entries,
		arg.CreatedAt,
	)
	return err
}

const insertIdempotency = `-- name: InsertIdempotency :execrows
INSERT INTO idempotency (account_id, contact_fpr, msg_id, ack, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING
`

type InsertIdempotencyParams struct {
	AccountID  string
	ContactFpr string
	MsgID      string
	Ack        string
	CreatedAt  int64
	ExpiresAt  sql.NullInt64
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotency,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
		arg.Ack,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertIntegration = `-- name: InsertIntegration :exec
INSERT INTO integrations (id, account_id, slug, transport, endpoint, command, auth_kind, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertIntegrationParams struct {
	ID        string
	AccountID string
	Slug      string
	Transport string
	Endpoint  string
	Command   string
	AuthKind  string
	Status    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertIntegration(ctx context.Context, arg InsertIntegrationParams) error {
	_, err := q.db.Exec(ctx, insertIntegration,
		arg.ID,
		arg.AccountID,
		arg.Slug,
		arg.Transport,
		arg.Endpoint,
		arg.Command,
		arg.AuthKind,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPendingRequest = `-- name: InsertPendingRequest :exec
INSERT INTO pending_requests (id, account_id, contact_fpr, capability, args, trust_flag, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPendingRequestParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	Capability string
	Args       string
	TrustFlag  string
	CreatedAt  int64
	ExpiresAt  int64
}

func (q *Queries) InsertPendingRequest(ctx context.Context, arg InsertPendingRequestParams) error {
	_, err := q.db.Exec(ctx, insertPendingRequest,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Capability,
		arg.Args,
		arg.TrustFlag,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const latestCatalog = `-- name: LatestCatalog :one
SELECT id, integration_id, version, tools, created_at FROM catalogs WHERE integration_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) LatestCatalog(ctx context.Context, integrationID string) (Catalog, error) {
	row := q.db.QueryRow(ctx, latestCatalog, integrationID)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Version,
		&i.Tools,
		&i.CreatedAt,
	)
	return i, err
}

const latestExposure = `-- name: LatestExposure :one
SELECT id, integration_id, version, catalog_version, entries, created_at FROM exposures WHERE integration_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) LatestExposure(ctx context.Context, integrationID string) (Exposure, error) {
	row := q.db.QueryRow(ctx, latestExposure, integrationID)
	var i Exposure
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Version,
		&i.CatalogVersion,
		&i.Entries,
		&i.CreatedAt,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, account_id, slug, transport, endpoint, command, auth_kind, status, created_at, updated_at, secret FROM integrations WHERE account_id = $1 ORDER BY slug
`

func (q *Queries) ListIntegrations(ctx context.Context, accountID string) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Slug,
			&i.Transport,
			&i.Endpoint,
			&i.Command,
			&i.AuthKind,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPendingRequests = `-- name: ListOpenPendingRequests :many
SELECT id, account_id, contact_fpr, capability, args, trust_flag, status, result, created_at, expires_at, answered_at FROM pending_requests WHERE account_id = $1 AND status = 'open' AND expires_at > $2 ORDER BY created_at, id
`

type ListOpenPendingRequestsParams struct {
	AccountID string
	ExpiresAt int64
}

func (q *Queries) ListOpenPendingRequests(ctx context.Context, arg ListOpenPendingRequestsParams) ([]PendingRequest, error) {
	rows, err := q.db.Query(ctx, listOpenPendingRequests, arg.AccountID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingRequest
	for rows.Next() {
		var i PendingRequest
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.Capability,
			&i.Args,
			&i.TrustFlag,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIntegrationSecret = `-- name: SetIntegrationSecret :execrows
UPDATE integrations SET secret = $1, updated_at = $2 WHERE id = $3
`

type SetIntegrationSecretParams struct {
	Secret    []byte
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetIntegrationSecret(ctx context.Context, arg SetIntegrationSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIntegrationSecret, arg.Secret, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIdempotencyAck = `-- name: UpdateIdempotencyAck :execrows
UPDATE idempotency SET ack = $1 WHERE account_id = $2 AND contact_fpr = $3 AND msg_id = $4
`

type UpdateIdempotencyAckParams struct {
	Ack        string
	AccountID  string
	ContactFpr string
	MsgID      string
}

func (q *Queries) UpdateIdempotencyAck(ctx context.Context, arg UpdateIdempotencyAckParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIdempotencyAck,
		arg.Ack,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIntegrationConfig = `-- name: UpdateIntegrationConfig :execrows
UPDATE integrations SET transport = $1, endpoint = $2, command = $3, auth_kind = $4, updated_at = $5 WHERE id = $6
`

type UpdateIntegrationConfigParams struct {
	Transport string
	Endpoint  string
	Command   string
	AuthKind  string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateIntegrationConfig(ctx context.Context, arg UpdateIntegrationConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIntegrationConfig,
		arg.Transport,
		arg.Endpoint,
		arg.Command,
		arg.AuthKind,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIntegrationStatus = `-- name: UpdateIntegrationStatus :execrows
UPDATE integrations SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdateIntegrationStatusParams struct {
	Status    string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateIntegrationStatus(ctx context.Context, arg UpdateIntegrationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIntegrationStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
