// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leases.sql

package pgdb

import (
	"context"
)

const takeLease = `-- name: TakeLease :one
INSERT INTO leases (name, holder, taken_at, expires_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET holder = excluded.holder, taken_at = excluded.taken_at, expires_at = excluded.expires_at
WHERE leases.holder = excluded.holder OR leases.expires_at < excluded.taken_at
RETURNING holder
`

type TakeLeaseParams struct {
	Name   string
	Holder string
	Now    int64
	Until  int64
}

// Takes the lease, or renews it for its holder; a lease another holds and has not let expire by
// the time this one is taken (excluded.taken_at) is left as it is, and no row comes back.
func (q *Queries) TakeLease(ctx context.Context, arg TakeLeaseParams) (string, error) {
	row := q.db.QueryRow(ctx, takeLease,
		arg.Name,
		arg.Holder,
		arg.Now,
		arg.Until,
	)
	var holder string
	err := row.Scan(&holder)
	return holder, err
}
