// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messaging.sql

package pgdb

import (
	"context"
)

const conversationHasMessage = `-- name: ConversationHasMessage :one
SELECT COUNT(*) FROM messages m JOIN threads t ON t.account_id = m.account_id AND t.id = m.thread_id
WHERE m.account_id = $1 AND t.contact_fpr = $2 AND m.seq = $3
`

type ConversationHasMessageParams struct {
	AccountID  string
	ContactFpr string
	Seq        int64
}

// Whether `seq` is a message of this account's conversation with this contact: what a read
// marker may name. Another identity's message, or one of another contact, is not.
func (q *Queries) ConversationHasMessage(ctx context.Context, arg ConversationHasMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, conversationHasMessage, arg.AccountID, arg.ContactFpr, arg.Seq)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBlobRefs = `-- name: CountBlobRefs :one
SELECT COUNT(*) FROM blobs WHERE hash = $1
`

func (q *Queries) CountBlobRefs(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRow(ctx, countBlobRefs, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlob = `-- name: DeleteBlob :execrows
DELETE FROM blobs WHERE account_id = $1 AND hash = $2
`

type DeleteBlobParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlob, arg.AccountID, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmptyThreads = `-- name: DeleteEmptyThreads :execrows
DELETE FROM threads WHERE threads.account_id = $1
  AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.account_id = threads.account_id AND m.thread_id = threads.id)
`

// One index probe per thread. As a NOT IN over the account's messages it listed the thread of
// every message the account has before it looked at a single thread.
func (q *Queries) DeleteEmptyThreads(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptyThreads, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessagesBefore = `-- name: DeleteMessagesBefore :execrows
DELETE FROM messages WHERE account_id = $1 AND created_at < $2
`

type DeleteMessagesBeforeParams struct {
	AccountID string
	CreatedAt int64
}

func (q *Queries) DeleteMessagesBefore(ctx context.Context, arg DeleteMessagesBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagesBefore, arg.AccountID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteThread = `-- name: DeleteThread :execrows
DELETE FROM threads WHERE account_id = $1 AND id = $2
`

type DeleteThreadParams struct {
	AccountID string
	ID        string
}

func (q *Queries) DeleteThread(ctx context.Context, arg DeleteThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteThread, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteThreadMessages = `-- name: DeleteThreadMessages :execrows
DELETE FROM messages WHERE account_id = $1 AND thread_id = $2
`

type DeleteThreadMessagesParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) DeleteThreadMessages(ctx context.Context, arg DeleteThreadMessagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteThreadMessages, arg.AccountID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlob = `-- name: GetBlob :one
SELECT account_id, hash, size, mime, filename, created_at FROM blobs WHERE account_id = $1 AND hash = $2
`

type GetBlobParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlob, arg.AccountID, arg.Hash)
	var i Blob
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.Size,
		&i.Mime,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = $1 AND id = $2
`

type GetMessageParams struct {
	AccountID string
	ID        string
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.AccountID, arg.ID)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.MsgID,
		&i.ThreadID,
		&i.Direction,
		&i.Sender,
		&i.Body,
		&i.ReplyTo,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.ExpiresAt,
		&i.Attempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const getMessageByMsgID = `-- name: GetMessageByMsgID :one
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = $1 AND contact_fpr = $2 AND direction = $3 AND msg_id = $4
`

type GetMessageByMsgIDParams struct {
	AccountID  string
	ContactFpr string
	Direction  string
	MsgID      string
}

func (q *Queries) GetMessageByMsgID(ctx context.Context, arg GetMessageByMsgIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByMsgID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Direction,
		arg.MsgID,
	)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.MsgID,
		&i.ThreadID,
		&i.Direction,
		&i.Sender,
		&i.Body,
		&i.ReplyTo,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.ExpiresAt,
		&i.Attempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, account_id, contact_fpr, topic, created_at, last_at, last_read_seq, kept_display_name, kept_petname FROM threads WHERE account_id = $1 AND id = $2
`

type GetThreadParams struct {
	AccountID string
	ID        string
}

func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, arg.AccountID, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.Topic,
		&i.CreatedAt,
		&i.LastAt,
		&i.LastReadSeq,
		&i.KeptDisplayName,
		&i.KeptPetname,
	)
	return i, err
}

const importBlob = `-- name: ImportBlob :execrows
INSERT INTO blobs (account_id, hash, size, mime, filename, created_at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type ImportBlobParams struct {
	AccountID string
	Hash      string
	Size      int64
	Mime      string
	Filename  string
	CreatedAt int64
}

// The record of a file arriving in an export. One already here, by hash, is left as it is.
func (q *Queries) ImportBlob(ctx context.Context, arg ImportBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, importBlob,
		arg.AccountID,
		arg.Hash,
		arg.Size,
		arg.Mime,
		arg.Filename,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importMessage = `-- name: ImportMessage :execrows
INSERT INTO messages (id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT DO NOTHING
`

type ImportMessageParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	MsgID      string
	ThreadID   string
	Direction  string
	Sender     string
	Kind       string
	Body       string
	ReplyTo    string
	Status     string
	CreatedAt  int64
}

// A message arriving in an export, with no retry schedule (it was the old host's to deliver).
// One already here, by id or by its sender's msg_id, is left as it is.
func (q *Queries) ImportMessage(ctx context.Context, arg ImportMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, importMessage,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
		arg.ThreadID,
		arg.Direction,
		arg.Sender,
		arg.Kind,
		arg.Body,
		arg.ReplyTo,
		arg.Status,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importThread = `-- name: ImportThread :execrows
INSERT INTO threads (id, account_id, contact_fpr, topic, created_at, last_at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type ImportThreadParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	Topic      string
	CreatedAt  int64
	LastAt     int64
}

// A thread arriving in an export (SPEC sec. 3.10). One already here, by id, is left as it is:
// importing into an identity this host already holds adds what it lacks and changes nothing else.
func (q *Queries) ImportThread(ctx context.Context, arg ImportThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, importThread,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Topic,
		arg.CreatedAt,
		arg.LastAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBlob = `-- name: InsertBlob :exec
INSERT INTO blobs (account_id, hash, size, mime, filename, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBlobParams struct {
	AccountID string
	Hash      string
	Size      int64
	Mime      string
	Filename  string
	CreatedAt int64
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) error {
	_, err := q.db.Exec(ctx, insertBlob,
		arg.AccountID,
		arg.Hash,
		arg.Size,
		arg.Mime,
		arg.Filename,
		arg.CreatedAt,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertMessageParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	MsgID      string
	ThreadID   string
	Direction  string
	Sender     string
	Kind       string
	Body       string
	ReplyTo    string
	Status     string
	CreatedAt  int64
	ExpiresAt  int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
		arg.ThreadID,
		arg.Direction,
		arg.Sender,
		arg.Kind,
		arg.Body,
		arg.ReplyTo,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertThread = `-- name: InsertThread :exec
INSERT INTO threads (id, account_id, contact_fpr, topic, created_at, last_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertThreadParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	Topic      string
	CreatedAt  int64
	LastAt     int64
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) error {
	_, err := q.db.Exec(ctx, insertThread,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Topic,
		arg.CreatedAt,
		arg.LastAt,
	)
	return err
}

const listBlobs = `-- name: ListBlobs :many
SELECT account_id, hash, size, mime, filename, created_at FROM blobs WHERE account_id = $1 ORDER BY created_at
`

func (q *Queries) ListBlobs(ctx context.Context, accountID string) ([]Blob, error) {
	rows, err := q.db.Query(ctx, listBlobs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.AccountID,
			&i.Hash,
			&i.Size,
			&i.Mime,
			&i.Filename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsWithUnread = `-- name: ListContactsWithUnread :many
SELECT DISTINCT t.contact_fpr FROM threads t
WHERE t.account_id = $1 AND EXISTS (
  SELECT 1 FROM messages m
  WHERE m.account_id = t.account_id AND m.thread_id = t.id AND m.direction = 'in' AND m.seq > t.last_read_seq
)
ORDER BY t.contact_fpr
`

// The contacts with at least one unread message, never a count: for each thread, messages_thread
// is walked from the thread's marker until the first inbound message, past any of ours.
func (q *Queries) ListContactsWithUnread(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listContactsWithUnread, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var contact_fpr string
		if err := rows.Scan(&contact_fpr); err != nil {
			return nil, err
		}
		items = append(items, contact_fpr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaBodies = `-- name: ListMediaBodies :many
SELECT body FROM messages WHERE account_id = $1 AND kind = 'media' ORDER BY seq
`

// What retention reads to learn which media is still referenced: the media messages, and only
// those, from `messages_media`. It used to be learned by reading every message of every thread.
func (q *Queries) ListMediaBodies(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMediaBodies, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var body string
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByThread = `-- name: ListMessagesByThread :many
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = $1 AND thread_id = $2 ORDER BY seq
`

type ListMessagesByThreadParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) ListMessagesByThread(ctx context.Context, arg ListMessagesByThreadParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByThread, arg.AccountID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.MsgID,
			&i.ThreadID,
			&i.Direction,
			&i.Sender,
			&i.Body,
			&i.ReplyTo,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.ExpiresAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutbound = `-- name: ListPendingOutbound :many
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at, expires_at, attempts, next_attempt_at
FROM messages WHERE direction = 'out' AND status = 'pending' ORDER BY seq LIMIT $1
`

type ListPendingOutboundRow struct {
	Seq           int64
	ID            string
	AccountID     string
	ContactFpr    string
	MsgID         string
	ThreadID      string
	Direction     string
	Sender        string
	Kind          string
	Body          string
	ReplyTo       string
	Status        string
	CreatedAt     int64
	ExpiresAt     int64
	Attempts      int64
	NextAttemptAt int64
}

// ListPendingOutbound is the retry sweeper's work list (SPEC sec. 7.1): outbound
// messages still awaiting delivery, oldest first.
func (q *Queries) ListPendingOutbound(ctx context.Context, limit int32) ([]ListPendingOutboundRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutbound, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboundRow
	for rows.Next() {
		var i ListPendingOutboundRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.MsgID,
			&i.ThreadID,
			&i.Direction,
			&i.Sender,
			&i.Kind,
			&i.Body,
			&i.ReplyTo,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMediaBodies = `-- name: ListThreadMediaBodies :many
SELECT body FROM messages WHERE account_id = $1 AND thread_id = $2 AND kind = 'media' ORDER BY seq
`

type ListThreadMediaBodiesParams struct {
	AccountID string
	ThreadID  string
}

// The media one thread's messages describe: the files deleting the thread may leave unreferenced.
func (q *Queries) ListThreadMediaBodies(ctx context.Context, arg ListThreadMediaBodiesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listThreadMediaBodies, arg.AccountID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var body string
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByAccount = `-- name: ListThreadsByAccount :many
SELECT id, account_id, contact_fpr, topic, created_at, last_at, last_read_seq, kept_display_name, kept_petname FROM threads WHERE account_id = $1 ORDER BY last_at DESC, id
`

func (q *Queries) ListThreadsByAccount(ctx context.Context, accountID string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.Topic,
			&i.CreatedAt,
			&i.LastAt,
			&i.LastReadSeq,
			&i.KeptDisplayName,
			&i.KeptPetname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationReadThrough = `-- name: MarkConversationReadThrough :execrows
UPDATE threads SET last_read_seq = $1
WHERE account_id = $2 AND contact_fpr = $3 AND last_read_seq < $1
`

type MarkConversationReadThroughParams struct {
	LastReadSeq int64
	AccountID   string
	ContactFpr  string
}

// Every thread with one contact, through one message: a conversation is with a person, not a
// thread id, and seq is one sequence over every message, so every message of the conversation
// at or below `through` was on the page the reader was shown.
func (q *Queries) MarkConversationReadThrough(ctx context.Context, arg MarkConversationReadThroughParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConversationReadThrough, arg.LastReadSeq, arg.AccountID, arg.ContactFpr)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markThreadReadThrough = `-- name: MarkThreadReadThrough :execrows
UPDATE threads SET last_read_seq = $1
WHERE account_id = $2 AND id = $3 AND last_read_seq < $1
`

type MarkThreadReadThroughParams struct {
	LastReadSeq int64
	AccountID   string
	ID          string
}

// The read marker is a high-water mark, never lowered: a reader marks through the newest message
// it was shown (`through`), so what arrived after it stays unread, and marking again
// changes nothing.
func (q *Queries) MarkThreadReadThrough(ctx context.Context, arg MarkThreadReadThroughParams) (int64, error) {
	result, err := q.db.Exec(ctx, markThreadReadThrough, arg.LastReadSeq, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMediaBody = `-- name: SetMediaBody :execrows
UPDATE messages SET body = $1 WHERE account_id = $2 AND id = $3 AND kind = 'media'
`

type SetMediaBodyParams struct {
	Body      string
	AccountID string
	ID        string
}

// A media message's description, rewritten: a URL the owner fetched now names the file it fetched.
func (q *Queries) SetMediaBody(ctx context.Context, arg SetMediaBodyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMediaBody, arg.Body, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMessageAttempt = `-- name: SetMessageAttempt :execrows
UPDATE messages SET attempts = $1, next_attempt_at = $2
WHERE account_id = $3 AND contact_fpr = $4 AND msg_id = $5 AND direction = 'out'
`

type SetMessageAttemptParams struct {
	Attempts      int64
	NextAttemptAt int64
	AccountID     string
	ContactFpr    string
	MsgID         string
}

// SetMessageAttempt records that a delivery attempt was made and when the next
// one is due. Backoff is a function of attempts MADE, so the count has to
// survive the sweep that made it.
func (q *Queries) SetMessageAttempt(ctx context.Context, arg SetMessageAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMessageAttempt,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMessageStatus = `-- name: SetMessageStatus :execrows
UPDATE messages SET status = $1 WHERE account_id = $2 AND contact_fpr = $3 AND msg_id = $4 AND direction = 'out'
`

type SetMessageStatusParams struct {
	Status     string
	AccountID  string
	ContactFpr string
	MsgID      string
}

// SetMessageStatus records what became of a message AFTER it was written. It is
// scoped to direction='out' on purpose: only a message we sent has a delivery
// outcome, and without the scope an outbound msg_id colliding with an inbound
// one rewrote the peer's row instead.
func (q *Queries) SetMessageStatus(ctx context.Context, arg SetMessageStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMessageStatus,
		arg.Status,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumBlobBytes = `-- name: SumBlobBytes :one
SELECT COALESCE(SUM(size), 0)::bigint FROM blobs WHERE account_id = $1
`

func (q *Queries) SumBlobBytes(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumBlobBytes, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchThread = `-- name: TouchThread :execrows
UPDATE threads SET last_at = $1 WHERE account_id = $2 AND id = $3
`

type TouchThreadParams struct {
	LastAt    int64
	AccountID string
	ID        string
}

func (q *Queries) TouchThread(ctx context.Context, arg TouchThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchThread, arg.LastAt, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*) FROM messages m JOIN threads t ON t.account_id = m.account_id AND t.id = m.thread_id
WHERE m.account_id = $1 AND m.thread_id = $2 AND m.direction = 'in' AND m.seq > t.last_read_seq
`

type UnreadCountParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) UnreadCount(ctx context.Context, arg UnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, unreadCount, arg.AccountID, arg.ThreadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unreadWithContactUpTo = `-- name: UnreadWithContactUpTo :one
SELECT COUNT(*) FROM (
  SELECT 1 FROM threads t JOIN messages m ON m.account_id = t.account_id AND m.thread_id = t.id
  WHERE t.account_id = $1 AND t.contact_fpr = $2
    AND m.direction = 'in' AND m.seq > t.last_read_seq
  LIMIT $3
) AS u
`

type UnreadWithContactUpToParams struct {
	AccountID  string
	ContactFpr string
	Limit      int32
}

// A conversation's unread, counted no further than a bound: the inbox reads it for every
// row of a page on every visit, so it stops at a bound instead of walking every unread message.
func (q *Queries) UnreadWithContactUpTo(ctx context.Context, arg UnreadWithContactUpToParams) (int64, error) {
	row := q.db.QueryRow(ctx, unreadWithContactUpTo, arg.AccountID, arg.ContactFpr, arg.Limit)
	var count int64
	err := row.Scan(&count)
	return count, err
}
