// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messaging.sql

package pgdb

import (
	"context"
)

const countBlobRefs = `-- name: CountBlobRefs :one
SELECT COUNT(*) FROM blobs WHERE hash = $1
`

func (q *Queries) CountBlobRefs(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRow(ctx, countBlobRefs, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlob = `-- name: DeleteBlob :execrows
DELETE FROM blobs WHERE account_id = $1 AND hash = $2
`

type DeleteBlobParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlob, arg.AccountID, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmptyThreads = `-- name: DeleteEmptyThreads :execrows
DELETE FROM threads WHERE threads.account_id = $1
  AND threads.id NOT IN (SELECT thread_id FROM messages WHERE messages.account_id = $2)
`

type DeleteEmptyThreadsParams struct {
	AccountID   string
	AccountID_2 string
}

func (q *Queries) DeleteEmptyThreads(ctx context.Context, arg DeleteEmptyThreadsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptyThreads, arg.AccountID, arg.AccountID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessagesBefore = `-- name: DeleteMessagesBefore :execrows
DELETE FROM messages WHERE account_id = $1 AND created_at < $2
`

type DeleteMessagesBeforeParams struct {
	AccountID string
	CreatedAt int64
}

func (q *Queries) DeleteMessagesBefore(ctx context.Context, arg DeleteMessagesBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagesBefore, arg.AccountID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlob = `-- name: GetBlob :one
SELECT account_id, hash, size, mime, filename, created_at FROM blobs WHERE account_id = $1 AND hash = $2
`

type GetBlobParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlob, arg.AccountID, arg.Hash)
	var i Blob
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.Size,
		&i.Mime,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByMsgID = `-- name: GetMessageByMsgID :one
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = $1 AND contact_fpr = $2 AND direction = $3 AND msg_id = $4
`

type GetMessageByMsgIDParams struct {
	AccountID  string
	ContactFpr string
	Direction  string
	MsgID      string
}

func (q *Queries) GetMessageByMsgID(ctx context.Context, arg GetMessageByMsgIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByMsgID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Direction,
		arg.MsgID,
	)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.MsgID,
		&i.ThreadID,
		&i.Direction,
		&i.Sender,
		&i.Body,
		&i.ReplyTo,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.ExpiresAt,
		&i.Attempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, account_id, contact_fpr, topic, created_at, last_at, last_read_seq FROM threads WHERE account_id = $1 AND id = $2
`

type GetThreadParams struct {
	AccountID string
	ID        string
}

func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, arg.AccountID, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.Topic,
		&i.CreatedAt,
		&i.LastAt,
		&i.LastReadSeq,
	)
	return i, err
}

const insertBlob = `-- name: InsertBlob :exec
INSERT INTO blobs (account_id, hash, size, mime, filename, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBlobParams struct {
	AccountID string
	Hash      string
	Size      int64
	Mime      string
	Filename  string
	CreatedAt int64
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) error {
	_, err := q.db.Exec(ctx, insertBlob,
		arg.AccountID,
		arg.Hash,
		arg.Size,
		arg.Mime,
		arg.Filename,
		arg.CreatedAt,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertMessageParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	MsgID      string
	ThreadID   string
	Direction  string
	Sender     string
	Kind       string
	Body       string
	ReplyTo    string
	Status     string
	CreatedAt  int64
	ExpiresAt  int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
		arg.ThreadID,
		arg.Direction,
		arg.Sender,
		arg.Kind,
		arg.Body,
		arg.ReplyTo,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertThread = `-- name: InsertThread :exec
INSERT INTO threads (id, account_id, contact_fpr, topic, created_at, last_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertThreadParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	Topic      string
	CreatedAt  int64
	LastAt     int64
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) error {
	_, err := q.db.Exec(ctx, insertThread,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Topic,
		arg.CreatedAt,
		arg.LastAt,
	)
	return err
}

const listBlobs = `-- name: ListBlobs :many
SELECT account_id, hash, size, mime, filename, created_at FROM blobs WHERE account_id = $1 ORDER BY created_at
`

func (q *Queries) ListBlobs(ctx context.Context, accountID string) ([]Blob, error) {
	rows, err := q.db.Query(ctx, listBlobs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.AccountID,
			&i.Hash,
			&i.Size,
			&i.Mime,
			&i.Filename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByThread = `-- name: ListMessagesByThread :many
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = $1 AND thread_id = $2 ORDER BY seq
`

type ListMessagesByThreadParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) ListMessagesByThread(ctx context.Context, arg ListMessagesByThreadParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByThread, arg.AccountID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.MsgID,
			&i.ThreadID,
			&i.Direction,
			&i.Sender,
			&i.Body,
			&i.ReplyTo,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.ExpiresAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutbound = `-- name: ListPendingOutbound :many
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at, expires_at, attempts, next_attempt_at
FROM messages WHERE direction = 'out' AND status = 'pending' ORDER BY seq LIMIT $1
`

type ListPendingOutboundRow struct {
	Seq           int64
	ID            string
	AccountID     string
	ContactFpr    string
	MsgID         string
	ThreadID      string
	Direction     string
	Sender        string
	Kind          string
	Body          string
	ReplyTo       string
	Status        string
	CreatedAt     int64
	ExpiresAt     int64
	Attempts      int64
	NextAttemptAt int64
}

// ListPendingOutbound is the retry sweeper's work list (SPEC sec. 7.1): outbound
// messages still awaiting delivery, oldest first.
func (q *Queries) ListPendingOutbound(ctx context.Context, limit int32) ([]ListPendingOutboundRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutbound, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboundRow
	for rows.Next() {
		var i ListPendingOutboundRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.MsgID,
			&i.ThreadID,
			&i.Direction,
			&i.Sender,
			&i.Kind,
			&i.Body,
			&i.ReplyTo,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByAccount = `-- name: ListThreadsByAccount :many
SELECT id, account_id, contact_fpr, topic, created_at, last_at, last_read_seq FROM threads WHERE account_id = $1 ORDER BY last_at DESC, id
`

func (q *Queries) ListThreadsByAccount(ctx context.Context, accountID string) ([]Thread, error) {
	rows, err := q.db.Query(ctx, listThreadsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.Topic,
			&i.CreatedAt,
			&i.LastAt,
			&i.LastReadSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThreadRead = `-- name: MarkThreadRead :execrows
UPDATE threads SET last_read_seq = (
  SELECT COALESCE(MAX(m.seq), 0) FROM messages m WHERE m.account_id = $1 AND m.thread_id = $2
) WHERE threads.account_id = $3 AND threads.id = $4
`

type MarkThreadReadParams struct {
	AccountID   string
	ThreadID    string
	AccountID_2 string
	ID          string
}

func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markThreadRead,
		arg.AccountID,
		arg.ThreadID,
		arg.AccountID_2,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMessageAttempt = `-- name: SetMessageAttempt :execrows
UPDATE messages SET attempts = $1, next_attempt_at = $2
WHERE account_id = $3 AND contact_fpr = $4 AND msg_id = $5 AND direction = 'out'
`

type SetMessageAttemptParams struct {
	Attempts      int64
	NextAttemptAt int64
	AccountID     string
	ContactFpr    string
	MsgID         string
}

// SetMessageAttempt records that a delivery attempt was made and when the next
// one is due. Backoff is a function of attempts MADE, so the count has to
// survive the sweep that made it.
func (q *Queries) SetMessageAttempt(ctx context.Context, arg SetMessageAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMessageAttempt,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMessageStatus = `-- name: SetMessageStatus :execrows
UPDATE messages SET status = $1 WHERE account_id = $2 AND contact_fpr = $3 AND msg_id = $4 AND direction = 'out'
`

type SetMessageStatusParams struct {
	Status     string
	AccountID  string
	ContactFpr string
	MsgID      string
}

// SetMessageStatus records what became of a message AFTER it was written. It is
// scoped to direction='out' on purpose: only a message we sent has a delivery
// outcome, and without the scope an outbound msg_id colliding with an inbound
// one rewrote the peer's row instead.
func (q *Queries) SetMessageStatus(ctx context.Context, arg SetMessageStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMessageStatus,
		arg.Status,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumBlobBytes = `-- name: SumBlobBytes :one
SELECT COALESCE(SUM(size), 0)::bigint FROM blobs WHERE account_id = $1
`

func (q *Queries) SumBlobBytes(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumBlobBytes, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchThread = `-- name: TouchThread :exec
UPDATE threads SET last_at = $1 WHERE account_id = $2 AND id = $3
`

type TouchThreadParams struct {
	LastAt    int64
	AccountID string
	ID        string
}

func (q *Queries) TouchThread(ctx context.Context, arg TouchThreadParams) error {
	_, err := q.db.Exec(ctx, touchThread, arg.LastAt, arg.AccountID, arg.ID)
	return err
}

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*) FROM messages m JOIN threads t ON t.account_id = m.account_id AND t.id = m.thread_id
WHERE m.account_id = $1 AND m.thread_id = $2 AND m.direction = 'in' AND m.seq > t.last_read_seq
`

type UnreadCountParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) UnreadCount(ctx context.Context, arg UnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, unreadCount, arg.AccountID, arg.ThreadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
