// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              string
	Slug            string
	DisplayName     string
	Algo            string
	Fingerprint     pgtype.Text
	KeySealed       []byte
	Seal            string
	Status          string
	CreatedAt       int64
	PrevFingerprint pgtype.Text
	PrevKeySealed   []byte
	GraceUntil      int64
}

type AuditEvent struct {
	Seq       int64
	Ts        int64
	AccountID pgtype.Text
	ActorKind string
	ActorID   string
	Action    string
	Resource  string
	Outcome   string
	RequestID string
	Details   string
	PrevHash  string
	Hash      string
}

type Blob struct {
	AccountID string
	Hash      string
	Size      int64
	Mime      string
	Filename  string
	CreatedAt int64
}

type Catalog struct {
	ID            string
	IntegrationID string
	Version       int64
	Tools         string
	CreatedAt     int64
}

type Contact struct {
	ID               string
	AccountID        string
	Fingerprint      string
	Spki             []byte
	Status           string
	Preset           string
	Permissions      string
	TrustFlag        string
	DisplayName      string
	Card             string
	CreatedAt        int64
	PinnedAt         pgtype.Int8
	TheirPermissions string
	Petname          string
	InviteID         string
}

type Credential struct {
	ID         string
	OwnerID    string
	Kind       string
	Tag        string
	Data       []byte
	CreatedAt  int64
	LastUsedAt pgtype.Int8
}

type Exposure struct {
	ID             string
	IntegrationID  string
	Version        int64
	CatalogVersion int64
	Entries        string
	CreatedAt      int64
}

type Idempotency struct {
	AccountID  string
	ContactFpr string
	MsgID      string
	Ack        string
	CreatedAt  int64
	ExpiresAt  pgtype.Int8
}

type Integration struct {
	ID        string
	AccountID string
	Slug      string
	Transport string
	Endpoint  string
	Command   string
	AuthKind  string
	Status    string
	CreatedAt int64
	UpdatedAt int64
	Secret    []byte
}

type Invite struct {
	ID          string
	AccountID   string
	TokenHash   []byte
	ExpiresAt   int64
	MaxUses     int64
	Uses        int64
	AutoAccept  int64
	Preset      string
	Permissions string
	Label       string
	RevokedAt   pgtype.Int8
	CreatedAt   int64
}

type Membership struct {
	OwnerID   string
	AccountID string
	Role      string
}

type Message struct {
	Seq           int64
	ID            string
	AccountID     string
	ContactFpr    string
	MsgID         string
	ThreadID      string
	Direction     string
	Sender        string
	Body          string
	ReplyTo       string
	Status        string
	CreatedAt     int64
	Kind          string
	ExpiresAt     int64
	Attempts      int64
	NextAttemptAt int64
}

type Owner struct {
	ID          string
	DisplayName string
	CreatedAt   int64
}

type PendingRequest struct {
	ID         string
	AccountID  string
	ContactFpr string
	Capability string
	Args       string
	TrustFlag  string
	Status     string
	Result     string
	CreatedAt  int64
	ExpiresAt  int64
	AnsweredAt pgtype.Int8
}

type RelayAllowlist struct {
	RecipientFpr string
	SenderFpr    string
	UpdatedAt    int64
}

type RelayQueue struct {
	ID           string
	RecipientFpr string
	SenderFpr    string
	MsgID        string
	Envelope     string
	SizeBytes    int64
	QueuedAt     int64
	ExpiresAt    int64
}

type RotationFanout struct {
	AccountID  string
	ContactFpr string
	NewFpr     string
	Status     string
	Attempts   int64
	LastError  string
	UpdatedAt  int64
}

type Session struct {
	ID        string
	OwnerID   string
	CreatedAt int64
	ExpiresAt int64
}

type Thread struct {
	ID          string
	AccountID   string
	ContactFpr  string
	Topic       string
	CreatedAt   int64
	LastAt      int64
	LastReadSeq int64
}

type Token struct {
	ID        string
	OwnerID   string
	Label     string
	Hash      []byte
	AccountID pgtype.Text
	CreatedAt int64
	RevokedAt pgtype.Int8
}
