// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"database/sql"
)

type Account struct {
	ID              string
	Slug            string
	DisplayName     string
	Algo            string
	Fingerprint     sql.NullString
	KeySealed       []byte
	Seal            string
	Status          string
	CreatedAt       int64
	RootFingerprint sql.NullString
	RootCert        []byte
	AcceptNewHosts  string
}

type AuditAnchor struct {
	ID                 int64
	ArchivedThroughSeq int64
	TerminalHash       string
	ArchivePath        string
	UpdatedAt          int64
}

type AuditArchiveRow struct {
	Seq  int64
	Hash string
}

type AuditEvent struct {
	Seq       int64
	Ts        int64
	AccountID sql.NullString
	ActorKind string
	ActorID   string
	Action    string
	Resource  string
	Outcome   string
	RequestID string
	Details   string
	PrevHash  string
	Hash      string
}

type Blob struct {
	AccountID string
	Hash      string
	Size      int64
	Mime      string
	Filename  string
	CreatedAt int64
}

type Catalog struct {
	ID            string
	IntegrationID string
	Version       int64
	Tools         string
	CreatedAt     int64
}

type Change struct {
	ID         int64
	AccountID  string
	Kind       string
	ThreadID   string
	ContactFpr string
	Ref        string
	At         int64
}

type Contact struct {
	ID               string
	AccountID        string
	Fingerprint      string
	Spki             []byte
	Status           string
	Preset           string
	Permissions      string
	TrustFlag        string
	DisplayName      string
	Card             string
	CreatedAt        int64
	PinnedAt         sql.NullInt64
	TheirPermissions string
	Petname          string
	InviteID         string
	Endpoint         string
	Leaf             []byte
	ChainSentKid     string
	RootCert         []byte
	EverActive       int64
	HandshakeDue     int64
	RequestedAt      sql.NullInt64
}

type Credential struct {
	ID         string
	OwnerID    string
	Kind       string
	Tag        string
	Data       []byte
	CreatedAt  int64
	LastUsedAt sql.NullInt64
}

type Exposure struct {
	ID             string
	IntegrationID  string
	Version        int64
	CatalogVersion int64
	Entries        string
	CreatedAt      int64
}

type FormerEndpoint struct {
	AccountID string
	Root      string
	Endpoint  string
	At        int64
}

type Idempotency struct {
	AccountID  string
	ContactFpr string
	MsgID      string
	Ack        string
	CreatedAt  int64
	ExpiresAt  sql.NullInt64
}

type Integration struct {
	ID        string
	AccountID string
	Slug      string
	Transport string
	Endpoint  string
	Command   string
	AuthKind  string
	Status    string
	CreatedAt int64
	UpdatedAt int64
	Secret    []byte
}

type Invite struct {
	ID          string
	AccountID   string
	TokenHash   []byte
	ExpiresAt   int64
	MaxUses     int64
	Uses        int64
	AutoAccept  int64
	Preset      string
	Permissions string
	Label       string
	RevokedAt   sql.NullInt64
	CreatedAt   int64
}

type Leaf struct {
	AccountID        string
	Kid              string
	Leaf             []byte
	KeySealed        []byte
	NotBefore        int64
	NotAfter         int64
	State            string
	Endpoint         string
	CreatedAt        int64
	RequestStateHash []byte
	WalletOrigin     string
	Moved            int64
}

type Lease struct {
	Name      string
	Holder    string
	TakenAt   int64
	ExpiresAt int64
}

type Membership struct {
	OwnerID   string
	AccountID string
	Role      string
}

type Message struct {
	Seq           int64
	ID            string
	AccountID     string
	ContactFpr    string
	MsgID         string
	ThreadID      string
	Direction     string
	Sender        string
	Body          string
	ReplyTo       string
	Status        string
	CreatedAt     int64
	Kind          string
	ExpiresAt     int64
	Attempts      int64
	NextAttemptAt int64
}

type MoveFanout struct {
	AccountID  string
	ContactFpr string
	LeafKid    string
	Status     string
	Attempts   int64
	LastError  string
	UpdatedAt  int64
}

type Owner struct {
	ID          string
	DisplayName string
	CreatedAt   int64
}

type OwnerPresence struct {
	ID     int64
	SeenAt int64
}

type PendingAddress struct {
	AccountID string
	Root      string
	Endpoint  string
	Leaf      []byte
	Why       string
	At        int64
	RootCert  []byte
}

type PendingRequest struct {
	ID         string
	AccountID  string
	ContactFpr string
	Capability string
	Args       string
	TrustFlag  string
	Status     string
	Result     string
	CreatedAt  int64
	ExpiresAt  int64
	AnsweredAt sql.NullInt64
}

type Session struct {
	ID        string
	OwnerID   string
	CreatedAt int64
	ExpiresAt int64
}

type Setting struct {
	Key       string
	Value     string
	Secret    bool
	UpdatedAt int64
}

type Thread struct {
	ID          string
	AccountID   string
	ContactFpr  string
	Topic       string
	CreatedAt   int64
	LastAt      int64
	LastReadSeq int64
}

type Token struct {
	ID        string
	OwnerID   string
	Label     string
	Hash      []byte
	AccountID sql.NullString
	CreatedAt int64
	RevokedAt sql.NullInt64
}

type Tombstone struct {
	AccountID string
	Root      string
	Leaf      []byte
	At        int64
}

type VacatedAddress struct {
	Endpoint string
	Slug     string
	UntilAt  int64
	At       int64
}
