// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pact20.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearChainSentKids = `-- name: ClearChainSentKids :execrows
UPDATE contacts SET chain_sent_kid = '' WHERE account_id = $1
`

// After a leaf install every contact must see the new chain once (PACT sec. 13.2).
func (q *Queries) ClearChainSentKids(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, clearChainSentKids, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLeavesByState = `-- name: DeleteLeavesByState :execrows
DELETE FROM leaves WHERE account_id = $1 AND state = $2
`

type DeleteLeavesByStateParams struct {
	AccountID string
	State     string
}

func (q *Queries) DeleteLeavesByState(ctx context.Context, arg DeleteLeavesByStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLeavesByState, arg.AccountID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingAddress = `-- name: DeletePendingAddress :execrows
DELETE FROM pending_addresses WHERE account_id = $1 AND root = $2
`

type DeletePendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeletePendingAddress(ctx context.Context, arg DeletePendingAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingAddress, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTombstone = `-- name: DeleteTombstone :execrows
DELETE FROM tombstones WHERE account_id = $1 AND root = $2
`

type DeleteTombstoneParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeleteTombstone(ctx context.Context, arg DeleteTombstoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTombstone, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingAddress = `-- name: GetPendingAddress :one
SELECT account_id, root, endpoint, leaf, why, at FROM pending_addresses WHERE account_id = $1 AND root = $2
`

type GetPendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) GetPendingAddress(ctx context.Context, arg GetPendingAddressParams) (PendingAddress, error) {
	row := q.db.QueryRow(ctx, getPendingAddress, arg.AccountID, arg.Root)
	var i PendingAddress
	err := row.Scan(
		&i.AccountID,
		&i.Root,
		&i.Endpoint,
		&i.Leaf,
		&i.Why,
		&i.At,
	)
	return i, err
}

const insertFormerEndpoint = `-- name: InsertFormerEndpoint :exec
INSERT INTO former_endpoints (account_id, root, endpoint, at) VALUES ($1, $2, $3, $4)
`

type InsertFormerEndpointParams struct {
	AccountID string
	Root      string
	Endpoint  string
	At        int64
}

func (q *Queries) InsertFormerEndpoint(ctx context.Context, arg InsertFormerEndpointParams) error {
	_, err := q.db.Exec(ctx, insertFormerEndpoint,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.At,
	)
	return err
}

const insertLeaf = `-- name: InsertLeaf :exec
INSERT INTO leaves (account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertLeafParams struct {
	AccountID string
	Kid       string
	Leaf      []byte
	KeySealed []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	CreatedAt int64
}

func (q *Queries) InsertLeaf(ctx context.Context, arg InsertLeafParams) error {
	_, err := q.db.Exec(ctx, insertLeaf,
		arg.AccountID,
		arg.Kid,
		arg.Leaf,
		arg.KeySealed,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.CreatedAt,
	)
	return err
}

const listFormerEndpoints = `-- name: ListFormerEndpoints :many
SELECT account_id, root, endpoint, at FROM former_endpoints WHERE account_id = $1 ORDER BY at, root, endpoint
`

func (q *Queries) ListFormerEndpoints(ctx context.Context, accountID string) ([]FormerEndpoint, error) {
	rows, err := q.db.Query(ctx, listFormerEndpoints, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormerEndpoint
	for rows.Next() {
		var i FormerEndpoint
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaves = `-- name: ListLeaves :many
SELECT account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at FROM leaves WHERE account_id = $1 ORDER BY created_at, kid
`

func (q *Queries) ListLeaves(ctx context.Context, accountID string) ([]Leaf, error) {
	rows, err := q.db.Query(ctx, listLeaves, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaf
	for rows.Next() {
		var i Leaf
		if err := rows.Scan(
			&i.AccountID,
			&i.Kid,
			&i.Leaf,
			&i.KeySealed,
			&i.NotBefore,
			&i.NotAfter,
			&i.State,
			&i.Endpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAddresses = `-- name: ListPendingAddresses :many
SELECT account_id, root, endpoint, leaf, why, at FROM pending_addresses WHERE account_id = $1 ORDER BY at, root
`

func (q *Queries) ListPendingAddresses(ctx context.Context, accountID string) ([]PendingAddress, error) {
	rows, err := q.db.Query(ctx, listPendingAddresses, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAddress
	for rows.Next() {
		var i PendingAddress
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.Leaf,
			&i.Why,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstones = `-- name: ListTombstones :many
SELECT account_id, root, leaf, at FROM tombstones WHERE account_id = $1 ORDER BY at, root
`

func (q *Queries) ListTombstones(ctx context.Context, accountID string) ([]Tombstone, error) {
	rows, err := q.db.Query(ctx, listTombstones, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tombstone
	for rows.Next() {
		var i Tombstone
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Leaf,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repinContactAddress = `-- name: RepinContactAddress :execrows
UPDATE contacts SET endpoint = $1, leaf = $2, spki = $3, pinned_at = $4 WHERE account_id = $5 AND fingerprint = $6
`

type RepinContactAddressParams struct {
	Endpoint    string
	Leaf        []byte
	Spki        []byte
	PinnedAt    pgtype.Int8
	AccountID   string
	Fingerprint string
}

// The 2.0 pin moves: a renewal at the pinned endpoint or an accepted new
// address replaces the leaf, its key and the endpoint; the root (the
// fingerprint column) never moves (PACT sec. 14.3, sec. 5.3).
func (q *Queries) RepinContactAddress(ctx context.Context, arg RepinContactAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, repinContactAddress,
		arg.Endpoint,
		arg.Leaf,
		arg.Spki,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireLeafKey = `-- name: RetireLeafKey :execrows
UPDATE leaves SET key_sealed = NULL, state = 'former' WHERE account_id = $1 AND kid = $2
`

type RetireLeafKeyParams struct {
	AccountID string
	Kid       string
}

// A superseded leaf past its not_after: the key is destroyed, the kid kept so
// an envelope still sealed to it is answered certificate_renewed (PACT sec. 14.4).
func (q *Queries) RetireLeafKey(ctx context.Context, arg RetireLeafKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireLeafKey, arg.AccountID, arg.Kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountHostPolicy = `-- name: SetAccountHostPolicy :execrows
UPDATE accounts SET accept_new_hosts = $1, accept_1x = $2 WHERE id = $3
`

type SetAccountHostPolicyParams struct {
	AcceptNewHosts string
	Accept1x       int64
	ID             string
}

func (q *Queries) SetAccountHostPolicy(ctx context.Context, arg SetAccountHostPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountHostPolicy, arg.AcceptNewHosts, arg.Accept1x, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountLeafKey = `-- name: SetAccountLeafKey :execrows
UPDATE accounts SET fingerprint = $1, key_sealed = $2, algo = $3 WHERE id = $4
`

type SetAccountLeafKeyParams struct {
	Fingerprint pgtype.Text
	KeySealed   []byte
	Algo        string
	ID          string
}

// Re-points the account at its CURRENT leaf key. SetAccountKey binds once and
// never moves; a leaf install moves it, keeping every fingerprint-keyed path
// (routing, audit, pins) on the key that signs and seals today.
func (q *Queries) SetAccountLeafKey(ctx context.Context, arg SetAccountLeafKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountLeafKey,
		arg.Fingerprint,
		arg.KeySealed,
		arg.Algo,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountProtocol = `-- name: SetAccountProtocol :execrows

UPDATE accounts SET protocol = $1, root_fingerprint = $2, root_cert = $3 WHERE id = $4
`

type SetAccountProtocolParams struct {
	Protocol        int64
	RootFingerprint pgtype.Text
	RootCert        []byte
	ID              string
}

// PACT 2.0 state (SPEC sec. 2, sec. 14; migration 0027): the account's root and leaf
// ledger, 2.0 pins, the removal tombstone, former endpoints, and the
// addresses awaiting the owner under `accept_new_hosts = ask`.
func (q *Queries) SetAccountProtocol(ctx context.Context, arg SetAccountProtocolParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountProtocol,
		arg.Protocol,
		arg.RootFingerprint,
		arg.RootCert,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContactChainSentKid = `-- name: SetContactChainSentKid :execrows
UPDATE contacts SET chain_sent_kid = $1 WHERE account_id = $2 AND fingerprint = $3
`

type SetContactChainSentKidParams struct {
	ChainSentKid string
	AccountID    string
	Fingerprint  string
}

func (q *Queries) SetContactChainSentKid(ctx context.Context, arg SetContactChainSentKidParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContactChainSentKid, arg.ChainSentKid, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLeaf = `-- name: UpdateLeaf :execrows
UPDATE leaves SET leaf = $1, not_before = $2, not_after = $3, state = $4, endpoint = $5 WHERE account_id = $6 AND kid = $7
`

type UpdateLeafParams struct {
	Leaf      []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	AccountID string
	Kid       string
}

func (q *Queries) UpdateLeaf(ctx context.Context, arg UpdateLeafParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLeaf,
		arg.Leaf,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.AccountID,
		arg.Kid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upgradeContactPin = `-- name: UpgradeContactPin :execrows
UPDATE contacts SET fingerprint = $1, protocol = 2, endpoint = $2, leaf = $3, spki = $4, pinned_at = $5 WHERE account_id = $6 AND fingerprint = $7
`

type UpgradeContactPinParams struct {
	Fingerprint   string
	Endpoint      string
	Leaf          []byte
	Spki          []byte
	PinnedAt      pgtype.Int8
	AccountID     string
	Fingerprint_2 string
}

// Appendix C row 6: a 1.x pin of key K, met by a chain whose leaf key is K,
// becomes a 2.0 pin of the root with no human step.
func (q *Queries) UpgradeContactPin(ctx context.Context, arg UpgradeContactPinParams) (int64, error) {
	result, err := q.db.Exec(ctx, upgradeContactPin,
		arg.Fingerprint,
		arg.Endpoint,
		arg.Leaf,
		arg.Spki,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPendingAddress = `-- name: UpsertPendingAddress :exec
INSERT INTO pending_addresses (account_id, root, endpoint, leaf, why, at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, root) DO UPDATE SET endpoint = excluded.endpoint, leaf = excluded.leaf, why = excluded.why, at = excluded.at
`

type UpsertPendingAddressParams struct {
	AccountID string
	Root      string
	Endpoint  string
	Leaf      []byte
	Why       string
	At        int64
}

func (q *Queries) UpsertPendingAddress(ctx context.Context, arg UpsertPendingAddressParams) error {
	_, err := q.db.Exec(ctx, upsertPendingAddress,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.Leaf,
		arg.Why,
		arg.At,
	)
	return err
}

const upsertTombstone = `-- name: UpsertTombstone :exec
INSERT INTO tombstones (account_id, root, leaf, at) VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, root) DO UPDATE SET leaf = excluded.leaf, at = excluded.at
`

type UpsertTombstoneParams struct {
	AccountID string
	Root      string
	Leaf      []byte
	At        int64
}

func (q *Queries) UpsertTombstone(ctx context.Context, arg UpsertTombstoneParams) error {
	_, err := q.db.Exec(ctx, upsertTombstone,
		arg.AccountID,
		arg.Root,
		arg.Leaf,
		arg.At,
	)
	return err
}
