// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presence.sql

package pgdb

import (
	"context"
)

const ownerPresenceSeenAt = `-- name: OwnerPresenceSeenAt :one
SELECT seen_at FROM owner_presence WHERE id = 1
`

func (q *Queries) OwnerPresenceSeenAt(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, ownerPresenceSeenAt)
	var seen_at int64
	err := row.Scan(&seen_at)
	return seen_at, err
}

const touchOwnerPresence = `-- name: TouchOwnerPresence :exec
INSERT INTO owner_presence (id, seen_at) VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET seen_at = excluded.seen_at
`

func (q *Queries) TouchOwnerPresence(ctx context.Context, seenAt int64) error {
	_, err := q.db.Exec(ctx, touchOwnerPresence, seenAt)
	return err
}
