// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changes.sql

package sqlitedb

import (
	"context"
)

const accountChangesAfter = `-- name: AccountChangesAfter :many
SELECT id, account_id, kind, thread_id, contact_fpr, ref, at FROM changes WHERE account_id = ? AND id > ? ORDER BY id LIMIT ?
`

type AccountChangesAfterParams struct {
	AccountID string
	ID        int64
	Limit     int64
}

func (q *Queries) AccountChangesAfter(ctx context.Context, arg AccountChangesAfterParams) ([]Change, error) {
	rows, err := q.db.QueryContext(ctx, accountChangesAfter, arg.AccountID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.ThreadID,
			&i.ContactFpr,
			&i.Ref,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesAfter = `-- name: ChangesAfter :many
SELECT id, account_id, kind, thread_id, contact_fpr, ref, at FROM changes WHERE id > ? ORDER BY id LIMIT ?
`

type ChangesAfterParams struct {
	ID    int64
	Limit int64
}

func (q *Queries) ChangesAfter(ctx context.Context, arg ChangesAfterParams) ([]Change, error) {
	rows, err := q.db.QueryContext(ctx, changesAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Kind,
			&i.ThreadID,
			&i.ContactFpr,
			&i.Ref,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChangesBefore = `-- name: DeleteChangesBefore :execrows
DELETE FROM changes WHERE at < ?
`

func (q *Queries) DeleteChangesBefore(ctx context.Context, at int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChangesBefore, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChangesByAccount = `-- name: DeleteChangesByAccount :execrows
DELETE FROM changes WHERE account_id = ?
`

// An identity leaving (HDTP sec. 9): its changes go with it.
func (q *Queries) DeleteChangesByAccount(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChangesByAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (account_id, kind, thread_id, contact_fpr, ref, at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertChangeParams struct {
	AccountID  string
	Kind       string
	ThreadID   string
	ContactFpr string
	Ref        string
	At         int64
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChange,
		arg.AccountID,
		arg.Kind,
		arg.ThreadID,
		arg.ContactFpr,
		arg.Ref,
		arg.At,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastChangeID = `-- name: LastChangeID :one
SELECT CAST(COALESCE(MAX(id), 0) AS INTEGER) AS id FROM changes
`

func (q *Queries) LastChangeID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastChangeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const oldestChangeID = `-- name: OldestChangeID :one
SELECT CAST(COALESCE(MIN(id), 0) AS INTEGER) AS id FROM changes
`

func (q *Queries) OldestChangeID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, oldestChangeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
