// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const clearContactHandshake = `-- name: ClearContactHandshake :execrows
UPDATE contacts SET handshake_due = 0 WHERE account_id = ? AND fingerprint = ?
`

type ClearContactHandshakeParams struct {
	AccountID   string
	Fingerprint string
}

// The campaign has told this contact: it is owed nothing more (sec. 9.2).
func (q *Queries) ClearContactHandshake(ctx context.Context, arg ClearContactHandshakeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearContactHandshake, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE account_id = ? AND fingerprint = ?
`

type DeleteContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContact, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteContactInStatus = `-- name: DeleteContactInStatus :execrows
DELETE FROM contacts WHERE account_id = ? AND fingerprint = ? AND status = ?
`

type DeleteContactInStatusParams struct {
	AccountID   string
	Fingerprint string
	Status      string
}

// Unblock's forget: only while the row is still the blocked row the decision read.
func (q *Queries) DeleteContactInStatus(ctx context.Context, arg DeleteContactInStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContactInStatus, arg.AccountID, arg.Fingerprint, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredPendingContacts = `-- name: DeleteExpiredPendingContacts :many
DELETE FROM contacts
WHERE account_id = ? AND status IN ('pending_in', 'pending_out') AND created_at < ?
RETURNING fingerprint, status
`

type DeleteExpiredPendingContactsParams struct {
	AccountID string
	CreatedAt int64
}

type DeleteExpiredPendingContactsRow struct {
	Fingerprint string
	Status      string
}

// An unanswered request, ours or theirs, expires (SPEC sec. 9.1): the relationship returns to
// none. The status is in the statement, so a request approved between a read and this delete
// is not the one removed.
func (q *Queries) DeleteExpiredPendingContacts(ctx context.Context, arg DeleteExpiredPendingContactsParams) ([]DeleteExpiredPendingContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredPendingContacts, arg.AccountID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteExpiredPendingContactsRow
	for rows.Next() {
		var i DeleteExpiredPendingContactsRow
		if err := rows.Scan(&i.Fingerprint, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContact = `-- name: GetContact :one
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, endpoint, leaf, chain_sent_kid, root_cert, ever_active, handshake_due FROM contacts WHERE account_id = ? AND fingerprint = ?
`

type GetContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, arg.AccountID, arg.Fingerprint)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Fingerprint,
		&i.Spki,
		&i.Status,
		&i.Preset,
		&i.Permissions,
		&i.TrustFlag,
		&i.DisplayName,
		&i.Card,
		&i.CreatedAt,
		&i.PinnedAt,
		&i.TheirPermissions,
		&i.Petname,
		&i.InviteID,
		&i.Endpoint,
		&i.Leaf,
		&i.ChainSentKid,
		&i.RootCert,
		&i.EverActive,
		&i.HandshakeDue,
	)
	return i, err
}

const importContact = `-- name: ImportContact :exec
INSERT INTO contacts (id, account_id, fingerprint, spki, status, preset, permissions, their_permissions, trust_flag, display_name, petname, card, created_at, pinned_at, endpoint, leaf, root_cert, ever_active, handshake_due)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
`

type ImportContactParams struct {
	ID               string
	AccountID        string
	Fingerprint      string
	Spki             []byte
	Status           string
	Preset           string
	Permissions      string
	TheirPermissions string
	TrustFlag        string
	DisplayName      string
	Petname          string
	Card             string
	CreatedAt        int64
	PinnedAt         sql.NullInt64
	Endpoint         string
	Leaf             []byte
	RootCert         []byte
	EverActive       int64
}

// A contact arriving in an export (SPEC sec. 3.10): every column an export carries, in one
// statement, and none it does not. invite_id stays empty because invites do not travel, and
// chain_sent_kid stays empty because it records which of THIS host's leaves the contact has
// seen - and this host has not been issued one yet. handshake_due is set: the contact is owed
// this host's handshake once its next leaf is installed (sec. 9.2).
func (q *Queries) ImportContact(ctx context.Context, arg ImportContactParams) error {
	_, err := q.db.ExecContext(ctx, importContact,
		arg.ID,
		arg.AccountID,
		arg.Fingerprint,
		arg.Spki,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.TheirPermissions,
		arg.TrustFlag,
		arg.DisplayName,
		arg.Petname,
		arg.Card,
		arg.CreatedAt,
		arg.PinnedAt,
		arg.Endpoint,
		arg.Leaf,
		arg.RootCert,
		arg.EverActive,
	)
	return err
}

const importContactPin = `-- name: ImportContactPin :execrows
UPDATE contacts SET endpoint = ?, leaf = ?, spki = ?, root_cert = COALESCE(?, root_cert), handshake_due = 1
WHERE account_id = ? AND fingerprint = ? AND (leaf IS NULL OR length(leaf) = 0)
`

type ImportContactPinParams struct {
	Endpoint    string
	Leaf        []byte
	Spki        []byte
	RootCert    []byte
	AccountID   string
	Fingerprint string
}

// An import merging into an identity this host already holds (SPEC sec. 3.10, PACT sec. 9.2):
// a contact held with no leaf takes the pin a file carries - the endpoint, and the leaf that
// validated there - and is owed this host's handshake. A contact held WITH a leaf is never
// written: a pin this host validated itself is not replaced by one from a file (sec. 14.5).
func (q *Queries) ImportContactPin(ctx context.Context, arg ImportContactPinParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, importContactPin,
		arg.Endpoint,
		arg.Leaf,
		arg.Spki,
		arg.RootCert,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertContact = `-- name: InsertContact :exec
INSERT INTO contacts (id, account_id, fingerprint, spki, status, preset, permissions, display_name, card, created_at, pinned_at, invite_id, endpoint, leaf, chain_sent_kid, root_cert, ever_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertContactParams struct {
	ID           string
	AccountID    string
	Fingerprint  string
	Spki         []byte
	Status       string
	Preset       string
	Permissions  string
	DisplayName  string
	Card         string
	CreatedAt    int64
	PinnedAt     sql.NullInt64
	InviteID     string
	Endpoint     string
	Leaf         []byte
	ChainSentKid string
	RootCert     []byte
	EverActive   int64
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.ExecContext(ctx, insertContact,
		arg.ID,
		arg.AccountID,
		arg.Fingerprint,
		arg.Spki,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.DisplayName,
		arg.Card,
		arg.CreatedAt,
		arg.PinnedAt,
		arg.InviteID,
		arg.Endpoint,
		arg.Leaf,
		arg.ChainSentKid,
		arg.RootCert,
		arg.EverActive,
	)
	return err
}

const listContacts = `-- name: ListContacts :many
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, endpoint, leaf, chain_sent_kid, root_cert, ever_active, handshake_due FROM contacts WHERE account_id = ? ORDER BY created_at, id
`

func (q *Queries) ListContacts(ctx context.Context, accountID string) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContacts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Fingerprint,
			&i.Spki,
			&i.Status,
			&i.Preset,
			&i.Permissions,
			&i.TrustFlag,
			&i.DisplayName,
			&i.Card,
			&i.CreatedAt,
			&i.PinnedAt,
			&i.TheirPermissions,
			&i.Petname,
			&i.InviteID,
			&i.Endpoint,
			&i.Leaf,
			&i.ChainSentKid,
			&i.RootCert,
			&i.EverActive,
			&i.HandshakeDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveContactStatus = `-- name: MoveContactStatus :execrows
UPDATE contacts SET status = ?1,
    ever_active = CASE WHEN ?1 = 'active' THEN 1 ELSE ever_active END
WHERE account_id = ?2 AND fingerprint = ?3 AND status = ?4
`

type MoveContactStatusParams struct {
	Status      string
	AccountID   string
	Fingerprint string
	Status_2    string
}

// The owner's decisions (approve, reject, block, unblock): the move happens only from the status
// the decision was taken on, so a row that changed between the read and this write (a redeem over
// a pending request, the expiry sweep) is not overwritten. Zero rows means it changed.
func (q *Queries) MoveContactStatus(ctx context.Context, arg MoveContactStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveContactStatus,
		arg.Status,
		arg.AccountID,
		arg.Fingerprint,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const redeemOverPendingContact = `-- name: RedeemOverPendingContact :execrows
UPDATE contacts SET status = ?1,
    ever_active = CASE WHEN ?1 = 'active' THEN 1 ELSE ever_active END,
    preset = ?2, permissions = ?3, invite_id = ?4,
    display_name = ?5, card = ?6, spki = ?7,
    endpoint = ?8, leaf = ?9, root_cert = COALESCE(?10, root_cert)
WHERE account_id = ?11 AND fingerprint = ?12 AND status = 'pending_in'
`

type RedeemOverPendingContactParams struct {
	Status      string
	Preset      string
	Permissions string
	InviteID    string
	DisplayName string
	Card        string
	Spki        []byte
	Endpoint    string
	Leaf        []byte
	RootCert    []byte
	AccountID   string
	Fingerprint string
}

// A request still awaiting the owner (pending_in) redeems one of the owner's invites: the row
// takes the invite's status and grant and the pin this call proved (a sealed call proves no root
// certificate, and then the one held is kept). Guarded by the status it expects, so a row the
// owner decided on meanwhile is not overwritten.
func (q *Queries) RedeemOverPendingContact(ctx context.Context, arg RedeemOverPendingContactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, redeemOverPendingContact,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.InviteID,
		arg.DisplayName,
		arg.Card,
		arg.Spki,
		arg.Endpoint,
		arg.Leaf,
		arg.RootCert,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContactAccepted = `-- name: SetContactAccepted :execrows
UPDATE contacts SET status = 'active', ever_active = 1, card = ?, their_permissions = ?, pinned_at = ?
WHERE account_id = ? AND fingerprint = ?
`

type SetContactAcceptedParams struct {
	Card             string
	TheirPermissions string
	PinnedAt         sql.NullInt64
	AccountID        string
	Fingerprint      string
}

func (q *Queries) SetContactAccepted(ctx context.Context, arg SetContactAcceptedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setContactAccepted,
		arg.Card,
		arg.TheirPermissions,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactCard = `-- name: UpdateContactCard :execrows
UPDATE contacts SET card = ?, display_name = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactCardParams struct {
	Card        string
	DisplayName string
	AccountID   string
	Fingerprint string
}

// The periodic contact sync's write: a re-fetched card whose signature
// verified under the PINNED key. The key itself never moves here - rotation
// is update_contact's job - so only the card text and the display name change.
func (q *Queries) UpdateContactCard(ctx context.Context, arg UpdateContactCardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactCard,
		arg.Card,
		arg.DisplayName,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactPermissions = `-- name: UpdateContactPermissions :execrows
UPDATE contacts SET permissions = ?, preset = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactPermissionsParams struct {
	Permissions string
	Preset      string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactPermissions(ctx context.Context, arg UpdateContactPermissionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactPermissions,
		arg.Permissions,
		arg.Preset,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactPetname = `-- name: UpdateContactPetname :execrows
UPDATE contacts SET petname = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactPetnameParams struct {
	Petname     string
	AccountID   string
	Fingerprint string
}

// The owner's own name for a contact. Local by construction: no peer surface
// reaches it, which is the point - display_name is the contact's own claim.
func (q *Queries) UpdateContactPetname(ctx context.Context, arg UpdateContactPetnameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactPetname, arg.Petname, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactStatus = `-- name: UpdateContactStatus :execrows
UPDATE contacts SET status = ?1,
    ever_active = CASE WHEN ?1 = 'active' THEN 1 ELSE ever_active END
WHERE account_id = ?2 AND fingerprint = ?3
`

type UpdateContactStatusParams struct {
	Status      string
	AccountID   string
	Fingerprint string
}

// Moving a row to active records that it was ever active (migration 0039); nothing clears it.
func (q *Queries) UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactStatus, arg.Status, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactTrust = `-- name: UpdateContactTrust :execrows
UPDATE contacts SET trust_flag = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactTrustParams struct {
	TrustFlag   string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactTrust(ctx context.Context, arg UpdateContactTrustParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactTrust, arg.TrustFlag, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
