// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE account_id = ? AND fingerprint = ?
`

type DeleteContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContact, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContact = `-- name: GetContact :one
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, protocol, endpoint, leaf, chain_sent_kid FROM contacts WHERE account_id = ? AND fingerprint = ?
`

type GetContactParams struct {
	AccountID   string
	Fingerprint string
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, arg.AccountID, arg.Fingerprint)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Fingerprint,
		&i.Spki,
		&i.Status,
		&i.Preset,
		&i.Permissions,
		&i.TrustFlag,
		&i.DisplayName,
		&i.Card,
		&i.CreatedAt,
		&i.PinnedAt,
		&i.TheirPermissions,
		&i.Petname,
		&i.InviteID,
		&i.Protocol,
		&i.Endpoint,
		&i.Leaf,
		&i.ChainSentKid,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :exec
INSERT INTO contacts (id, account_id, fingerprint, spki, status, preset, permissions, display_name, card, created_at, pinned_at, invite_id, protocol, endpoint, leaf, chain_sent_kid)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertContactParams struct {
	ID           string
	AccountID    string
	Fingerprint  string
	Spki         []byte
	Status       string
	Preset       string
	Permissions  string
	DisplayName  string
	Card         string
	CreatedAt    int64
	PinnedAt     sql.NullInt64
	InviteID     string
	Protocol     int64
	Endpoint     string
	Leaf         []byte
	ChainSentKid string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.ExecContext(ctx, insertContact,
		arg.ID,
		arg.AccountID,
		arg.Fingerprint,
		arg.Spki,
		arg.Status,
		arg.Preset,
		arg.Permissions,
		arg.DisplayName,
		arg.Card,
		arg.CreatedAt,
		arg.PinnedAt,
		arg.InviteID,
		arg.Protocol,
		arg.Endpoint,
		arg.Leaf,
		arg.ChainSentKid,
	)
	return err
}

const listContacts = `-- name: ListContacts :many
SELECT id, account_id, fingerprint, spki, status, preset, permissions, trust_flag, display_name, card, created_at, pinned_at, their_permissions, petname, invite_id, protocol, endpoint, leaf, chain_sent_kid FROM contacts WHERE account_id = ? ORDER BY created_at, id
`

func (q *Queries) ListContacts(ctx context.Context, accountID string) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContacts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Fingerprint,
			&i.Spki,
			&i.Status,
			&i.Preset,
			&i.Permissions,
			&i.TrustFlag,
			&i.DisplayName,
			&i.Card,
			&i.CreatedAt,
			&i.PinnedAt,
			&i.TheirPermissions,
			&i.Petname,
			&i.InviteID,
			&i.Protocol,
			&i.Endpoint,
			&i.Leaf,
			&i.ChainSentKid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactPermissions = `-- name: UpdateContactPermissions :execrows
UPDATE contacts SET permissions = ?, preset = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactPermissionsParams struct {
	Permissions string
	Preset      string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactPermissions(ctx context.Context, arg UpdateContactPermissionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactPermissions,
		arg.Permissions,
		arg.Preset,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactStatus = `-- name: UpdateContactStatus :execrows
UPDATE contacts SET status = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactStatusParams struct {
	Status      string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactStatus, arg.Status, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactTrust = `-- name: UpdateContactTrust :execrows
UPDATE contacts SET trust_flag = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactTrustParams struct {
	TrustFlag   string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactTrust(ctx context.Context, arg UpdateContactTrustParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactTrust, arg.TrustFlag, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContactAccepted = `-- name: SetContactAccepted :execrows
UPDATE contacts SET status = 'active', card = ?, their_permissions = ?, pinned_at = ?
WHERE account_id = ? AND fingerprint = ?
`

type SetContactAcceptedParams struct {
	Card             string
	TheirPermissions string
	PinnedAt         sql.NullInt64
	AccountID        string
	Fingerprint      string
}

func (q *Queries) SetContactAccepted(ctx context.Context, arg SetContactAcceptedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setContactAccepted,
		arg.Card, arg.TheirPermissions, arg.PinnedAt, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactCard = `-- name: UpdateContactCard :execrows
UPDATE contacts SET card = ?, display_name = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactCardParams struct {
	Card        string
	DisplayName string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactCard(ctx context.Context, arg UpdateContactCardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactCard, arg.Card, arg.DisplayName, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContactPetname = `-- name: UpdateContactPetname :execrows
UPDATE contacts SET petname = ? WHERE account_id = ? AND fingerprint = ?
`

type UpdateContactPetnameParams struct {
	Petname     string
	AccountID   string
	Fingerprint string
}

func (q *Queries) UpdateContactPetname(ctx context.Context, arg UpdateContactPetnameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContactPetname, arg.Petname, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
