// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countCredentialsByKind = `-- name: CountCredentialsByKind :one
SELECT COUNT(*) FROM credentials WHERE kind = ?
`

func (q *Queries) CountCredentialsByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCredentialsByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuditEventsThrough = `-- name: DeleteAuditEventsThrough :execrows
DELETE FROM audit_events WHERE seq <= ?
`

func (q *Queries) DeleteAuditEventsThrough(ctx context.Context, seq int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditEventsThrough, seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCredentialIfNotLast = `-- name: DeleteCredentialIfNotLast :execrows
DELETE FROM credentials WHERE credentials.id = ? AND credentials.kind = ?
  AND (SELECT COUNT(*) FROM credentials WHERE credentials.kind = ?) > 1
`

type DeleteCredentialIfNotLastParams struct {
	ID     string
	Kind   string
	Kind_2 string
}

// DeleteCredentialIfNotLast removes a credential only while another of the same
// kind survives - the guard that stops the owner locking themselves out. The
// count and the delete are ONE statement so two concurrent removals cannot both
// observe "there are two" and both delete.
func (q *Queries) DeleteCredentialIfNotLast(ctx context.Context, arg DeleteCredentialIfNotLastParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCredentialIfNotLast, arg.ID, arg.Kind, arg.Kind_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships WHERE owner_id = ? AND account_id = ?
`

type DeleteMembershipParams struct {
	OwnerID   string
	AccountID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMembership, arg.OwnerID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOwner = `-- name: DeleteOwner :execrows
DELETE FROM owners WHERE id = ?
`

func (q *Queries) DeleteOwner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOwner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, slug, display_name, algo, fingerprint, key_sealed, seal, status, created_at, protocol, root_fingerprint, root_cert, accept_new_hosts, accept_1x FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Algo,
		&i.Fingerprint,
		&i.KeySealed,
		&i.Seal,
		&i.Status,
		&i.CreatedAt,
		&i.Protocol,
		&i.RootFingerprint,
		&i.RootCert,
		&i.AcceptNewHosts,
		&i.Accept1x,
	)
	return i, err
}

const getAccountBySlug = `-- name: GetAccountBySlug :one
SELECT id, slug, display_name, algo, fingerprint, key_sealed, seal, status, created_at, protocol, root_fingerprint, root_cert, accept_new_hosts, accept_1x FROM accounts WHERE slug = ?
`

func (q *Queries) GetAccountBySlug(ctx context.Context, slug string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountBySlug, slug)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Algo,
		&i.Fingerprint,
		&i.KeySealed,
		&i.Seal,
		&i.Status,
		&i.CreatedAt,
		&i.Protocol,
		&i.RootFingerprint,
		&i.RootCert,
		&i.AcceptNewHosts,
		&i.Accept1x,
	)
	return i, err
}

const getAuditAnchor = `-- name: GetAuditAnchor :one
SELECT id, archived_through_seq, terminal_hash, archive_path, updated_at FROM audit_anchor WHERE id = 1
`

func (q *Queries) GetAuditAnchor(ctx context.Context) (AuditAnchor, error) {
	row := q.db.QueryRowContext(ctx, getAuditAnchor)
	var i AuditAnchor
	err := row.Scan(
		&i.ID,
		&i.ArchivedThroughSeq,
		&i.TerminalHash,
		&i.ArchivePath,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT id, display_name, created_at FROM owners WHERE id = ?
`

func (q *Queries) GetOwner(ctx context.Context, id string) (Owner, error) {
	row := q.db.QueryRowContext(ctx, getOwner, id)
	var i Owner
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, owner_id, created_at, expires_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, owner_id, label, hash, account_id, created_at, revoked_at FROM tokens WHERE hash = ?
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash []byte) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Label,
		&i.Hash,
		&i.AccountID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, slug, display_name, algo, created_at) VALUES (?, ?, ?, ?, ?)
`

type InsertAccountParams struct {
	ID          string
	Slug        string
	DisplayName string
	Algo        string
	CreatedAt   int64
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Algo,
		arg.CreatedAt,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (seq, ts, account_id, actor_kind, actor_id, action, resource, outcome, request_id, details, prev_hash, hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	Seq       int64
	Ts        int64
	AccountID sql.NullString
	ActorKind string
	ActorID   string
	Action    string
	Resource  string
	Outcome   string
	RequestID string
	Details   string
	PrevHash  string
	Hash      string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.Seq,
		arg.Ts,
		arg.AccountID,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.Outcome,
		arg.RequestID,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (id, owner_id, kind, tag, data, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCredentialParams struct {
	ID        string
	OwnerID   string
	Kind      string
	Tag       string
	Data      []byte
	CreatedAt int64
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertCredential,
		arg.ID,
		arg.OwnerID,
		arg.Kind,
		arg.Tag,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO memberships (owner_id, account_id, role) VALUES (?, ?, ?)
`

type InsertMembershipParams struct {
	OwnerID   string
	AccountID string
	Role      string
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.ExecContext(ctx, insertMembership, arg.OwnerID, arg.AccountID, arg.Role)
	return err
}

const insertOwner = `-- name: InsertOwner :exec
INSERT INTO owners (id, display_name, created_at) VALUES (?, ?, ?)
`

type InsertOwnerParams struct {
	ID          string
	DisplayName string
	CreatedAt   int64
}

func (q *Queries) InsertOwner(ctx context.Context, arg InsertOwnerParams) error {
	_, err := q.db.ExecContext(ctx, insertOwner, arg.ID, arg.DisplayName, arg.CreatedAt)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, owner_id, created_at, expires_at) VALUES (?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID        string
	OwnerID   string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.OwnerID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO tokens (id, owner_id, label, hash, account_id, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTokenParams struct {
	ID        string
	OwnerID   string
	Label     string
	Hash      []byte
	AccountID sql.NullString
	CreatedAt int64
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertToken,
		arg.ID,
		arg.OwnerID,
		arg.Label,
		arg.Hash,
		arg.AccountID,
		arg.CreatedAt,
	)
	return err
}

const lastAuditEvent = `-- name: LastAuditEvent :one
SELECT seq, ts, account_id, actor_kind, actor_id, "action", resource, outcome, request_id, details, prev_hash, hash FROM audit_events ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LastAuditEvent(ctx context.Context) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, lastAuditEvent)
	var i AuditEvent
	err := row.Scan(
		&i.Seq,
		&i.Ts,
		&i.AccountID,
		&i.ActorKind,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.Outcome,
		&i.RequestID,
		&i.Details,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, slug, display_name, algo, fingerprint, key_sealed, seal, status, created_at, protocol, root_fingerprint, root_cert, accept_new_hosts, accept_1x FROM accounts ORDER BY created_at, id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Algo,
			&i.Fingerprint,
			&i.KeySealed,
			&i.Seal,
			&i.Status,
			&i.CreatedAt,
			&i.Protocol,
			&i.RootFingerprint,
			&i.RootCert,
			&i.AcceptNewHosts,
			&i.Accept1x,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT seq, ts, account_id, actor_kind, actor_id, "action", resource, outcome, request_id, details, prev_hash, hash FROM audit_events ORDER BY seq
`

func (q *Queries) ListAuditEvents(ctx context.Context) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.AccountID,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RequestID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByActor = `-- name: ListAuditEventsByActor :many
SELECT seq, ts, account_id, actor_kind, actor_id, "action", resource, outcome, request_id, details, prev_hash, hash FROM audit_events WHERE actor_id = ? ORDER BY seq
`

func (q *Queries) ListAuditEventsByActor(ctx context.Context, actorID string) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.AccountID,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RequestID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT seq, ts, account_id, actor_kind, actor_id, "action", resource, outcome, request_id, details, prev_hash, hash FROM audit_events
WHERE (?1 = '' OR actor_id = ?1)
  AND (?2 = '' OR account_id = ?2 OR account_id IS NULL OR account_id = '')
ORDER BY seq DESC LIMIT ?3
`

type ListAuditEventsPageParams struct {
	Column1 interface{}
	Column2 interface{}
	Limit   int64
}

// The portal reads the trail from the present backwards and never needs all of
// it. ListAuditEvents stays ascending because that is the order the hash chain
// must be VERIFIED in; this is the reading order: newest first and bounded.
//
// Both filters are optional and empty means "any". The account filter keeps the
// node's own rows, which belong to no account: a listener starting or an owner
// signing in is a fact about the node, not about anybody's identity. account_id
// is nullable, and a row with no account arrives as NULL, not as ”.
func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsPage, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.AccountID,
			&i.ActorKind,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.Outcome,
			&i.RequestID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByKind = `-- name: ListCredentialsByKind :many
SELECT id, owner_id, kind, tag, data, created_at, last_used_at FROM credentials WHERE kind = ? ORDER BY created_at, id
`

func (q *Queries) ListCredentialsByKind(ctx context.Context, kind string) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Tag,
			&i.Data,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByOwner = `-- name: ListMembershipsByOwner :many
SELECT owner_id, account_id, role FROM memberships WHERE owner_id = ? ORDER BY account_id
`

func (q *Queries) ListMembershipsByOwner(ctx context.Context, ownerID string) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(&i.OwnerID, &i.AccountID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwners = `-- name: ListOwners :many
SELECT id, display_name, created_at FROM owners ORDER BY created_at, id
`

func (q *Queries) ListOwners(ctx context.Context) ([]Owner, error) {
	rows, err := q.db.QueryContext(ctx, listOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Owner
	for rows.Next() {
		var i Owner
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRotationFanout = `-- name: ListRotationFanout :many
SELECT account_id, contact_fpr, new_fpr, status, attempts, last_error, updated_at, kind FROM rotation_fanout WHERE account_id = ? ORDER BY contact_fpr
`

func (q *Queries) ListRotationFanout(ctx context.Context, accountID string) ([]RotationFanout, error) {
	rows, err := q.db.QueryContext(ctx, listRotationFanout, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RotationFanout
	for rows.Next() {
		var i RotationFanout
		if err := rows.Scan(
			&i.AccountID,
			&i.ContactFpr,
			&i.NewFpr,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.UpdatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, secret, updated_at FROM settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Secret,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, owner_id, label, hash, account_id, created_at, revoked_at FROM tokens ORDER BY created_at, id
`

func (q *Queries) ListTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Label,
			&i.Hash,
			&i.AccountID,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value, secret, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, secret = excluded.secret, updated_at = excluded.updated_at
`

type PutSettingParams struct {
	Key       string
	Value     string
	Secret    int64
	UpdatedAt int64
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting,
		arg.Key,
		arg.Value,
		arg.Secret,
		arg.UpdatedAt,
	)
	return err
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE tokens SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt sql.NullInt64
	ID        string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountKey = `-- name: SetAccountKey :execrows
UPDATE accounts SET fingerprint = ?, key_sealed = ? WHERE id = ? AND fingerprint IS NULL
`

type SetAccountKeyParams struct {
	Fingerprint sql.NullString
	KeySealed   []byte
	ID          string
}

func (q *Queries) SetAccountKey(ctx context.Context, arg SetAccountKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountKey, arg.Fingerprint, arg.KeySealed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAuditAnchor = `-- name: SetAuditAnchor :exec
INSERT INTO audit_anchor (id, archived_through_seq, terminal_hash, archive_path, updated_at)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET archived_through_seq = excluded.archived_through_seq,
    terminal_hash = excluded.terminal_hash, archive_path = excluded.archive_path,
    updated_at = excluded.updated_at
`

type SetAuditAnchorParams struct {
	ArchivedThroughSeq int64
	TerminalHash       string
	ArchivePath        string
	UpdatedAt          int64
}

func (q *Queries) SetAuditAnchor(ctx context.Context, arg SetAuditAnchorParams) error {
	_, err := q.db.ExecContext(ctx, setAuditAnchor,
		arg.ArchivedThroughSeq,
		arg.TerminalHash,
		arg.ArchivePath,
		arg.UpdatedAt,
	)
	return err
}

const updateAccountSeal = `-- name: UpdateAccountSeal :execrows
UPDATE accounts SET seal = ? WHERE id = ?
`

type UpdateAccountSealParams struct {
	Seal string
	ID   string
}

func (q *Queries) UpdateAccountSeal(ctx context.Context, arg UpdateAccountSealParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccountSeal, arg.Seal, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertRotationFanout = `-- name: UpsertRotationFanout :exec
INSERT INTO rotation_fanout (account_id, contact_fpr, new_fpr, status, attempts, last_error, updated_at, kind)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (account_id, contact_fpr) DO UPDATE SET
  new_fpr = excluded.new_fpr, status = excluded.status, attempts = excluded.attempts,
  last_error = excluded.last_error, updated_at = excluded.updated_at, kind = excluded.kind
`

type UpsertRotationFanoutParams struct {
	AccountID  string
	ContactFpr string
	NewFpr     string
	Status     string
	Attempts   int64
	LastError  string
	UpdatedAt  int64
	Kind       string
}

func (q *Queries) UpsertRotationFanout(ctx context.Context, arg UpsertRotationFanoutParams) error {
	_, err := q.db.ExecContext(ctx, upsertRotationFanout,
		arg.AccountID,
		arg.ContactFpr,
		arg.NewFpr,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.UpdatedAt,
		arg.Kind,
	)
	return err
}
