// Package sqlitedb is the SQL the SQLite store runs, as Go: one method on Queries for each
// statement in queries/sqlite/*.sql, with the parameter and row types sqlc derived from the schema in
// migrations/sqlite.
//
// Every .go file in this directory except this one is generated by sqlc (make sqlc, pinned to the version
// the Makefile names) and is not edited by hand; make sqlc-check fails when the committed files differ
// from what the sources produce. This file is the only hand-written .go file, and it holds only this
// comment. The package is imported by internal/core/store alone, which maps its rows to the store's
// domain types and is what the rest of the node calls (README.md in this directory says more).
package sqlitedb
