// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const consumeInviteUse = `-- name: ConsumeInviteUse :execrows
UPDATE invites SET uses = uses + 1
WHERE id = ? AND revoked_at IS NULL AND uses < max_uses AND expires_at > ?
`

type ConsumeInviteUseParams struct {
	ID        string
	ExpiresAt int64
}

func (q *Queries) ConsumeInviteUse(ctx context.Context, arg ConsumeInviteUseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeInviteUse, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInviteByHash = `-- name: GetInviteByHash :one
SELECT id, account_id, token_hash, expires_at, max_uses, uses, auto_accept, preset, permissions, label, revoked_at, created_at FROM invites WHERE account_id = ? AND token_hash = ?
`

type GetInviteByHashParams struct {
	AccountID string
	TokenHash []byte
}

func (q *Queries) GetInviteByHash(ctx context.Context, arg GetInviteByHashParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByHash, arg.AccountID, arg.TokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AutoAccept,
		&i.Preset,
		&i.Permissions,
		&i.Label,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByHashGlobal = `-- name: GetInviteByHashGlobal :one
SELECT id, account_id, token_hash, expires_at, max_uses, uses, auto_accept, preset, permissions, label, revoked_at, created_at FROM invites WHERE token_hash = ?
`

func (q *Queries) GetInviteByHashGlobal(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByHashGlobal, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AutoAccept,
		&i.Preset,
		&i.Permissions,
		&i.Label,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites (id, account_id, token_hash, expires_at, max_uses, auto_accept, preset, permissions, label, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInviteParams struct {
	ID          string
	AccountID   string
	TokenHash   []byte
	ExpiresAt   int64
	MaxUses     int64
	AutoAccept  int64
	Preset      string
	Permissions string
	Label       string
	CreatedAt   int64
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.AutoAccept,
		arg.Preset,
		arg.Permissions,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const listInvites = `-- name: ListInvites :many
SELECT id, account_id, token_hash, expires_at, max_uses, uses, auto_accept, preset, permissions, label, revoked_at, created_at FROM invites WHERE account_id = ? ORDER BY created_at, id
`

func (q *Queries) ListInvites(ctx context.Context, accountID string) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.Uses,
			&i.AutoAccept,
			&i.Preset,
			&i.Permissions,
			&i.Label,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	RevokedAt sql.NullInt64
	ID        string
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeInvite, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
