// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messaging.sql

package sqlitedb

import (
	"context"
)

const getBlob = `-- name: GetBlob :one
SELECT account_id, hash, size, mime, filename, created_at FROM blobs WHERE account_id = ? AND hash = ?
`

type GetBlobParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getBlob, arg.AccountID, arg.Hash)
	var i Blob
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.Size,
		&i.Mime,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByMsgID = `-- name: GetMessageByMsgID :one
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = ? AND contact_fpr = ? AND direction = ? AND msg_id = ?
`

type GetMessageByMsgIDParams struct {
	AccountID  string
	ContactFpr string
	Direction  string
	MsgID      string
}

func (q *Queries) GetMessageByMsgID(ctx context.Context, arg GetMessageByMsgIDParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByMsgID, arg.AccountID, arg.ContactFpr, arg.Direction, arg.MsgID)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.MsgID,
		&i.ThreadID,
		&i.Direction,
		&i.Sender,
		&i.Body,
		&i.ReplyTo,
		&i.Status,
		&i.CreatedAt,
		&i.Kind,
		&i.ExpiresAt,
		&i.Attempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, account_id, contact_fpr, topic, created_at, last_at, last_read_seq FROM threads WHERE account_id = ? AND id = ?
`

type GetThreadParams struct {
	AccountID string
	ID        string
}

func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, arg.AccountID, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactFpr,
		&i.Topic,
		&i.CreatedAt,
		&i.LastAt,
		&i.LastReadSeq,
	)
	return i, err
}

const insertBlob = `-- name: InsertBlob :exec
INSERT INTO blobs (account_id, hash, size, mime, filename, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertBlobParams struct {
	AccountID string
	Hash      string
	Size      int64
	Mime      string
	Filename  string
	CreatedAt int64
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertBlob,
		arg.AccountID,
		arg.Hash,
		arg.Size,
		arg.Mime,
		arg.Filename,
		arg.CreatedAt,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ExpiresAt  int64
	ID         string
	AccountID  string
	ContactFpr string
	MsgID      string
	ThreadID   string
	Direction  string
	Sender     string
	Kind       string
	Body       string
	ReplyTo    string
	Status     string
	CreatedAt  int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.MsgID,
		arg.ThreadID,
		arg.Direction,
		arg.Sender,
		arg.Kind,
		arg.Body,
		arg.ReplyTo,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listPendingOutbound = `-- name: ListPendingOutbound :many
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, kind, body, reply_to, status, created_at, expires_at, attempts, next_attempt_at
FROM messages WHERE direction = 'out' AND status = 'pending' ORDER BY seq LIMIT ?
`

func (q *Queries) ListPendingOutbound(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutbound, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(&i.Seq, &i.ID, &i.AccountID, &i.ContactFpr, &i.MsgID, &i.ThreadID,
			&i.Direction, &i.Sender, &i.Kind, &i.Body, &i.ReplyTo, &i.Status, &i.CreatedAt, &i.ExpiresAt,
			&i.Attempts, &i.NextAttemptAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertThread = `-- name: InsertThread :exec
INSERT INTO threads (id, account_id, contact_fpr, topic, created_at, last_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertThreadParams struct {
	ID         string
	AccountID  string
	ContactFpr string
	Topic      string
	CreatedAt  int64
	LastAt     int64
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) error {
	_, err := q.db.ExecContext(ctx, insertThread,
		arg.ID,
		arg.AccountID,
		arg.ContactFpr,
		arg.Topic,
		arg.CreatedAt,
		arg.LastAt,
	)
	return err
}

const listMessagesByThread = `-- name: ListMessagesByThread :many
SELECT seq, id, account_id, contact_fpr, msg_id, thread_id, direction, sender, body, reply_to, status, created_at, kind, expires_at, attempts, next_attempt_at FROM messages WHERE account_id = ? AND thread_id = ? ORDER BY seq
`

type ListMessagesByThreadParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) ListMessagesByThread(ctx context.Context, arg ListMessagesByThreadParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByThread, arg.AccountID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.MsgID,
			&i.ThreadID,
			&i.Direction,
			&i.Sender,
			&i.Body,
			&i.ReplyTo,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.ExpiresAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByAccount = `-- name: ListThreadsByAccount :many
SELECT id, account_id, contact_fpr, topic, created_at, last_at, last_read_seq FROM threads WHERE account_id = ? ORDER BY last_at DESC, id
`

func (q *Queries) ListThreadsByAccount(ctx context.Context, accountID string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ContactFpr,
			&i.Topic,
			&i.CreatedAt,
			&i.LastAt,
			&i.LastReadSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessageStatus = `-- name: SetMessageStatus :execrows
UPDATE messages SET status = ? WHERE account_id = ? AND contact_fpr = ? AND msg_id = ? AND direction = 'out'
`

type SetMessageStatusParams struct {
	Status     string
	AccountID  string
	ContactFpr string
	MsgID      string
}

func (q *Queries) SetMessageStatus(ctx context.Context, arg SetMessageStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMessageStatus, arg.Status, arg.AccountID, arg.ContactFpr, arg.MsgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markThreadRead = `-- name: MarkThreadRead :execrows
UPDATE threads SET last_read_seq = (
  SELECT COALESCE(MAX(m.seq), 0) FROM messages m WHERE m.account_id = ? AND m.thread_id = ?
) WHERE threads.account_id = ? AND threads.id = ?
`

type MarkThreadReadParams struct {
	AccountID   string
	ThreadID    string
	AccountID_2 string
	ID          string
}

func (q *Queries) MarkThreadRead(ctx context.Context, arg MarkThreadReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markThreadRead,
		arg.AccountID,
		arg.ThreadID,
		arg.AccountID_2,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumBlobBytes = `-- name: SumBlobBytes :one
SELECT COALESCE(SUM(size), 0) FROM blobs WHERE account_id = ?
`

func (q *Queries) SumBlobBytes(ctx context.Context, accountID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumBlobBytes, accountID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const touchThread = `-- name: TouchThread :exec
UPDATE threads SET last_at = ? WHERE account_id = ? AND id = ?
`

type TouchThreadParams struct {
	LastAt    int64
	AccountID string
	ID        string
}

func (q *Queries) TouchThread(ctx context.Context, arg TouchThreadParams) error {
	_, err := q.db.ExecContext(ctx, touchThread, arg.LastAt, arg.AccountID, arg.ID)
	return err
}

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*) FROM messages m JOIN threads t ON t.account_id = m.account_id AND t.id = m.thread_id
WHERE m.account_id = ? AND m.thread_id = ? AND m.direction = 'in' AND m.seq > t.last_read_seq
`

type UnreadCountParams struct {
	AccountID string
	ThreadID  string
}

func (q *Queries) UnreadCount(ctx context.Context, arg UnreadCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, unreadCount, arg.AccountID, arg.ThreadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessagesBefore = `-- name: DeleteMessagesBefore :execrows
DELETE FROM messages WHERE account_id = ? AND created_at < ?
`

type DeleteMessagesBeforeParams struct {
	AccountID string
	CreatedAt int64
}

func (q *Queries) DeleteMessagesBefore(ctx context.Context, arg DeleteMessagesBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessagesBefore, arg.AccountID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEmptyThreads = `-- name: DeleteEmptyThreads :execrows
DELETE FROM threads WHERE account_id = ?
  AND id NOT IN (SELECT thread_id FROM messages WHERE account_id = ?)
`

func (q *Queries) DeleteEmptyThreads(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyThreads, accountID, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listBlobs = `-- name: ListBlobs :many
SELECT account_id, hash, size, mime, filename, created_at FROM blobs WHERE account_id = ? ORDER BY created_at
`

func (q *Queries) ListBlobs(ctx context.Context, accountID string) ([]Blob, error) {
	rows, err := q.db.QueryContext(ctx, listBlobs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(&i.AccountID, &i.Hash, &i.Size, &i.Mime, &i.Filename, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const deleteBlob = `-- name: DeleteBlob :execrows
DELETE FROM blobs WHERE account_id = ? AND hash = ?
`

type DeleteBlobParams struct {
	AccountID string
	Hash      string
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBlob, arg.AccountID, arg.Hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countBlobRefs = `-- name: CountBlobRefs :one
SELECT COUNT(*) FROM blobs WHERE hash = ?
`

func (q *Queries) CountBlobRefs(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobRefs, hash)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const setMessageAttempt = `-- name: SetMessageAttempt :execrows
UPDATE messages SET attempts = ?, next_attempt_at = ?
WHERE account_id = ? AND contact_fpr = ? AND msg_id = ? AND direction = 'out'
`

type SetMessageAttemptParams struct {
	Attempts      int64
	NextAttemptAt int64
	AccountID     string
	ContactFpr    string
	MsgID         string
}

func (q *Queries) SetMessageAttempt(ctx context.Context, arg SetMessageAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMessageAttempt,
		arg.Attempts, arg.NextAttemptAt, arg.AccountID, arg.ContactFpr, arg.MsgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
