// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pact20.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const clearChainSentKids = `-- name: ClearChainSentKids :execrows
UPDATE contacts SET chain_sent_kid = '' WHERE account_id = ?
`

func (q *Queries) ClearChainSentKids(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearChainSentKids, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLeavesByState = `-- name: DeleteLeavesByState :execrows
DELETE FROM leaves WHERE account_id = ? AND state = ?
`

type DeleteLeavesByStateParams struct {
	AccountID string
	State     string
}

func (q *Queries) DeleteLeavesByState(ctx context.Context, arg DeleteLeavesByStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLeavesByState, arg.AccountID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingAddress = `-- name: DeletePendingAddress :execrows
DELETE FROM pending_addresses WHERE account_id = ? AND root = ?
`

type DeletePendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeletePendingAddress(ctx context.Context, arg DeletePendingAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingAddress, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTombstone = `-- name: DeleteTombstone :execrows
DELETE FROM tombstones WHERE account_id = ? AND root = ?
`

type DeleteTombstoneParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeleteTombstone(ctx context.Context, arg DeleteTombstoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTombstone, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPendingAddress = `-- name: GetPendingAddress :one
SELECT account_id, root, endpoint, leaf, why, at FROM pending_addresses WHERE account_id = ? AND root = ?
`

type GetPendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) GetPendingAddress(ctx context.Context, arg GetPendingAddressParams) (PendingAddress, error) {
	row := q.db.QueryRowContext(ctx, getPendingAddress, arg.AccountID, arg.Root)
	var i PendingAddress
	err := row.Scan(
		&i.AccountID,
		&i.Root,
		&i.Endpoint,
		&i.Leaf,
		&i.Why,
		&i.At,
	)
	return i, err
}

const insertFormerEndpoint = `-- name: InsertFormerEndpoint :exec
INSERT INTO former_endpoints (account_id, root, endpoint, at) VALUES (?, ?, ?, ?)
`

type InsertFormerEndpointParams struct {
	AccountID string
	Root      string
	Endpoint  string
	At        int64
}

func (q *Queries) InsertFormerEndpoint(ctx context.Context, arg InsertFormerEndpointParams) error {
	_, err := q.db.ExecContext(ctx, insertFormerEndpoint,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.At,
	)
	return err
}

const insertLeaf = `-- name: InsertLeaf :exec
INSERT INTO leaves (account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLeafParams struct {
	AccountID string
	Kid       string
	Leaf      []byte
	KeySealed []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	CreatedAt int64
}

func (q *Queries) InsertLeaf(ctx context.Context, arg InsertLeafParams) error {
	_, err := q.db.ExecContext(ctx, insertLeaf,
		arg.AccountID,
		arg.Kid,
		arg.Leaf,
		arg.KeySealed,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.CreatedAt,
	)
	return err
}

const listFormerEndpoints = `-- name: ListFormerEndpoints :many
SELECT account_id, root, endpoint, at FROM former_endpoints WHERE account_id = ? ORDER BY at, root, endpoint
`

func (q *Queries) ListFormerEndpoints(ctx context.Context, accountID string) ([]FormerEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listFormerEndpoints, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormerEndpoint
	for rows.Next() {
		var i FormerEndpoint
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaves = `-- name: ListLeaves :many
SELECT account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at FROM leaves WHERE account_id = ? ORDER BY created_at, kid
`

func (q *Queries) ListLeaves(ctx context.Context, accountID string) ([]Leaf, error) {
	rows, err := q.db.QueryContext(ctx, listLeaves, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaf
	for rows.Next() {
		var i Leaf
		if err := rows.Scan(
			&i.AccountID,
			&i.Kid,
			&i.Leaf,
			&i.KeySealed,
			&i.NotBefore,
			&i.NotAfter,
			&i.State,
			&i.Endpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAddresses = `-- name: ListPendingAddresses :many
SELECT account_id, root, endpoint, leaf, why, at FROM pending_addresses WHERE account_id = ? ORDER BY at, root
`

func (q *Queries) ListPendingAddresses(ctx context.Context, accountID string) ([]PendingAddress, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAddresses, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAddress
	for rows.Next() {
		var i PendingAddress
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.Leaf,
			&i.Why,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstones = `-- name: ListTombstones :many
SELECT account_id, root, leaf, at FROM tombstones WHERE account_id = ? ORDER BY at, root
`

func (q *Queries) ListTombstones(ctx context.Context, accountID string) ([]Tombstone, error) {
	rows, err := q.db.QueryContext(ctx, listTombstones, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tombstone
	for rows.Next() {
		var i Tombstone
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Leaf,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repinContactAddress = `-- name: RepinContactAddress :execrows
UPDATE contacts SET endpoint = ?, leaf = ?, spki = ?, pinned_at = ? WHERE account_id = ? AND fingerprint = ?
`

type RepinContactAddressParams struct {
	Endpoint    string
	Leaf        []byte
	Spki        []byte
	PinnedAt    sql.NullInt64
	AccountID   string
	Fingerprint string
}

func (q *Queries) RepinContactAddress(ctx context.Context, arg RepinContactAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, repinContactAddress,
		arg.Endpoint,
		arg.Leaf,
		arg.Spki,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireLeafKey = `-- name: RetireLeafKey :execrows
UPDATE leaves SET key_sealed = NULL, state = 'former' WHERE account_id = ? AND kid = ?
`

type RetireLeafKeyParams struct {
	AccountID string
	Kid       string
}

func (q *Queries) RetireLeafKey(ctx context.Context, arg RetireLeafKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireLeafKey, arg.AccountID, arg.Kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountHostPolicy = `-- name: SetAccountHostPolicy :execrows
UPDATE accounts SET accept_new_hosts = ?, accept_1x = ? WHERE id = ?
`

type SetAccountHostPolicyParams struct {
	AcceptNewHosts string
	Accept1x       int64
	ID             string
}

func (q *Queries) SetAccountHostPolicy(ctx context.Context, arg SetAccountHostPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountHostPolicy, arg.AcceptNewHosts, arg.Accept1x, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountLeafKey = `-- name: SetAccountLeafKey :execrows
UPDATE accounts SET fingerprint = ?, key_sealed = ?, algo = ? WHERE id = ?
`

type SetAccountLeafKeyParams struct {
	Fingerprint sql.NullString
	KeySealed   []byte
	Algo        string
	ID          string
}

func (q *Queries) SetAccountLeafKey(ctx context.Context, arg SetAccountLeafKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountLeafKey,
		arg.Fingerprint,
		arg.KeySealed,
		arg.Algo,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountProtocol = `-- name: SetAccountProtocol :execrows
UPDATE accounts SET protocol = ?, root_fingerprint = ?, root_cert = ? WHERE id = ?
`

type SetAccountProtocolParams struct {
	Protocol        int64
	RootFingerprint sql.NullString
	RootCert        []byte
	ID              string
}

func (q *Queries) SetAccountProtocol(ctx context.Context, arg SetAccountProtocolParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountProtocol,
		arg.Protocol,
		arg.RootFingerprint,
		arg.RootCert,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContactChainSentKid = `-- name: SetContactChainSentKid :execrows
UPDATE contacts SET chain_sent_kid = ? WHERE account_id = ? AND fingerprint = ?
`

type SetContactChainSentKidParams struct {
	ChainSentKid string
	AccountID    string
	Fingerprint  string
}

func (q *Queries) SetContactChainSentKid(ctx context.Context, arg SetContactChainSentKidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setContactChainSentKid, arg.ChainSentKid, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLeaf = `-- name: UpdateLeaf :execrows
UPDATE leaves SET leaf = ?, not_before = ?, not_after = ?, state = ?, endpoint = ? WHERE account_id = ? AND kid = ?
`

type UpdateLeafParams struct {
	Leaf      []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	AccountID string
	Kid       string
}

func (q *Queries) UpdateLeaf(ctx context.Context, arg UpdateLeafParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLeaf,
		arg.Leaf,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.AccountID,
		arg.Kid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upgradeContactPin = `-- name: UpgradeContactPin :execrows
UPDATE contacts SET fingerprint = ?, protocol = 2, endpoint = ?, leaf = ?, spki = ?, pinned_at = ? WHERE account_id = ? AND fingerprint = ?
`

type UpgradeContactPinParams struct {
	Fingerprint   string
	Endpoint      string
	Leaf          []byte
	Spki          []byte
	PinnedAt      sql.NullInt64
	AccountID     string
	Fingerprint_2 string
}

func (q *Queries) UpgradeContactPin(ctx context.Context, arg UpgradeContactPinParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upgradeContactPin,
		arg.Fingerprint,
		arg.Endpoint,
		arg.Leaf,
		arg.Spki,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPendingAddress = `-- name: UpsertPendingAddress :exec
INSERT INTO pending_addresses (account_id, root, endpoint, leaf, why, at) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (account_id, root) DO UPDATE SET endpoint = excluded.endpoint, leaf = excluded.leaf, why = excluded.why, at = excluded.at
`

type UpsertPendingAddressParams struct {
	AccountID string
	Root      string
	Endpoint  string
	Leaf      []byte
	Why       string
	At        int64
}

func (q *Queries) UpsertPendingAddress(ctx context.Context, arg UpsertPendingAddressParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingAddress,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.Leaf,
		arg.Why,
		arg.At,
	)
	return err
}

const upsertTombstone = `-- name: UpsertTombstone :exec
INSERT INTO tombstones (account_id, root, leaf, at) VALUES (?, ?, ?, ?)
ON CONFLICT (account_id, root) DO UPDATE SET leaf = excluded.leaf, at = excluded.at
`

type UpsertTombstoneParams struct {
	AccountID string
	Root      string
	Leaf      []byte
	At        int64
}

func (q *Queries) UpsertTombstone(ctx context.Context, arg UpsertTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, upsertTombstone,
		arg.AccountID,
		arg.Root,
		arg.Leaf,
		arg.At,
	)
	return err
}
