// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pact20.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const clearAccountKey = `-- name: ClearAccountKey :execrows
UPDATE accounts SET key_sealed = NULL WHERE id = ?
`

// The account's copy of its CURRENT leaf's key, destroyed when that leaf expires. The leaf ledger
// row is retired by RetireLeafKey; this is the other place the same key is held. The fingerprint
// stays: it is how every pin, route and audit row names this account, and it names a key the
// account no longer has - which is exactly what "awaiting a leaf" means.
func (q *Queries) ClearAccountKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearAccountKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearChainSentKids = `-- name: ClearChainSentKids :execrows
UPDATE contacts SET chain_sent_kid = '' WHERE account_id = ?
`

// After a leaf install every contact must see the new chain once (PACT sec. 13.2).
func (q *Queries) ClearChainSentKids(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearChainSentKids, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLeavesByState = `-- name: DeleteLeavesByState :execrows
DELETE FROM leaves WHERE account_id = ? AND state = ?
`

type DeleteLeavesByStateParams struct {
	AccountID string
	State     string
}

func (q *Queries) DeleteLeavesByState(ctx context.Context, arg DeleteLeavesByStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLeavesByState, arg.AccountID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingAddress = `-- name: DeletePendingAddress :execrows
DELETE FROM pending_addresses WHERE account_id = ? AND root = ?
`

type DeletePendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeletePendingAddress(ctx context.Context, arg DeletePendingAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingAddress, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTombstone = `-- name: DeleteTombstone :execrows
DELETE FROM tombstones WHERE account_id = ? AND root = ?
`

type DeleteTombstoneParams struct {
	AccountID string
	Root      string
}

func (q *Queries) DeleteTombstone(ctx context.Context, arg DeleteTombstoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTombstone, arg.AccountID, arg.Root)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPendingAddress = `-- name: GetPendingAddress :one
SELECT account_id, root, endpoint, leaf, why, at, root_cert FROM pending_addresses WHERE account_id = ? AND root = ?
`

type GetPendingAddressParams struct {
	AccountID string
	Root      string
}

func (q *Queries) GetPendingAddress(ctx context.Context, arg GetPendingAddressParams) (PendingAddress, error) {
	row := q.db.QueryRowContext(ctx, getPendingAddress, arg.AccountID, arg.Root)
	var i PendingAddress
	err := row.Scan(
		&i.AccountID,
		&i.Root,
		&i.Endpoint,
		&i.Leaf,
		&i.Why,
		&i.At,
		&i.RootCert,
	)
	return i, err
}

const insertFormerEndpoint = `-- name: InsertFormerEndpoint :exec
INSERT INTO former_endpoints (account_id, root, endpoint, at) VALUES (?, ?, ?, ?)
`

type InsertFormerEndpointParams struct {
	AccountID string
	Root      string
	Endpoint  string
	At        int64
}

func (q *Queries) InsertFormerEndpoint(ctx context.Context, arg InsertFormerEndpointParams) error {
	_, err := q.db.ExecContext(ctx, insertFormerEndpoint,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.At,
	)
	return err
}

const insertLeaf = `-- name: InsertLeaf :exec
INSERT INTO leaves (account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLeafParams struct {
	AccountID string
	Kid       string
	Leaf      []byte
	KeySealed []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	CreatedAt int64
}

func (q *Queries) InsertLeaf(ctx context.Context, arg InsertLeafParams) error {
	_, err := q.db.ExecContext(ctx, insertLeaf,
		arg.AccountID,
		arg.Kid,
		arg.Leaf,
		arg.KeySealed,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.CreatedAt,
	)
	return err
}

const listFormerEndpoints = `-- name: ListFormerEndpoints :many
SELECT account_id, root, endpoint, at FROM former_endpoints WHERE account_id = ? ORDER BY at, root, endpoint
`

func (q *Queries) ListFormerEndpoints(ctx context.Context, accountID string) ([]FormerEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listFormerEndpoints, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormerEndpoint
	for rows.Next() {
		var i FormerEndpoint
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKidsExcept = `-- name: ListKidsExcept :many
SELECT account_id, kid FROM leaves WHERE account_id != ? ORDER BY account_id, kid
`

type ListKidsExceptRow struct {
	AccountID string
	Kid       string
}

// Every leaf kid on this node that does NOT belong to one account. State20 asks
// this once per inbound envelope, to tell a kid held for a SIBLING identity from
// one this endpoint never held (PACT sec. 13.3, sec. 14.4). It used to be one
// query per other account, so the cost of every message grew with the number of
// identities the node hosts.
func (q *Queries) ListKidsExcept(ctx context.Context, accountID string) ([]ListKidsExceptRow, error) {
	rows, err := q.db.QueryContext(ctx, listKidsExcept, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKidsExceptRow
	for rows.Next() {
		var i ListKidsExceptRow
		if err := rows.Scan(&i.AccountID, &i.Kid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaves = `-- name: ListLeaves :many
SELECT account_id, kid, leaf, key_sealed, not_before, not_after, state, endpoint, created_at FROM leaves WHERE account_id = ? ORDER BY created_at, kid
`

func (q *Queries) ListLeaves(ctx context.Context, accountID string) ([]Leaf, error) {
	rows, err := q.db.QueryContext(ctx, listLeaves, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leaf
	for rows.Next() {
		var i Leaf
		if err := rows.Scan(
			&i.AccountID,
			&i.Kid,
			&i.Leaf,
			&i.KeySealed,
			&i.NotBefore,
			&i.NotAfter,
			&i.State,
			&i.Endpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAddresses = `-- name: ListPendingAddresses :many
SELECT account_id, root, endpoint, leaf, why, at, root_cert FROM pending_addresses WHERE account_id = ? ORDER BY at, root
`

func (q *Queries) ListPendingAddresses(ctx context.Context, accountID string) ([]PendingAddress, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAddresses, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAddress
	for rows.Next() {
		var i PendingAddress
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Endpoint,
			&i.Leaf,
			&i.Why,
			&i.At,
			&i.RootCert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTombstones = `-- name: ListTombstones :many
SELECT account_id, root, leaf, at FROM tombstones WHERE account_id = ? ORDER BY at, root
`

func (q *Queries) ListTombstones(ctx context.Context, accountID string) ([]Tombstone, error) {
	rows, err := q.db.QueryContext(ctx, listTombstones, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tombstone
	for rows.Next() {
		var i Tombstone
		if err := rows.Scan(
			&i.AccountID,
			&i.Root,
			&i.Leaf,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repinContactAddress = `-- name: RepinContactAddress :execrows
UPDATE contacts SET endpoint = ?, leaf = ?, spki = ?, pinned_at = ? WHERE account_id = ? AND fingerprint = ?
`

type RepinContactAddressParams struct {
	Endpoint    string
	Leaf        []byte
	Spki        []byte
	PinnedAt    sql.NullInt64
	AccountID   string
	Fingerprint string
}

// The 2.0 pin moves: a renewal at the pinned endpoint or an accepted new
// address replaces the leaf, its key and the endpoint; the root (the
// fingerprint column) never moves (PACT sec. 14.3, sec. 5.3).
func (q *Queries) RepinContactAddress(ctx context.Context, arg RepinContactAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, repinContactAddress,
		arg.Endpoint,
		arg.Leaf,
		arg.Spki,
		arg.PinnedAt,
		arg.AccountID,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retireLeafKey = `-- name: RetireLeafKey :execrows
UPDATE leaves SET key_sealed = NULL, state = 'former' WHERE account_id = ? AND kid = ?
`

type RetireLeafKeyParams struct {
	AccountID string
	Kid       string
}

// A superseded leaf past its not_after: the key is destroyed, the kid kept so
// an envelope still sealed to it is answered certificate_renewed (PACT sec. 14.4).
func (q *Queries) RetireLeafKey(ctx context.Context, arg RetireLeafKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireLeafKey, arg.AccountID, arg.Kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountHostPolicy = `-- name: SetAccountHostPolicy :execrows
UPDATE accounts SET accept_new_hosts = ? WHERE id = ?
`

type SetAccountHostPolicyParams struct {
	AcceptNewHosts string
	ID             string
}

func (q *Queries) SetAccountHostPolicy(ctx context.Context, arg SetAccountHostPolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountHostPolicy, arg.AcceptNewHosts, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountLeafKey = `-- name: SetAccountLeafKey :execrows
UPDATE accounts SET fingerprint = ?, key_sealed = ?, algo = ? WHERE id = ?
`

type SetAccountLeafKeyParams struct {
	Fingerprint sql.NullString
	KeySealed   []byte
	Algo        string
	ID          string
}

// Re-points the account at its CURRENT leaf key. SetAccountKey binds once and
// never moves; a leaf install moves it, keeping every fingerprint-keyed path
// (routing, audit, pins) on the key that signs and seals today.
func (q *Queries) SetAccountLeafKey(ctx context.Context, arg SetAccountLeafKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountLeafKey,
		arg.Fingerprint,
		arg.KeySealed,
		arg.Algo,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountRoot = `-- name: SetAccountRoot :execrows

UPDATE accounts SET root_fingerprint = ?, root_cert = ? WHERE id = ?
`

type SetAccountRootParams struct {
	RootFingerprint sql.NullString
	RootCert        []byte
	ID              string
}

// PACT 2.0 state (SPEC sec. 2, sec. 14; migration 0027): the account's root and leaf
// ledger, 2.0 pins, the removal tombstone, former endpoints, and the
// addresses awaiting the owner under `accept_new_hosts = ask`.
// The first leaf installed names the account's root; the root never changes after (PACT sec. 2).
func (q *Queries) SetAccountRoot(ctx context.Context, arg SetAccountRootParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountRoot, arg.RootFingerprint, arg.RootCert, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContactChainSentKid = `-- name: SetContactChainSentKid :execrows
UPDATE contacts SET chain_sent_kid = ? WHERE account_id = ? AND fingerprint = ?
`

type SetContactChainSentKidParams struct {
	ChainSentKid string
	AccountID    string
	Fingerprint  string
}

func (q *Queries) SetContactChainSentKid(ctx context.Context, arg SetContactChainSentKidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setContactChainSentKid, arg.ChainSentKid, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContactRootCert = `-- name: SetContactRootCert :execrows
UPDATE contacts SET root_cert = ? WHERE account_id = ? AND fingerprint = ? AND (root_cert IS NULL OR length(root_cert) = 0)
`

type SetContactRootCertParams struct {
	RootCert    []byte
	AccountID   string
	Fingerprint string
}

// Fills in a pin's root certificate the first time a chain carries one: a pin made
// before this column existed, or one restored from an archive that could not carry it.
// Never overwrites, because the root a pin names cannot change (PACT sec. 14.3) and the
// cert already stored is the one that was checked when the pin was made.
func (q *Queries) SetContactRootCert(ctx context.Context, arg SetContactRootCertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setContactRootCert, arg.RootCert, arg.AccountID, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stripAccountKeys = `-- name: StripAccountKeys :exec
UPDATE accounts SET key_sealed = NULL
`

// A data-only restore (PACT sec. 9): another host's archive arrives and every key in it is
// refused. Runs AFTER the restored store is migrated, so it always meets the current schema;
// the one other column that ever held key material, accounts.prev_key_sealed, is destroyed by
// migration 0031 rather than named here. Idempotent.
func (q *Queries) StripAccountKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, stripAccountKeys)
	return err
}

const stripLeafKeys = `-- name: StripLeafKeys :exec
UPDATE leaves SET key_sealed = NULL, state = 'former' WHERE state IN ('current', 'superseded', 'pending')
`

// The ledger's keys go and its rows stay, as former leaves, so an envelope sealed to one is
// answered certificate_renewed once the wallet has issued a leaf here (PACT sec. 14.4).
// Idempotent: a second run finds nothing in these states.
func (q *Queries) StripLeafKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, stripLeafKeys)
	return err
}

const updateLeaf = `-- name: UpdateLeaf :execrows
UPDATE leaves SET leaf = ?, not_before = ?, not_after = ?, state = ?, endpoint = ? WHERE account_id = ? AND kid = ?
`

type UpdateLeafParams struct {
	Leaf      []byte
	NotBefore int64
	NotAfter  int64
	State     string
	Endpoint  string
	AccountID string
	Kid       string
}

func (q *Queries) UpdateLeaf(ctx context.Context, arg UpdateLeafParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLeaf,
		arg.Leaf,
		arg.NotBefore,
		arg.NotAfter,
		arg.State,
		arg.Endpoint,
		arg.AccountID,
		arg.Kid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPendingAddress = `-- name: UpsertPendingAddress :exec
INSERT INTO pending_addresses (account_id, root, endpoint, leaf, why, at, root_cert) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (account_id, root) DO UPDATE SET endpoint = excluded.endpoint, leaf = excluded.leaf, why = excluded.why, at = excluded.at,
  -- A later note for the same root must not erase a certificate already kept: the
  -- envelope path has none to offer, and the root of a pending address cannot change.
  root_cert = COALESCE(excluded.root_cert, pending_addresses.root_cert)
`

type UpsertPendingAddressParams struct {
	AccountID string
	Root      string
	Endpoint  string
	Leaf      []byte
	Why       string
	At        int64
	RootCert  []byte
}

func (q *Queries) UpsertPendingAddress(ctx context.Context, arg UpsertPendingAddressParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingAddress,
		arg.AccountID,
		arg.Root,
		arg.Endpoint,
		arg.Leaf,
		arg.Why,
		arg.At,
		arg.RootCert,
	)
	return err
}

const upsertTombstone = `-- name: UpsertTombstone :exec
INSERT INTO tombstones (account_id, root, leaf, at) VALUES (?, ?, ?, ?)
ON CONFLICT (account_id, root) DO UPDATE SET leaf = excluded.leaf, at = excluded.at
`

type UpsertTombstoneParams struct {
	AccountID string
	Root      string
	Leaf      []byte
	At        int64
}

func (q *Queries) UpsertTombstone(ctx context.Context, arg UpsertTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, upsertTombstone,
		arg.AccountID,
		arg.Root,
		arg.Leaf,
		arg.At,
	)
	return err
}
