// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relay.sql

package sqlitedb

import (
	"context"
)

const ackRelay = `-- name: AckRelay :execrows
DELETE FROM relay_queue WHERE id = ? AND recipient_fpr = ?
`

type AckRelayParams struct {
	ID           string
	RecipientFpr string
}

func (q *Queries) AckRelay(ctx context.Context, arg AckRelayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ackRelay, arg.ID, arg.RecipientFpr)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearRelayAllow = `-- name: ClearRelayAllow :execrows
DELETE FROM relay_allowlist WHERE recipient_fpr = ?
`

func (q *Queries) ClearRelayAllow(ctx context.Context, recipientFpr string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearRelayAllow, recipientFpr)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRelayQueue = `-- name: CountRelayQueue :one
SELECT COUNT(*) FROM relay_queue WHERE recipient_fpr = ? AND expires_at > ?
`

type CountRelayQueueParams struct {
	RecipientFpr string
	ExpiresAt    int64
}

func (q *Queries) CountRelayQueue(ctx context.Context, arg CountRelayQueueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRelayQueue, arg.RecipientFpr, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const relayQueueUsage = `-- name: RelayQueueUsage :one
SELECT COUNT(*) AS items, COALESCE(SUM(size_bytes), 0) AS bytes
FROM relay_queue WHERE recipient_fpr = ? AND expires_at > ?
`

type RelayQueueUsageParams struct {
	RecipientFpr string
	ExpiresAt    int64
}

type RelayQueueUsageRow struct {
	Items int64
	Bytes interface{}
}

func (q *Queries) RelayQueueUsage(ctx context.Context, arg RelayQueueUsageParams) (RelayQueueUsageRow, error) {
	row := q.db.QueryRowContext(ctx, relayQueueUsage, arg.RecipientFpr, arg.ExpiresAt)
	var i RelayQueueUsageRow
	err := row.Scan(&i.Items, &i.Bytes)
	return i, err
}

const enqueueRelay = `-- name: EnqueueRelay :exec
INSERT INTO relay_queue (id, recipient_fpr, sender_fpr, msg_id, envelope, size_bytes, queued_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type EnqueueRelayParams struct {
	ID           string
	RecipientFpr string
	SenderFpr    string
	MsgID        string
	Envelope     string
	SizeBytes    int64
	QueuedAt     int64
	ExpiresAt    int64
}

func (q *Queries) EnqueueRelay(ctx context.Context, arg EnqueueRelayParams) error {
	_, err := q.db.ExecContext(ctx, enqueueRelay,
		arg.ID,
		arg.RecipientFpr,
		arg.SenderFpr,
		arg.MsgID,
		arg.Envelope,
		arg.SizeBytes,
		arg.QueuedAt,
		arg.ExpiresAt,
	)
	return err
}

const fetchRelayQueue = `-- name: FetchRelayQueue :many
SELECT id, recipient_fpr, sender_fpr, msg_id, envelope, size_bytes, queued_at, expires_at FROM relay_queue WHERE recipient_fpr = ? AND expires_at > ? ORDER BY queued_at, id LIMIT ?
`

type FetchRelayQueueParams struct {
	RecipientFpr string
	ExpiresAt    int64
	Limit        int64
}

func (q *Queries) FetchRelayQueue(ctx context.Context, arg FetchRelayQueueParams) ([]RelayQueue, error) {
	rows, err := q.db.QueryContext(ctx, fetchRelayQueue, arg.RecipientFpr, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelayQueue
	for rows.Next() {
		var i RelayQueue
		if err := rows.Scan(
			&i.ID,
			&i.RecipientFpr,
			&i.SenderFpr,
			&i.MsgID,
			&i.Envelope,
			&i.SizeBytes,
			&i.QueuedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredRelay = `-- name: PurgeExpiredRelay :execrows
DELETE FROM relay_queue WHERE expires_at <= ?
`

func (q *Queries) PurgeExpiredRelay(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredRelay, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const relayAllowed = `-- name: RelayAllowed :one
SELECT COUNT(*) FROM relay_allowlist WHERE recipient_fpr = ? AND sender_fpr = ?
`

type RelayAllowedParams struct {
	RecipientFpr string
	SenderFpr    string
}

func (q *Queries) RelayAllowed(ctx context.Context, arg RelayAllowedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, relayAllowed, arg.RecipientFpr, arg.SenderFpr)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const syncRelayAllow = `-- name: SyncRelayAllow :exec
INSERT INTO relay_allowlist (recipient_fpr, sender_fpr, updated_at) VALUES (?, ?, ?)
ON CONFLICT (recipient_fpr, sender_fpr) DO UPDATE SET updated_at = excluded.updated_at
`

type SyncRelayAllowParams struct {
	RecipientFpr string
	SenderFpr    string
	UpdatedAt    int64
}

func (q *Queries) SyncRelayAllow(ctx context.Context, arg SyncRelayAllowParams) error {
	_, err := q.db.ExecContext(ctx, syncRelayAllow, arg.RecipientFpr, arg.SenderFpr, arg.UpdatedAt)
	return err
}
